### ISSUE TITLE
Simple syntax errors not caught by diagnostics

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#102]
Some compiler errors are not pointed out by diagnostics. This can be quite frustrating, because otherwise diagnostics are reliable enough that I've started to assume "the code will compile" when every red line is gone. Getting compiler errors at that point can be confusing. The red squiggles here only appear after running the build task:

![](http://i.imgur.com/UGdZf68.gif)

This is because the `@diagnostics` display mode is somewhat error-tolerant (rightly so) and doesn't care about e.g. missing semicolons.

I think we could detect these types of errors fairly easily with hxparer's parse tree, once that is ready.

**Comment by nadako** [comment]
Yes, once we have hxparser with diagnostic reporting and incremental parsing, we could update such diagnostics on the fly.

**Comment by Gama11** [comment]
We can't get rid of compiler-provided diagnostics entirely. There's no way we could provide import suggestions in vshaxe for instance, the parse tree doesn't help much for that.

**Comment by nadako** [comment]
Well, sure, I mean we would just combine diagnostics from two places: local hxparser and the compiler. 

However ideally we would connect to the haxe server and incrementally-update there and give diagnostics for both syntax and typing, but that's a long term goal.

**Comment by Gama11** [comment]
Should be able to solve this with the discussed `display/parse` API, which tells Haxe to parse (in "strict" / non-display mode) a file and returns the error, if any.

We could then combine that with the other diagnostics (or choose not to show them until parser errors have been resolved, not sure yet).

**Comment by Gama11** [comment]
Haxe now reports parser errors in diagnostics mode. While it's not perfect yet and misses a few things, it's already a huge improvement:

![](https://i.imgur.com/xzvmet1.png)
