### ISSUE TITLE
List of symbols in "not-in-project" hx files

### ISSUE THREAD

**Issue by RealyUniqueName** [vshaxe/vshaxe#105]
That would be great to get a list of symbols in hx files which are not included in a project or current classpath.
Atm when i surf through std lib or open a single hx file without opening a project i have to search for methods via ordinary CTRL+F search instead of "Go to symbol in file".

**Comment by Gama11** [comment]
Haha.. this actually "just works" if this check here is removed:

![](http://i.imgur.com/qxhxDBg.png)

![](http://i.imgur.com/7XEZnME.png)

**Comment by Gama11** [comment]
In fact, in the Haxe std lib, this seems to work for pretty much all display features. I'm starting to think that in a lot of cases, a display config isn't really necessary.
