### ISSUE TITLE
Go to definition not always functional

### ISSUE THREAD

**Issue by gogoprog** [vshaxe/vshaxe#106]
Hello,

I tested the Go to definition feature on a small haxe codebase and it was fine.

Then I tried it with an OpenFL project but I always get 'No definition found for...'.

Where can I find debug log to see what's failing?

**Comment by ibilon** [comment]
Is autocompletion working on the openfl project?

**Comment by Gama11** [comment]
You should see some details in the Haxe output channel:

![](http://i.imgur.com/WJcqOv5.gif)

Note: you'll get more detailed output if you add the following to your settings:

```json
"haxe.displayServer": {
    "arguments": ["-v"],
}
```

**Comment by Gama11** [comment]
Note that in a small, pure Haxe project, completion features may work fine without any additional setup. However, as soon as you have dependencies (like OpenFL), vshaxe needs a hxml file / display arguments to account for that. See also:

- https://github.com/vshaxe/vshaxe/wiki/Framework-Notes
- https://github.com/vshaxe/vshaxe/wiki/Configuration#display-configurations-and-display-server

**Comment by gogoprog** [comment]
No, auto-completion does not work either, here is my output :

```Type not found : ApplicationMain```

So in my case it comes from the fact that I have to build the project from a different directory.
How to set that for the haxe language server?

**Comment by Gama11** [comment]
What does your setup looks like?

You could add `--cwd <directory>`, like so:

```js
{
    "haxe.displayConfigurations": [
        ["--cwd", "<directory>", "build.hxml"]
    ]
}
```

**Comment by gogoprog** [comment]
Thanks @Gama11 it was exactly that

```{
    "haxe.displayConfigurations": [
        ["--cwd", "myproject/haxe", "Export/html5/haxe/release.hxml"],
    ]
}
```

I think this should be added in the Framework Notes https://github.com/vshaxe/vshaxe/wiki/Framework-Notes

**Comment by Gama11** [comment]
Glad you got it working. :)

I think https://github.com/vshaxe/vshaxe/wiki/Configuration might be a better place, as it's not really framework-specific.

**Comment by Gama11** [comment]
Alright, I've adjusted the docs a bit. There is now a new subsection for the Display Configurations docs:

https://github.com/vshaxe/vshaxe/wiki/Configuration#changing-the-working-directory

I also added a new "Troubleshooting" page:

https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

**Comment by gogoprog** [comment]
Great job :+1:
