### ISSUE TITLE
Use upcoming progress bar API during cache initialization

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#108]
It would be nice to have a progress bar that indicates the state of the completion cache (or indicates that it's a thing at all, a lot of users wouldn't know unless they check the Haxe output channel). This should be doable using the planned progress bar API: https://github.com/Microsoft/vscode/issues/18066

**Comment by nadako** [comment]
I added some simple progress reporting for "initializing cache" using the new progress API. It looks cute, but I think we're missing some error reporting in case it fails badly :)

**Comment by Gama11** [comment]
Well, there's some output in the Haxe output channel.. It probably happens quite often currently that the project doesn't compile when starting up VSCode, in which case "caching" would fail, so I originally didn't want it to be too intrusive. It sucks that caching isn't more robust / really needs everything to be compilable...

**Comment by Gama11** [comment]
Closing this for now, if we want better error handling, that belongs in a separate issue. :)
