### ISSUE TITLE
Completion inside anonymous structures can be improved

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#110]
This is how it works currently (using luxe's Sprite options as an example)

**Case 1 works**

<img width="517" alt="capture d ecran 2017-03-20 a 16 55 58" src="https://cloud.githubusercontent.com/assets/164094/24108697/a4794680-0d8e-11e7-85f3-597b372ff915.png">

**Case 2 works, but can be improved**

This is rather minor, but the property ``centered`` is still provided in the suggestions even though it is already used in the structure. Ideally, we would want to remove it from the suggestions, as the suggestion is no longer valid (we never put twice the same property in a structure, right?).

<img width="524" alt="capture d ecran 2017-03-20 a 16 57 38" src="https://cloud.githubusercontent.com/assets/164094/24108700/a7c9e07e-0d8e-11e7-9dbd-b8dac00fc847.png">

**Case 3 doesn't work at all**

Then, as soon as we have some complex code (parenthesis, anonymous function...) between ``{`` and the cursor, it doesn't work at all and switches back to toplevel completion.

<img width="520" alt="capture d ecran 2017-03-20 a 16 58 44" src="https://cloud.githubusercontent.com/assets/164094/24108708/ae920152-0d8e-11e7-8255-d2195ae76195.png">

Is there any plan to improve this (short term, with current haxe) ?

I am asking because if not, these is some code in tides (https://github.com/snowkit/tides) that helps handling those cases (even with an anonymous function containing complex code inside the structure, it works), and I can make a pull request to make these work (without creating a dependency to _tides_ obviously. Just by extracting the code useful for the task and adding a utility to haxe-languageServer repo that would be used instead of the current regular expression (https://github.com/vshaxe/haxe-languageserver/blob/8d5c214131f6f014bb2ecfd2ff2a467ff1c0fd11/src/haxeLanguageServer/features/CompletionFeature.hx#L41))

EDIT : forgot to say comments are also breaking completion, as the regular expression doesn't handle this either. This is handled in _tides_ code.

**Comment by Gama11** [comment]
For case 2, see https://github.com/HaxeFoundation/haxe/issues/5767.

We decide whether or not to invoke field or toplevel completion based on a regex right now, which is not very robust. The real blocking issue here is https://github.com/HaxeFoundation/haxe/issues/6005 however, which made me hesitate to enable struct completion in more cases.

**Comment by jeremyfa** [comment]
Yes, I did mention the regex you are talking about in my post. My point was I can make a pull request to replace this regex with some smarter parsing code (which is already successfully used in atom for months), unless you already have a better plan ahead (do you ?).

The parsing code also provides informations to help handle case 2, but it's even better if this can be provided by the haxe compiler of course.

**Comment by Gama11** [comment]
We're planning to integrate the hxparser parse tree into vshaxe sooner or later (https://github.com/vshaxe/hxparser), so I don't think it makes too much sense to integrate some other parsing logic.

Apart from that, I'm not sure it's a good idea to have struct completion in more places until that Haxe hanging issue is resolved, as it's quite likely to break completion alltogether.

**Comment by jeremyfa** [comment]
Right, then looking forward to seeing hxparser integration and the haxe bug fixed then. Thanks!

**Comment by Gama11** [comment]
This now works really well with the display protocol changes in latest Haxe 4 dev. Haxe only suggests fields that are not filled in yet and it's not limited to only working in calls (we don't have any regexes anymore, Haxe handles all that, and toplevel + field completion were unified):

![](https://i.imgur.com/fqZ6DPJ.png)
