### ISSUE TITLE
How to configure auto-complete?

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#111]
Hey,
First, very nice extension! thanks!

I have a problem to establish auto complete to my project, this is my `build.hxml`:
```
-cp src
-main server.Server
-js bin/hxconify.js

-lib hxnodejs
-lib js-kit
--macro npm.Package.export("bin/package.json")

--next

-cp src
-main client.Client
-js bin/public/js/hxconify.js

-lib react
-D react_global
```
And this is `.vscode/settings.json`:
```json
{
    "haxe.displayConfigurations": [
        ["build.hxml"]
    ]
}
```

What I'm doing wrong?
Michael

**Comment by nadako** [comment]
Please read the [configuration](https://github.com/vshaxe/vshaxe/wiki/Configuration) manual page. Currently, vshaxe requires an argument set that is suitable for display queries, so `--next`/`--cmd` and so on is a bad idea for completion.
