### ISSUE TITLE
Switch case colon triggers completion

### ISSUE THREAD

**Issue by mrcdk** [vshaxe/vshaxe#112]
![](http://i.imgur.com/EYJCySA.png)

Whenever I use the colon for the case it triggers some kind of completion (toplevel completion?)

**Comment by Simn** [comment]
This is really annoying. Does anyone feel responsible for fixing this? I don't really understand why this sends a toplevel-completion request. Isn't that something that should only happen upon explicit user request?

**Comment by nadako** [comment]
I guess it tries to complete a type hint here...

**Comment by Simn** [comment]
But a type hint should not request toplevel completion either.

**Comment by Gama11** [comment]
Why not?

**Comment by Simn** [comment]
I'm confused. Apparently it does send toplevel completion for type hints, but the result doesn't include local variables and fields and such. How does that work?

**Comment by Gama11** [comment]
No idea, maybe Haxe handles that? vshaxe certainly doesn't.

**Comment by Gama11** [comment]
Anyway, if you implement incremental parsing, we can just check whether we're after a `case` and not invoke completion. ;)

**Comment by Simn** [comment]
Why does that need incremental parsing?

**Comment by Simn** [comment]
I see now what's going on in Haxe: The parser always resumes on a `:` if the display position matches. It then inserts a `""` type-hint which the type loader picks up to emit a type-only toplevel collection.

So I still think vshaxe shouldn't request toplevel completion here, but rather "default" completion.

**Comment by Gama11** [comment]
So toplevel and "default" completion behave the same here?

>Why does that need incremental parsing?

Well, otherwise, we'd have to reparse the file on every completion request (at least if the file was changed). Not that I've tried, but that seems quite expensive.

**Comment by Simn** [comment]
Well, if we're talking expensive, running a toplevel completion on every colon is pretty damn expensive as well. So if that hasn't bothered anyone, I doubt parsing the file would.

> So toplevel and "default" completion behave the same here?

Yes, at least that's what the code tells me. If we request completion on a type-hint, we get type-hint completion.

**Comment by ncannasse** [comment]
What's the take on this then ? we don't really want to keep it as-it, it's annoying :)

**Comment by ncannasse** [comment]
I agree a full-proof solution will require extra work, but can I suggest the following for now:
- if you hit `:` look at the line content. if there's a `case` or `default` with no other `:` between this one and the keyword, don't trigger completion.

**Comment by Gama11** [comment]
I think I've considered that before, but discarded it because `case` expressions can be quite complex. You would have additional `:` between `case` start and end when matching against a structure for instance, or even just a string with a `:` in it.

However, since this is just about canceling completion in some cases, it would still be better than what we have now and catch most cases, even if not perfect.

**Comment by ncannasse** [comment]
Yes it's not perfect but should cover 98% of the cases already (pun
intended)

**Comment by Gama11** [comment]
This should now be fixed in all scenarios, as Haxe now handles this with the new protocol - no more regex hacks to decide between toplevel and field completion. :)

**Comment by RblSb** [comment]
Well, not anymore... Some info how new protocol handled that would be nice to have.
