### ISSUE TITLE
Completion became super slow after last VSCode update (1.11.0)

### ISSUE THREAD

**Issue by Tiago-Ling** [vshaxe/vshaxe#114]
Before the update completion was fast, no problems whatsoever, but after updating (through the application itself) and reloading the window, any time a completion window pops up it'll be in "loading..." mode for up to 5-7 seconds.

I'm using Haxe 3.4.2 (git build development @ ada466c)

Anything i might have done wrong or have to set up to fix this? Or is this a bug?

Thanks!

**Comment by Gama11** [comment]
I can't think of any changes in 1.5.0 that might have caused this. Would be nice to see the direct comparison to 1.4.0, but I guess you'd have too build from source for that...

Did you update to VSCode 1.11.0 at the same time?

**Comment by Tiago-Ling** [comment]
Hmmm, i think you're right - i updated the extension and after that updated VSCode itself.

**Comment by Gama11** [comment]
Well, in that case, does downgrading VSCode to 1.10.0 make a difference?

**Comment by Tiago-Ling** [comment]
Downgraded to 1.10.2 (the same i was using before) but the delay continues - it appears to be slightly faster than before, but the problem persists.

**Comment by Gama11** [comment]
Very strange, I haven't noticed any issues like this. Could this be related to the completion cache rather than vshaxe / VSCode versions? Perhaps it's not initializing successfully? (https://github.com/vshaxe/vshaxe/wiki/Completion-Cache)

> tried to uninstall all extensions manually first [...]

`code` has a command line argument for this: `--disable-extensions`. Not sure if you could still install vshaxe in that state though, which you'd need to do for testing..

**Comment by Tiago-Ling** [comment]
Another possibility: compiler errors preventing completion cache from working correctly. This is caused because the project is acting as if the selected target was Flash, when it is in fact made for desktop only.

As an example, when i tried checking `openfl.display.Shader` by Ctrl+Clicking it, it took me to the Flash externs instead of the "real" class. 

Is there a way to change / fix this?

**Comment by Tiago-Ling** [comment]
Hmmm, ok, i think i found it, sorry for not reading the wiki first! Looks like somehow my display configuration was changed to "flash debug" with one of the updates. This caused the errors and prevented the completion cache from finishing. 

I didn't know about display configuration so far, but the problem didn't happen in the past - does the extension set it automatically based on the last build or something?

**Comment by Gama11** [comment]
>does the extension set it automatically based on the last build or something?

No, tasks and display configurations are totally indepedent of each other right now. Vshaxe doesn't do anything task-related at all.

**Comment by Tiago-Ling** [comment]
Hmmm, strange - i don't recall ever changing display configuration before. Could be my mistake then, but would the extension reset folder-specific settings such as this? I don't think so, that may be the case of uploading both at the same time (don't recall the order though).

**Comment by Gama11** [comment]
It looks like the current display configuration is persisted via VSCode's so-called Memento" API:

https://github.com/vshaxe/vshaxe/blob/1.5.0/src/vshaxe/DisplayConfiguration.hx#L106

Not sure if / when that is cleared (or where it's even located). Do you know anything about this, @nadako?

**Comment by Tiago-Ling** [comment]
It looks like a bug on my side though - if you updated and your project settings were intact, could be something that i did unknowingly.

This weird case could be included somewhere in the wiki (maybe into troubleshooting?)

**Comment by Gama11** [comment]
I'm not sure why having a different display configuration was even an issue in the first place. Is the Flash display config that much slower for you? Is this a big project?

**Comment by nadako** [comment]
> Not sure if / when that is cleared (or where it's even located). Do you know anything about this, @nadako?

I think it's reset to the "first" configuration if the current one no longer exists, as to where it's stored - no idea 🤷

**Comment by Tiago-Ling** [comment]
That's what i think too - the first display configuration is "flash debug", probably reverted to that due to some unknown reason, which apparently does not happen for every update.

Closing this one since it is not a bug.
