### ISSUE TITLE
Method signature in trace ( 'string' ) shows trace signature

### ISSUE THREAD

**Issue by fzzr-** [vshaxe/vshaxe#115]
![screen shot 2017-04-23 at 14 52 58](https://cloud.githubusercontent.com/assets/888526/25313353/76e540d6-2835-11e7-89cd-94c3f51be92f.png)

**Comment by nadako** [comment]
That's actually a Haxe issue...

**Comment by fzzr-** [comment]
Not found anything like it in the (Haxe/issues](https://github.com/HaxeFoundation/haxe/issues). Should I open a new issue there?

**Comment by Gama11** [comment]
Reported to Haxe: https://github.com/HaxeFoundation/haxe/issues/6265
