### ISSUE TITLE
Standalone Server

### ISSUE THREAD

**Issue by camboris** [vshaxe/vshaxe#116]
I'm trying to use the lsp server with neovim. I didn't find any info about this, so I'm running `node server_wrapper.js` and it seems to work. But when I start neovim, it complains that it can't read `displayConfigurationIndex` from undefined.
I read the code and it seems to be read from some vscode Context info. There is a way I can pass the displayConfiguration hxml by command line or can you give any pointer in how to configure this?

I'm using https://github.com/autozimu/LanguageClient-neovim

**Comment by nadako** [comment]
`displayConfigurationIndex` is a member of `InitializeParams.initializationOptions` object. It's haxe-languageserver specific and represents the index of the currently selected display configuration. We might want to handle it more gracefully...

**Comment by camboris** [comment]
I see it's being used in the `onInitialize`  function in `Context.hx` . Do you know if there is a way to setup `params.initializationOptions` before the method is called? vscode seems to read settings.json, where `DisplayConfiguration` points to the `build.hxml` file needed for completion.

**Comment by nadako** [comment]
Well, passing correct `initializationOptions` is the job of the client. For vshaxe we use microsoft's vscode client which indeed reads stuff from vscode settings. For the neovim client, there must be some setting, I guess?

**Comment by nadako** [comment]
Hmm, I think vscode client sends `didChangeConfiguration` on initialization to pass the settings to the server, but searching for `didChangeConfiguration` in the `LanguageClient-neovim` yields nothing...

**Comment by camboris** [comment]
Yes, I don't see any way to pass config info, so I'm going to follow it from the client side. Thank you.

**Comment by Gama11** [comment]
@camboris Out of curiosity, did you have any luck getting this to work? :)

**Comment by camboris** [comment]
@Gama11 I silenced the errors by adding an empty `initializationOptions`  object in the `initialize` call of the neovim client, but I didn't do much else. I was going to try to hardcode the hxml path to see if I could get completion working but I got distracted with other projects.  It's on my pending list, along with making a neovim api client in haxe.

**Comment by camboris** [comment]
After adding an empty `initializationOptions` object, I'm getting `Unhandled method` for anything I try. This happens because the methods are registered when the `workspace/didChangeConfiguration` event is received, and the neovim plugin isn't sending that. Next step is to add that and figure what options I have to send
