### ISSUE TITLE
New tasks.json format doesn't seem to work the same way it used to

### ISSUE THREAD

**Issue by andywhite37** [vshaxe/vshaxe#119]
I have vshaxe 1.5.1 installed.

I have a small haxe project like this:

`Main.hx`
```
class Main {
  public static function main() {
    trace('hi');
  }
}
```

`build.hxml`
```
-main Main
-js main.js
-cmd node main.js
```

When I run "Haxe: Initialize VS Code Project..." I get a tasks.json file like this:

`.vscode/tasks.json`
```
{
    "version": "2.0.0",
    "command": "haxe",
    "args": ["build.hxml"],
    "problemMatcher": "$haxe"
}
```

When I run the build now, the task writes the compiler output to the terminal, rather than in the Problems/Output tabs like it used to.

When I change the tasks.json to the older style (below), it works like it used to (compiler errors go to the "Output" tab, etc.)

`.vscode/tasks.json` (old format)
```
{
    "version": "0.1.0",
    "command": "haxe",
    "args": ["build.hxml"],
    "problemMatcher": {
        "owner": "haxe",
        "pattern": {
            "regexp": "^(.+):(\\d+): (?:lines \\d+-(\\d+)|character(?:s (\\d+)-| )(\\d+)) : (?:(Warning) : )?(.*)$",
            "file": 1,
            "line": 2,
            "endLine": 3,
            "column": 4,
            "endColumn": 5,
            "severity": 6,
            "message": 7
        }
    }
}
```

Is it something related to the `version` 2.0.0 change?  Or is there something I need to do to get the `"problemMatcher": "$haxe"` to work the way it used to?

**Comment by Gama11** [comment]
What VSCode version are you using? You need the latest version (1.11.2) for `"problemMatcher": "$haxe"` to work).

Tasks.json version 2 does indeed output to the terminal instead of the output panel (mentioned [here](https://code.visualstudio.com/updates/v1_10#_more-work-on-terminal-runner)).

**Comment by andywhite37** [comment]
I do have VSCode 1.11.2, so I guess the problem matcher is working.  I do see build errors appearing in the `Problems` tab - I guess I missed that before.

This might be more of a VS Code question, but is there any way to have it show the `Problems` tab rather than the `Terminal` tab after running a task?

**Comment by Gama11** [comment]
Not directly, I think. What you could do is manually open the problems tab and then set `"showOutput"` in `tasks.json` to `"never"` or `"silent"` to avoid switching back to the Terminal.

That behvaior hasn't changed with the terminal runner though, IIRC? It used to switch to the Output panel, so you manually had to open the Problems view there as well.

**Comment by andywhite37** [comment]
Yeah, I think my problem was that I was happy to see the Output pane in the previous world, but not as happy to see the terminal output.  Thanks for your comments, it was very helpful.
