### ISSUE TITLE
Completion requests queued up

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#12]
Copied from Gitter:
> on vscode haxe, do the completion requests queue up? I mean when I am typing, the IDE should be sending requests to the completion server continuously, will the server discard the old one when it receive a new one, or they just queue up? My problem is that the haxe process used up 100% CPU for like a few minutes even I stopped typing anything. (and completion just won’t work during that period)

**Comment by nadako** [comment]
This is actually a [haxe-languageserver](https://github.com/vshaxe/haxe-languageserver) issue, I'll move it there.
