### ISSUE TITLE
@:noCompletion and @:isVar do not appear in the auto-completion list

### ISSUE THREAD

**Issue by Jarrio** [vshaxe/vshaxe#121]
When typing `@:noCompletion` or `@:isVar` the auto-suggestion doesn't appear for it. There may be more missing from the list that I just have not come across.

![gif](https://cloud.githubusercontent.com/assets/748557/26176285/7f1d0d12-3b4d-11e7-9431-2a4268db1be0.gif)

Typing `@:comp..` gets it to appear as does `@:var`

**Comment by Gama11** [comment]
Huh, seems like for a `camelCase` name, it only matches starting with `Case` - typing `camel` makes the entry disappear from the list.

**Comment by Gama11** [comment]
Ok, I tested this with several old VSCode versions. This worked fine in the February release (1.10) and broke starting with the March release (1.11). Still an issue with the latest Insider's build (Microsoft/vscode@ec76a9fc5146b822cdb14b982ac3e5b470dd646a) as well.

**Comment by Gama11** [comment]
Bisected it to Microsoft/vscode@264908a434e98f9b22f8de358b3636200c332ea4. Will report to vsocde later.

**Comment by Gama11** [comment]
This should be fixed in the upcoming VSCode May release.

**Comment by Gama11** [comment]
Actually, I just pushed a fix on the vshaxe side, so this works even without the VSCode change. There's still an annoying issue where the completion list closes and reopens when typing the `:`, but that's fixed in the next VSCode update.
