### ISSUE TITLE
AutoComplete isnot working on mac

### ISSUE THREAD

**Issue by mohGhazala96** [vshaxe/vshaxe#126]
AutoComplete is not working on my mac while haxe is working properly on cpp.
here is the output in vs code:
```
Haxe language server started
Initializing completion cache...
Processing Arguments [export/mac/cpp/haxe/release.hxml,--no-output]
> Error: Could not process argument export/mac/cpp/haxe/release.hxml (file not found)
invalid character: /
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Failed - try fixing the error(s) and restarting the language server:

Error: Could not process argument export/mac/cpp/haxe/release.hxml (file not found)
invalid character: /
Processing Arguments [--cwd,/Users/AbouGhazala/Desktop/carWars,export/mac/cpp/haxe/release.hxml,-D,display-details,--no-output,--display,/Users/AbouGhazala/Desktop/carWars/source/state/mode/Mode.hx@0@diagnostics]
> Error: Could not process argument export/mac/cpp/haxe/release.hxml (file not found)
invalid character: /
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Error: Could not process argument export/mac/cpp/haxe/release.hxml (file not found)
invalid character: /
```

**Comment by Gama11** [comment]
Have you verified the path is correct? Might be necessary to change `mac`  to `mac64`.

**Comment by mohGhazala96** [comment]
I discovered it was mac64 but when i change it to mac a different error is shown saying that the standard library is not found:
_________________________
Haxe language server started
Initializing completion cache...
Processing Arguments [export/mac/cpp/haxe/release.hxml,--no-output]
Defines FLX_NO_TOUCH=1,HXCPP_QUIET=1,NAPE_RELEASE_BUILD=1,cpp=1,dce=std,desktop=1,djFlixel=0.2.0,flixel-addons=2.4.1,flixel=4.2.1,flixel_addons=2.4.1,haxe3=1,haxe_ver=3.4,hxcpp=3.4.49,hxcpp_api_level=331,lime-legacy=1,lime-native=1,lime=2.9.1,lime_legacy=1,lime_native=1,mac=1,nape=2.0.20,native=1,no-compilation=1,no_compilation=1,openfl-legacy=1,openfl-native=1,openfl=3.6.1,openfl_legacy=1,openfl_native=1,poly2trihx=0.1.4,source-header=Generated by Haxe 3.4.0,sys=1,tools=2.9.1,true=1
Using signature f1143edde8c20db6e6c861736c349c30
Display position: ?: -1--1
> Standard library not found
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Failed - try fixing the error(s) and restarting the language server:

Standard library not found
Processing Arguments [--cwd,/Users/AbouGhazala/Desktop/carWars,export/mac/cpp/haxe/release.hxml,-D,display-details,--no-output,--display,/Users/AbouGhazala/Desktop/carWars/source/state/mode/Mode.hx@0@diagnostics]
Defines FLX_NO_TOUCH=1,HXCPP_QUIET=1,NAPE_RELEASE_BUILD=1,cpp=1,dce=std,desktop=1,display-details=1,display=diagnostics,display_details=1,djFlixel=0.2.0,flixel-addons=2.4.1,flixel=4.2.1,flixel_addons=2.4.1,haxe3=1,haxe_ver=3.4,hxcpp=3.4.49,hxcpp_api_level=331,lime-legacy=1,lime-native=1,lime=2.9.1,lime_legacy=1,lime_native=1,mac=1,nape=2.0.20,native=1,no-compilation=1,no_compilation=1,no_copt=1,openfl-legacy=1,openfl-native=1,openfl=3.6.1,openfl_legacy=1,openfl_native=1,poly2trihx=0.1.4,source-header=Generated by Haxe 3.4.0,sys=1,tools=2.9.1,true=1
Using signature f1143edde8c20db6e6c861736c349c30
Display position: /Users/AbouGhazala/Desktop/carWars/source/state/mode/Mode.hx: 0-0
> Standard library not found
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Standard library not found

**Comment by mohGhazala96** [comment]
@Gama11 i fixed the paths issue now i dont get any errors in the output, and to make sure I ran the built in haxe tutorials and i dont get an error in the output and the autocomplete doesn't work. 
please help!

**Comment by Gama11** [comment]
This seems like an issue with your setup, not with vshaxe. Try searching around a bit, this might be relevant for instance:

http://community.openfl.org/t/compiling-error-standard-library-not-found-in-previously-working-install/7243/4

If all else fails, you could try to reinstall Haxe.
