### ISSUE TITLE
Problems with Add Import

### ISSUE THREAD

**Issue by rjewson** [vshaxe/vshaxe#128]
Add Import as described here [https://github.com/vshaxe/vshaxe/wiki/Code-Actions](https://github.com/vshaxe/vshaxe/wiki/Code-Actions) never works for me.  Should it? I know there are issues with auto completing classes in the classpath and that these two are probably linked somehow.

**Comment by Gama11** [comment]
Have you checked whether it's one of the two "known isuses" described there?

**Comment by rjewson** [comment]
I don't think so.  The class I'm trying to auto add is already know to the compiler via an import in another class that is defiantly being compiled.

**Comment by Gama11** [comment]
Can you provide a reproducible example? Otherwise, there's not much we can do here.
