### ISSUE TITLE
problem matcher doesn't recognize cwd argument

### ISSUE THREAD

**Issue by JeriXNet** [vshaxe/vshaxe#129]
I have this simple setup:
```
- app/
    - src/
        - Main.hx
    - build.hxml
```
`build.hxml`:
```
-cp src
-main Main
-js main.js
```
`settings.json`:
```
{
    "haxe.displayConfigurations": [
        ["--cwd", "app", "build.hxml"]
    ]
}
```
and this `tasks.json`:
```
{
    "version": "2.0.0",
    "command": "haxe",
    "problemMatcher": "$haxe",
    "args": ["--cwd", "app", "build.hxml"]
}
```
If I have compile errors problems do appear after saving file and click in problem panel lead to error position in file - all ok
But after I run build task click in problems panel result in error notification about file not found like this:
![monosnap-2017-06-07-17-46-42](https://user-images.githubusercontent.com/7815518/26884807-6119f9d0-4ba9-11e7-96a8-7cc0dc2fe541.png)

**Comment by Gama11** [comment]
Try defining your problem matcher like this:

```json
"problemMatcher": {
	"pattern": "$haxe",
	"fileLocation": ["relative", "${workspaceRoot}/app"]
}
```

Problem matchers don't know about `--cwd`.

**Comment by JeriXNet** [comment]
Yay, now it's working ok, thanks!
