### ISSUE TITLE
Class<haxe.macro.Context> has no field getLocalClass

### ISSUE THREAD

**Issue by hapass** [vshaxe/vshaxe#130]
Using static getLocalClass method on macro Context is highlighted as an error in my code.

<img width="883" alt="screen shot 2017-06-13 at 3 00 23 pm" src="https://user-images.githubusercontent.com/23015779/27081491-53587232-5049-11e7-9dc0-95df3ce77fdc.png">

settings.json looks like this:
{
    "haxe.displayConfigurations": [
        ["build.hxml"]
    ]
}

build.hxml looks like this:

-cp src/main/haxe
-cp src/test/haxe

-D analyzer-optimize

-net-lib lib/thirdparty.dll
-net-std lib/netcore

-D net-ver=45
-D no-compilation

-main Main

--macro addGlobalMetadata('thirdparty', '@:build(codestyle.adapters.Facade.buildExternalType())')
--gen-hx-classes

-cs bin

**Comment by Gama11** [comment]
See https://github.com/HaxeFoundation/haxe/issues/6000.
