### ISSUE TITLE
Single expression if invalid indentation

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#133]
If you have the following code:

```haxe
class Test {
	static function main() {
		if( something )
			bla();		
	}
}
```

The identation is broken in numerous ways:

- after typing `if( something )` it doesn't ident
- after typing `bla();` it doesn't ident back

**Comment by nadako** [comment]
not sure if that's easy to fix. right now vshaxe can indent/unindent on braces, but complex language-specific constructs - probably not easy at all..

**Comment by nadako** [comment]
maybe someday with hxparser and incremental parsing...

**Comment by ncannasse** [comment]
how does C/C++/Java handles it ?

**Comment by nadako** [comment]
i don't think it does.

**Comment by ncannasse** [comment]
I'm willing to help fixing this, it's like unusable for me in the current state

**Comment by nadako** [comment]
gotta do some research if other extension authors came up with some solution...

**Comment by ncannasse** [comment]
please write your findings here

**Comment by nadako** [comment]
Maybe it's somehow possible to do with "(un)indent patterns" that are configured with LanguageConfiguration that we set here https://github.com/vshaxe/vshaxe/blob/master/src/vshaxe/Main.hx#L19.

See http://vshaxe.github.io/vscode-extern/vscode/IndentationRule.html

**Comment by nadako** [comment]
I tried using TypeScript indentation rules from here https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L290, but looks like there's a bug or something in VSCode, because it doesn't work even for TypeScript right now...

**Comment by Gama11** [comment]
With latest VSCode Insiders, auto-indent works with `"editor.autoIndent": true"` for TS:

![](http://i.imgur.com/ToUawwn.gif)

Source: https://github.com/Microsoft/vscode/issues/4039#issuecomment-309484522

**Comment by nadako** [comment]
that's nice, so we should prepare by configuring the rule regexes (can steal and modify ts rules)

**Comment by Gama11** [comment]
I've pushed support for this to an `indentationRules` branch for now, for two reasons:

- It appears it already works in the current release, except support for it wasn't added to TS [until recently](https://github.com/Microsoft/vscode/commit/19ae0932c45b1096443a8c1335cf1e02eb99e16d). This makes me think that support for it wasn't solid enough until now, and we should maybe do a VSCode version check before defining these.
- It doesn't seem all that solid even on Insider's atm: Microsoft/vscode#29390

**Comment by ncannasse** [comment]
Any update on this ? It's still an issue.

**Comment by nadako** [comment]
I think it's still an issue in VS Code, so...

**Comment by ncannasse** [comment]
Well, there's only an issue with Allman indentation, can't we have an option to enable this if we don't use this particular style?

**Comment by nadako** [comment]
Not sure, IIRC it was a "language configuration" thing, not an option, but I'll have to look into all this again.

**Comment by Gama11** [comment]
I don't like the idea of having a setting just to work around a VSCode bug. :( Then again, I was hoping for this to be fixed much more quickly, as it seems like something that should be high-priority...

**Comment by ncannasse** [comment]
I agree in general, but that's a pragmatic approach since the issue has been opened for several months now. it's still possible to remove the setting once VSCode fixes it.
