### ISSUE TITLE
Macros exceptions not showing in problems

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#138]
If you have a uncaught throw (or a trace) in macro, these are not showing in Problems, while they are correctly showing in the terminal.

**Comment by Gama11** [comment]
Do those macro errors have a position? If they don't, they probably don't match the problem pattern:

https://github.com/vshaxe/vshaxe/blob/master/package.json#L291

Also, do traces belong in the problems view? As info I guess? Does FD do that?

**Comment by ncannasse** [comment]
They do have an error position, simply try with:

````
macro static function foo() {
   throw "assert";
   return null;
}
```

And yes trace belong here, FD does that, it's quite nice to debug macros this way, especially if you can report them no as errors in VSCode

**Comment by Gama11** [comment]
Haha, it's because of a missing space before `:`. :D

```
source/Main.hx:7: characters 3-8: Uncaught exception assert
```
vs
```
source/Main.hx:7: characters 3-8 : Uncaught exception assert
```

I think this is actually a Haxe/Eval issue (in 3.4.2, the formatting was consistent). Of course we could make the regex more permissive, but other editors might have the same issue, so it should be fixed on the Haxe side.

**Comment by EricBishton** [comment]
Yeah.  IDEA expects the space there.

**Comment by ncannasse** [comment]
Thanks for looking into it

**Comment by Gama11** [comment]
Created a separate issue for the trace enhancement: #139
