### ISSUE TITLE
Space identation

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#140]
When writing an object declaration, completing with `<tab>` removes the space before the semicolon, has shows the following example:

![image](https://user-images.githubusercontent.com/1022912/27615418-0b4822da-5be3-11e7-90c9-95acee9e2a7e.png)

![image](https://user-images.githubusercontent.com/1022912/27615438-2fa53b0e-5be3-11e7-823b-19b54f67744f.png)

**Comment by Gama11** [comment]
That's actually another case where we trigger type hint completion but probably shouldn't.. similar to #112. That might also be what causes the spacing issue.

**Comment by nadako** [comment]
I also wanted to report that, very annoying!

**Comment by Gama11** [comment]
I wonder if this is the same as https://github.com/Microsoft/vscode/issues/29353.

**Comment by Gama11** [comment]
Just checked - this is indeed fixed with latest VSCode. Completion is simply canceled when you type the space:

![](http://i.imgur.com/FBWHhn0.gif)
