### ISSUE TITLE
Inconsistent hover presentation of function types

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#144]
Here, the `Void->Void` is replaced by `function():Void` as per @nadako's `TypeHelper` logic:

![](http://i.imgur.com/gGaQpmD.png)

However, in this case, it's left as-is:

![](http://i.imgur.com/Bc50VKx.png)

**Comment by nadako** [comment]
hmm, i think the desired behaviour would be to show `function():Void` for methods and `Void->Void` for vars, not sure if we have enough info from haxe to make the decision tho.

**Comment by Gama11** [comment]
Related: https://github.com/HaxeFoundation/haxe/issues/3287

**Comment by Gama11** [comment]
The presentation for this is now consistent with the new protocol:

![](https://i.imgur.com/4roLWR1.png)

![](https://i.imgur.com/NCrFx17.png)
