### ISSUE TITLE
Haxe Dependencies not showing icons

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#146]
This is a minor thing (not urgent) but the Haxe dependencies are not showing any icons even if they are enable in the workspace.

**Comment by Gama11** [comment]
This is on my todo-list, but depends on improvements to the VSCode API: https://github.com/Microsoft/vscode/issues/27823 ("Extract icons from the resource Uri")

**Comment by ncannasse** [comment]
@Gama11 the VSCode issue has been closed :)
