### ISSUE TITLE
Completion not showing in heaps/hxd/Stage.js.hx

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#147]
When having a vshaxe project with -lib heaps, completion is not showing for platform specific file hxd/Stage.js.hx, this might either be vshaxe or Haxe related.

**Comment by Gama11** [comment]
Check the Haxe output channel for more info: https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

**Comment by ncannasse** [comment]
`Message: Error: Display file was not found in class path`

**Comment by Gama11** [comment]
I think this is a Haxe issue: https://github.com/HaxeFoundation/haxe/issues/6435
