### ISSUE TITLE
Show keywords in completion

### ISSUE THREAD

**Issue by starry-abyss** [vshaxe/vshaxe#148]
Like this:

![vscode1](https://user-images.githubusercontent.com/11571820/27862231-f135f426-618c-11e7-8334-e76976a92b5c.gif)

**Comment by Gama11** [comment]
It would help to show `else` / keywords in general in completion. In that case, `else` would be the first match.

The problem with that is that we probably don't want to show all keywords in all positions, to avoid them getting in the way / being suggested in positions where they're not applicable. On the other hand, for TypeScript, VSCode seems to do just that (always showing all keywords). Other IDEs are a bit smarter (e.g. IntelliJ only shows `else` after an `if` in Java).

**Comment by Gama11** [comment]
Of course, the other thing here is that it's a bit of a stretch that there are matches here in the first place. That would be an issue with VSCode's fuzzy matching though.

**Comment by Gama11** [comment]
There's actually even a third issue here, which is that these `__ASSET__` classes generated by Lime have a `#if display private #end` in front of them, yet are still shown in toplevel completion. I created a Haxe issue for this: https://github.com/HaxeFoundation/haxe/issues/6434
