### ISSUE TITLE
Generate imports

### ISSUE THREAD

**Issue by nadako** [vshaxe/vshaxe#15]
This is a related, but different feature than discussed in #2. It should be much easier to actually implement.

[haxe-sublime-bundle](https://github.com/clemos/haxe-sublime-bundle) has a neat feature that allows you to type a fully qualified type path, then press a key combo and have an import statement generated at the top of the file:
![](https://github.com/r3a1ay/helper/raw/master/img/haxe/auto_import.gif)
It does simple text processing trying to guess what to actually import, it supports simple module and type imports and can have a number of false positives, but it's still very useful.

It would be cool to have the same in vshaxe, but to get it right, I'm afraid we need some compiler support. In Haxe we might want to:
 * import a while module 
 * import a type from a module
 * import a static from a class
 * import everything from a package or all statics from a class (though these use cases are more rare)

To determine what options do we have and what to actually import (e.g. "is this a main module type? a type within a module? a static field of a class?") we need a display query that tries to resolve a given dot-path and gives us info about it.

**Comment by nadako** [comment]
actually, this is a feature for the haxe language server, not vshaxe itself, since it's just a "code action" from the editor standpoint

**Comment by Geokureli** [comment]
[vshaxe/haxe-languageserver](https://github.com/vshaxe/haxe-languageserver) does not seem to have an issues page, I came here to request this feature only to find there's no good way to bring it up.

**Comment by Gama11** [comment]
I think we already have an issue for this here: https://github.com/vshaxe/vshaxe/issues/97

Having two issue pages that are so closely related to each other turned out to be a bit messy, so we closed the one for haxe-languageserver and exclusively use vshaxe's now.
