### ISSUE TITLE
How to add haxelib library?

### ISSUE THREAD

**Issue by tsutsarin** [vshaxe/vshaxe#154]
I install some library, for example:
`haxelib git install hxPako https://github.com/azrafe7/hxPako`

But when typing `import` nothing shows up.
There are no entries for dependencies in vscode, except `std`.

There's no completion for installed libraries.
Help vshaxe to find haxelib!

**Comment by Gama11** [comment]
You need a display configuration, see:

- https://github.com/vshaxe/vshaxe/wiki/Configuration
- https://github.com/vshaxe/vshaxe/wiki/Framework-Notes

**Comment by tsutsarin** [comment]
@Gama11, I'm new both to Haxe and VS Code.
In second link there are only popular frameworks mentioned.

How can I add arbitrary library?

**Comment by Gama11** [comment]
If you're using pure Haxe (no frameworks that come with their own build system), you'll want to create a `.hxml` file for building:

https://haxe.org/manual/compiler-usage-hxml.html

The easiest way to set things up is by using the "Initialize Project" command:

https://github.com/vshaxe/vshaxe/wiki/Commands#haxe-initialize-vs-code-project

It comes with a `build.hxml` to which you can add `-lib hxPako`.

**Comment by tsutsarin** [comment]
Thanks, adding `-lib hxPako` helped!
