### ISSUE TITLE
Minor issue, `Cannot read property 'map' of undefined`

### ISSUE THREAD

**Issue by jgranick** [vshaxe/vshaxe#158]
Just ran into this during development:

```
TypeError: Cannot read property 'map' of undefined
    at c:\Users\Joshua\.vscode\extensions\vshaxe\bin\client.js:795:34
    at Object.m [as _notify]
...
```

It occurs from this compiled code:

```js
	Vscode.workspace.findFiles("*.hxml").then(function(files) {
		return _gthis.hxmlFiles = files.map(function(uri) {
			return uri.fsPath;
		});
	});
```

I assume `files` might come through `undefined` if no files are found

**Comment by Gama11** [comment]
This should already be fixed, looks like your vshaxe wasn't quite up to date: https://github.com/vshaxe/vshaxe/commit/b96c3bae351ee4da9929b2d87dcfa6a2b732d259#diff-a28933f225b2a16b02f81140071780c5R19
