### ISSUE TITLE
Restart Language Server create a new output windows instead to restart

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#159]
Restarting the language server looks like create a new one instead of restart the already exists one.
## Way to reproduce
1. Open the Command Platte 
2. "\> Haxe: Restart Language Server"

![image](https://user-images.githubusercontent.com/11459632/28242078-acc20188-69aa-11e7-88e8-525a939a4789.png)

**Comment by Gama11** [comment]
This is already fixed for the next release, see #87.

**Comment by mikicho** [comment]
Ah, didn't catch the existing issue sorry! Thanks for the quick feedback :)
