### ISSUE TITLE
Haxe process was killed

### ISSUE THREAD

**Issue by Ashedragon** [vshaxe/vshaxe#16]
On a fresh installation of vscode with the vshaxe extension on multiple different computers, I keep getting the message "Restarting Haxe completion server: Haxe process was killed"

I'm using Windows 10 64 and 32-bit versions, though previously I had the same issue on my Windows 7 64-bit desktop. Any assistance would be greatly appreciated.
(I'm also using 0.1.3 of vshaxe)

**Comment by Ashedragon** [comment]
Didn't realize I didn't have the latest development version of Haxe.

**Comment by nadako** [comment]
Hmm, it should complain about unsupported version once and stop, not keep restarting it... I'll check it out.

**Comment by Hectate** [comment]
Just want to note I'm experiencing this as well (Windows 8.1 x64, vscode 1.5.3, vshaxe 0.1.5).

**Comment by Aelbannan** [comment]
Me too (Windows 10, vshaxe 0.1.5, newest vscode and Haxe)

**Comment by Hectate** [comment]
Update; I upgraded to Haxe 3.3.0 and the issue seems to have disappeared as expected.
