### ISSUE TITLE
Dependency Explorer: do not list local libraries

### ISSUE THREAD

**Issue by aliokan** [vshaxe/vshaxe#162]
When I install locally my libraries. 
```bash
haxelib newrepo
haxelib install all --always
```
I don't see them in Dependency Explorer. 

* Mac OS 10.12.5
* VS Code Version 1.14.1 (1.14.1)
* vshaxe 1.9.0
* Haxe Compiler 3.4.2 (git build development @ ada466c)

**Comment by Gama11** [comment]
Ah, I don't think I've tested this case. We're probably running `haxelib path` in the wrong working directory.
