### ISSUE TITLE
Errors are not shown in the workspace problems

### ISSUE THREAD

**Issue by gerardsmit** [vshaxe/vshaxe#167]
In the target Lua, when you return a class with the annotation `@:multiReturn` an error is shown in the terminal:

```
> Executing task: C:\haxe_dev\haxe.exe user.hxml <

Error: You cannot return a multireturn type from a haxe function
```

However, this is not shown in the workspace problems:

![Problems](http://i.imgur.com/hfBv3Ef.png)

So when you don't have the terminal open, you expect the build to be succeeded; which is not the case.

---

Example:
```haxe
@:multiReturn
extern class Signal {
    var name: String;
}

class SignalTools {
    public static function getSignal(): Signal {
        // Cast the signal and return it, which causes the error.
    }
}
```

**Comment by nadako** [comment]
I think this is something @jdonaldson has to fix in Haxe itself. This should be a proper compiler error with the correct position, so vshaxe's problem matcher can detect it.

**Comment by gerardsmit** [comment]
Should I create an issue on the Haxe Git repo?

**Comment by nadako** [comment]
I'm kind of hoping that Justin will notice this since I tagged him, but yes, to make it sure, create an issue in the haxe repo.
