### ISSUE TITLE
"Change to ___" doesn't seem to behave as expected.

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#168]
Recorded a gif that reproduces the issue below:

![auto-correct](https://user-images.githubusercontent.com/164094/29748910-d399b868-8b20-11e7-9572-ddc728077d24.gif)

Using Haxe 3.4.2 and latest public VSCode and VSHaxe.

**Comment by Gama11** [comment]
Hm... are we doing anything differently?

![](http://i.imgur.com/xlAJvki.gif)

**Comment by jeremyfa** [comment]
Huh, that's strange.

The only difference I see is that I am manipulating the actual Luxe API, not a typedef on the same file. But why would that change anything?

**Comment by jeremyfa** [comment]
Let me try with the typedef.

**Comment by jeremyfa** [comment]
Same issue (tried on a non-luxe project with "regular" hxml file). I'm on MacOS, vshaxe 1.9.1. I really don't know what would be different.

**Comment by jeremyfa** [comment]
It would be interesting to see if somebody else on Mac has the same issue I guess?

**Comment by Gama11** [comment]
I doubt it's something OS-specific.. IIRC I had similar issues with other code actions in the past, but it never reproduced consistently for me.

**Comment by jeremyfa** [comment]
The only difference I would see on Mac, compare to windows, is line breaks in strings, but that's many assumptions already. I could check directly in the vshaxe code to see if I can spot something (could it be a vscode issue?) as I seem to reproduce it consistently.

**Comment by jeremyfa** [comment]
Investigated a bit, and the problem seem to occur here:

https://github.com/vshaxe/haxe-languageserver/blob/933c2a1b1b5f7dbab95e1c411f470d51200c8f79/src/haxeLanguageServer/features/DiagnosticsManager.hx#L263-L265

The range computed from haxe compiler output doesn't seem to match in my case. Checking a bit more to understand why the range is wrong.

**Comment by Gama11** [comment]
Weird file encoding / BOM or anything like that?

**Comment by jeremyfa** [comment]
No, but if I replace the line in haxeLanguageServer with this, it fixes the problem:

``
range.start.character = range.end.character - fieldRe.matched(1).length;
``

What I don't understand is why it works on your side.

**Comment by jeremyfa** [comment]
Oh, wait. Are you using tabs or space?

**Comment by jeremyfa** [comment]
Got it:

Before, it only worked with 2 tabs indentations because you were computing the range with the prepended tabs in the line, and removing 2 characters (in the code there is this hardcoded ``- 2``), which works by chance when you indent your code with tabs and are writing in a class function which is indented by 2 tabs.

That breaks as soon as you don't use 2 tabs, but spaces, or an anonymous function (that implies more tab indentations).

Using the line I suggested above should fix the issue (and still work in your case).

**Comment by Gama11** [comment]
Oh, yeah, I can repro now. That might also explain why I experienced this incosistently. For some projects I use tabs, for some spaces.

Do other code actions suffer from the same problem?

**Comment by jeremyfa** [comment]
Didn't try much of them, but will tell if I get anything unexpected. Anyway computing the range by setting it's start to "end of reported haxe expression minus lenght of identifier" seems to work consistently in all cases I have tested.

**Comment by Gama11** [comment]
Wanna do a PR for the fix?

**Comment by jeremyfa** [comment]
Will do!
