### ISSUE TITLE
suggest wiki amend, to framework notes

### ISSUE THREAD

**Issue by hypertrifle** [vshaxe/vshaxe#169]
Ive had an much improved performance when targeting web when generating the hxml file from flow,  so suggesting;

`haxelib run flow info web --hxml > completion.hxml` 

Might be more appropriate, or at least hi light you can chose a target platform.

**Comment by hypertrifle** [comment]
or even, link to: https://luxeengine.com/setup-an-ide/#vscode

**Comment by Gama11** [comment]
Thanks - I added a link to the Luxe docs and a note about specifying a target. :)
