### ISSUE TITLE
Show the Haxe dependencies view only if current workspace use haxe

### ISSUE THREAD

**Issue by MangelMaxime** [vshaxe/vshaxe#174]
In the next picture, my project only use F# and you can see the "Haxe dependencies" view being displayed. We should displayed it only on project using Haxe otherwise, the views panel will get messy with all the extensions.

<details>
<img src="https://user-images.githubusercontent.com/4760796/31048305-c3effa34-a61a-11e7-8ef9-292e5565dc26.png"/>
</details>

**Comment by Gama11** [comment]
This wasn't possible back when I added the Haxe Dependencies view, but it looks like it now might be with a `when` clause: https://github.com/Microsoft/vscode/issues/29436
