### ISSUE TITLE
Hxml colouring

### ISSUE THREAD

**Issue by elsassph** [vshaxe/vshaxe#177]
Hxml syntax seems too eager to colorise `-option` tokens, e.g.:
```
-cmd node bin/cmd.js .temp/output.js -webpack -debug -debugmap .temp/index.js foo_Bar
```
will colourise `-cmd` (ok), `-debug` (probably shouldn't) and the `-debug` characters within `-debugmap` (wrong).

**Comment by nadako** [comment]
probably shouldn't colorize anything after `-cmd` until newline.

**Comment by nadako** [comment]
In fact, it shouldn't colorize anything but first known argument until the end of line...

**Comment by nadako** [comment]
Oh wait, I guess haxe supports multiple args on a hxml line
