### ISSUE TITLE
Wrong highlighting?

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#178]
hey,
I have problem with highlighting(`pulse` and `body` are white)

![image](https://user-images.githubusercontent.com/11459632/31684586-f1db76aa-b388-11e7-8562-12a86871ab4e.png)

Full file code:
```haxe
package controllers;

class API {
    public function new() {}

    @:get
    public function test() {
        return "OK!";
    }

    @:post
    public function pulse(body:{MAC:String, timeSample:Date}) {
        var pulse = new Pulse();
        pulse.MAC = body.MAC; // THIS LINE HAS WRONG HIGHLIGHTING
        pulse.sampleTime = body.timeSample;
        
        return pulse.insert();
    }
}
```

**Comment by Gama11** [comment]
This looks like a type path to the tmLanguage file (lowercase package name, followed by a dot, followed by a capitalized word). VSCode currently doesn't allow semantic highlighting (https://github.com/Microsoft/vscode/issues/585), where the highlighter would know the available types to differentiate, so I don't think we can fix this.
