### ISSUE TITLE
Pluggable display argument providers

### ISSUE THREAD

**Issue by nadako** [vshaxe/vshaxe#18]
A lot of frameworks have their own project files and an option to generate display arguments from those files. It would probably be nice to support those as an alternative to `haxe.displayConfigurations`. To make it generic, I thought we could maybe support pluggable "display arguments provider" system", where `haxe.displayConfigurations` config is just one of them, but there's also others, like the one for openfl/lime that would be watching `project.xml` and re-read display arguments with `lime display <platform>`. I think we don't even need to touch language server for that.

While this isn't implemented, we should steal/adapt the "framework notes" table from vscode-haxe:
https://github.com/jcward/vscode-haxe#framework-notes

**Comment by Gama11** [comment]
Adding the "blocked" label here for now, see https://github.com/vshaxe/vshaxe/issues/96#issuecomment-283705056 and #79.

**Comment by nadako** [comment]
This is now implemented.
