### ISSUE TITLE
Compiler warnings count as error.

### ISSUE THREAD

**Issue by ibilon** [vshaxe/vshaxe#180]
Having a code with warning compiled as preTask
```haxe
class Main {
	public static function main() {
		test();
	}

	static macro function test () {
		haxe.macro.Context.warning("no launch", haxe.macro.Context.currentPos());
		return macro null;
	}
}
```
fails to launch.

The compiler correctly return an exit code of 0.

Can a problem matcher differentiate errors and warnings?

**Comment by nadako** [comment]
Hmm, it should...

**Comment by Gama11** [comment]
Hm, it's showing up as a warning in the Problems panel, so the problem matcher works correctly:

![](https://i.imgur.com/Sg0h6Zz.png)

**Comment by Gama11** [comment]
Dug a bit into VSCode sources, this seems to be a bug on their end: https://github.com/Microsoft/vscode/issues/46439
