### ISSUE TITLE
js-debug available?

### ISSUE THREAD

**Issue by r3d9u11** [vshaxe/vshaxe#181]
Hi. Is available [javascript debugging](https://github.com/vshaxe/vshaxe/wiki/JavaScript-Debugging) for haxe? And how to configure it?

Also it mentioned in features list of vshaxe:
```
Features

This is just a brief overview of the supported features. For more details, check out our extensive Documentation.

Syntax Highlighting
...
JavaScript Debugging
```

Thanks.

**Comment by Gama11** [comment]
It should work out of the box due to source maps that are generated with -debug. You can base your launch.json on this repo: https://github.com/Gama11/HaxeRepro

**Comment by r3d9u11** [comment]
@Gama11 thank you, your link is useful!
