### ISSUE TITLE
Installed it and getting - Code language not supported or defined message ! HELP

### ISSUE THREAD

**Issue by Gamezpedia** [vshaxe/vshaxe#182]
Hi, 
i don't know if i am doing it wrong but when i add cpp in compiler settings it stops compiling.
kindly guide me i am new to this .

Steps i took:
0 - Pressed F1 > Haxe: Intialize VS Code project.
1 - Compiler settings 
![image](https://user-images.githubusercontent.com/1169093/32187207-1867f8a6-bdc6-11e7-9fd0-7ea66ded4cd2.png)
2 - Message 
![image](https://user-images.githubusercontent.com/1169093/32187050-a31f6d7c-bdc5-11e7-911a-37628b57531a.png)
3 - Code and output
![image](https://user-images.githubusercontent.com/1169093/32187433-e497304a-bdc6-11e7-9ffe-40a2bb019c43.png)
![image](https://user-images.githubusercontent.com/1169093/32187459-f703b8a2-bdc6-11e7-9b74-16acc6ef32d1.png)

thanks

**Comment by wiggin77** [comment]
I don't think you can target cpp and interp at the same time.   Remove `--interp`

**Comment by Gamezpedia** [comment]
> i tried that too
![image](https://user-images.githubusercontent.com/1169093/32246701-a266f6de-bea1-11e7-9060-feb05b0028e8.png)

>and if you write in terminal it is attempting to compile but with errors like Library is not installed and showing the files in the bin folder : i am confused .

![image](https://user-images.githubusercontent.com/1169093/32246812-13538e52-bea2-11e7-96f0-14e6b1777586.png)

**Comment by Gama11** [comment]
You need to install hxcpp for C++ compilation.

```
haxelib install hxcpp
```

**Comment by Gamezpedia** [comment]
Thank you @Gama11 and @wiggin77 i get the point i thought the libraries were installed with the kit itself.
it's compiling perfectly 👍
