### ISSUE TITLE
Diagnostics for all HXML

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#183]
It seems that diagnostics are displayed for all HXML in workspace and not only for the selected/current one. I could confirm this by closing and reopening VSCode.

In my case it was two HXML with different class paths, the Main class of the not selected HXML referencing a `final` package name.

**Comment by Gama11** [comment]
Are you sure that you didn't just have a file from that other classpath open? Vshaxe attempts display requests even without any display configuration / if the file is not in the classpath, which works fine if a file has no dependencies outside of std.

**Comment by ncannasse** [comment]
That's a high possibility, I'll close and repost in case it happens again with a specific scenario.
