### ISSUE TITLE
Dependencies explorer is infuriating

### ISSUE THREAD

**Issue by karai17** [vshaxe/vshaxe#189]
The dependencies explorer pops up every time I open code, even if I've closed it before. It takes up all the empty space so I need to constantly close or resize the damn thing. It also shows up in non-haxe projects. How the bloody hell can I made this thing GO AWAY. Thanks.

**Comment by nadako** [comment]
Yeah it's annoying. Tho I thought it's not really dep.explorer's fault. Since latest vscode release I have all explorer additions always expanded :-/

**Comment by karai17** [comment]
I'm only having issues with the haxe one.

**Comment by nadako** [comment]
@Gama11 could you look into this?

**Comment by nadako** [comment]
> I'm only having issues with the haxe one.

I'm also having same issues with Code Outline and Git Lens plugins, so maybe it's something about state saving API change that plugins have to adapt to or I don't know...

**Comment by Gama11** [comment]
I can't seem to reproduce this at all (VSCode 1.17.2, right?).

**Comment by karai17** [comment]
I am using latest vscode on Linux, yes.


---
Landon Manning
lmanning17@gmail.com

**Comment by Gama11** [comment]
Is this still an issue?
