### ISSUE TITLE
Type not found on imported haxe-libs

### ISSUE THREAD

**Issue by Ulfasaar** [vshaxe/vshaxe#190]
Hi guys,

I have recently installed the hxnodejs haxelib and included it in a .hxml file for a project I am working on.

However for some reason the extension seems to think that the types for this library are undefined, even though it compiles perfectly fine.

Here's the code for the hxml file

`-dce full
-lib hxnodejs
-D js_es=6
-main ClientSocket
-js clientSocket.js`

and a screenshot of the error in vs-code.

![2017-11-06 10_20_02-clientsocket hx - server - visual studio code](https://user-images.githubusercontent.com/10955652/32419262-1bf28e44-c2dc-11e7-9987-19d2d23628ba.png)

The link to my repo can be found here too [](https://github.com/SKOMOBO/server)
I apologize for how messy it is, I am currently in the process of cleaning it up :)

Is there some sort of setting I am supposed to alter? Like a setting for the location of my haxe libs folder?

**Comment by Gama11** [comment]
Does the "Haxe Dependencies" view in the lower left show the lib?

**Comment by Ulfasaar** [comment]
No, it only shows std

**Comment by Ulfasaar** [comment]
Ok I have reopened the folder with the haxe code so that it is the root folder of the workspace and now the extension seems to be doing something :)

![2017-11-06 10_24_54-clientsocket hx - dust_cleaner - visual studio code](https://user-images.githubusercontent.com/10955652/32419316-e7ab5c82-c2dc-11e7-9bf5-a575e588e6e7.png)

**Comment by Gama11** [comment]
Yes, vshaxe only auto-detects hxml files in the root directory. If you want to use one in a subdirectory for completion, use the haxe.displayConfigurations setting. https://github.com/vshaxe/vshaxe/wiki/Configuration

**Comment by Ulfasaar** [comment]
Sweet thank you very much Gama11.

It's definitely working now that I have restarted it as well :) 
![2017-11-06 10_30_40-clientsocket hx - dust_cleaner - visual studio code](https://user-images.githubusercontent.com/10955652/32419374-cc3bb6d0-c2dd-11e7-9f14-3fb1f1a3fe35.png)

**Comment by Ulfasaar** [comment]
Ok this is weird. So I closed and reopened my editor and now the error message is back again. 

![2017-11-06 11_17_08-clientsocket hx - dust_cleaner - visual studio code](https://user-images.githubusercontent.com/10955652/32419776-9eb39bf4-c2e4-11e7-9b45-af422ed98b22.png)

I can still navigate to the definition however and peek at it.

![2017-11-06 11_21_47-clientsocket hx - dust_cleaner - visual studio code](https://user-images.githubusercontent.com/10955652/32419784-b57e7b42-c2e4-11e7-9cd7-31e9f6c8ec98.png)

Also it doesn't seem to see the references I made to the module directly below it either

![2017-11-06 11_20_23-clientsocket hx - dust_cleaner - visual studio code](https://user-images.githubusercontent.com/10955652/32419790-cd885258-c2e4-11e7-8e58-b53aae11f02e.png)

**Comment by Ulfasaar** [comment]
Ok this is even weirder, my intellisense vanished, I tried restarting vscode several times and the language server and then finally my laptop. I then managed to bring it back by specifying a port for the completion server using the display port setting and connected to it which then fixed the intellisense, however the incorrect type not found error is still persisting

**Comment by Ulfasaar** [comment]
Ok now it seems fine again, very very weird probably just a stability glitch on my end so I will just close the issue :)
