### ISSUE TITLE
Goto Definition not working with dot

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#192]
With the following example:

```haxe
class Test {
    var foo : Int;
    function new() {
         foo.
    }
}
```

Using Goto Definition on foo (F12) will make an error. Removing the dot works however.

**Comment by Gama11** [comment]
This is a Haxe issue, same results when calling `haxe --display` manually. Similar to https://github.com/HaxeFoundation/haxe/issues/5951.
