### ISSUE TITLE
Keywords auto completion

### ISSUE THREAD

**Issue by Fl0xer** [vshaxe/vshaxe#195]
When I start typing keywords such as "switch" or "return", I have no auto completion. 
It seems to be the case for keywords inside functions because when I type "public", "override" or "function", I have autocompletion.

**Comment by Gama11** [comment]
Duplicate of #148.

Vshaxe doesn't have any keyword completion at all at the moment. You probably mean this sort of thing:

![](https://i.imgur.com/P5RyvtJ.png)

This is some basic word-based completion provided by VSCode itself, in places where vshaxe doesn't provide any completion.
