### ISSUE TITLE
'Go to Definiton' doesn't work inside angular brackets(XML, jsx-like syntax)

### ISSUE THREAD

**Issue by djaonourside** [vshaxe/vshaxe#196]
![123](https://user-images.githubusercontent.com/12369638/33215957-da6e59a6-d142-11e7-97be-4b645bdfb0b6.png)

At the present time there's no support of any haxe-react library and jsx syntax in any kind in vshaxe.

**Comment by djaonourside** [comment]
Could anyone comment this issue? Any hope on the resolving? Or may be a direction this issue could be solved?

**Comment by Gama11** [comment]
There's currently no plans of adding JSX support directly to vshaxe. Perhaps another extension might be able to.

Btw, that code snippet isn't valid Haxe code?

**Comment by djaonourside** [comment]
I suppose that it's possible to make it valid via macro. Am I wrong?

**Comment by Gama11** [comment]
Macros can't create new syntax. The code still has to make it through the parser first, which this snippet wouldn't.

**Comment by djaonourside** [comment]
It's clear. Thank you. I think haxe needs unsafe blocks or something that but it's off-topic.

**Comment by Gama11** [comment]
Originally I thought you were asking for vshaxe to support one of the existing Haxe JSX libs like https://github.com/massiveinteractive/haxe-react. I guess that's not the case. :)

>I think haxe needs unsafe blocks or something

There have been serveral haxe-evolution proposals on this topic. [Inline XML](https://github.com/HaxeFoundation/haxe-evolution/pull/12) has been turned down, currently there's one open for [Inline Markup Literals](https://github.com/HaxeFoundation/haxe-evolution/pull/26).

Either way, doesn't seem like there's anything for vshaxe to do here.
