### ISSUE TITLE
Moving tooltips

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#197]
When displaying completion arguments, the tooltip moves as you type which I think is a very unique behavior in IDE world (ie disturbing). I'm not sure if it's vshaxe behavior or vscode default but there should be a way to have fixed tooltips instead.

**Comment by ncannasse** [comment]
More remarks for the tooltip:

- positioning : having the tooltip under the cursor is much better than over since you usually want to read you code / variables before and not after. 

- documentation : documentation should be take like 1s without typing to show, or be displayed by pressing a special key, because big documentation takes way more space and prevent from correctly reading the arguments.

**Comment by Gama11** [comment]
vshaxe doesn't / can't do anything here. A related VSCode issue: https://github.com/Microsoft/vscode/issues/33752

**Comment by ncannasse** [comment]
Could we get an option in vshaxe to disable documentation ? this would allow to trim down significantly the tooltip size.

**Comment by Gama11** [comment]
I guess that would be possible, yeah. Although it's something that would ideally be a global VSCode setting, not specific to a particular language.

**Comment by Gama11** [comment]
To clarify, which tooltips did you mean exactly here? Because the ones from field completion already have a button to expand / collapse documentation, including a shortcut:

![](https://i.imgur.com/gqTpwfs.gif)

**Comment by ncannasse** [comment]
It was the arguments tooltip after opening `obj.call(`

**Comment by Gama11** [comment]
Starting with the next release, you can disable documentation in those popups with:

```json
"haxe.enableSignatureHelpDocumentation": false
```

___________

With docs enabled:

![](https://i.imgur.com/9rMZd0c.png)

With docs disabled:

![](https://i.imgur.com/hKyivbW.png)
