### ISSUE TITLE
Autocompletion is very slow

### ISSUE THREAD

**Issue by serjek** [vshaxe/vshaxe#199]
Hey, so autocomplete takes 5-6 seconds to show the result. --times option indicates that operation took 0.8 sec (78% macro) so I wonder why there is such a big difference? I can tolerate 0.8 sec, but 5-6 seconds is just too much. 

Per wiki this can be related to specific macro or macro over-usage. Project is quite big (about 4k classes and hundreds of macros), so could this be a reason of this delay? Shouldn't completion cache deal with it? Anything I'm missing?

**Comment by Gama11** [comment]
The time shown with `--times` is the time the compiler took to return the results, vshaxe still has to process them and pass them on to VSCode. Normally that's negligible though.

Any way to reproduce this with publicly available code?

**Comment by Gama11** [comment]
Something that just occurred to me while debugging some performance issues with @jgranick: the Haxe server triggers a memory reduction every 10th request, which on large projects with a lot of memory usage can take quite a while. This would explain the discrepancy you're seeing, and means `--times` is actually correct, it's just that the request itself is delayed.

If you enable verbose mode, you can see messages like this in the Haxe output channel every now and then (this is an extreme case):

```
Compacted memory 13.230s 1541.2MB
```

This might be something to add to the Wiki.

**Comment by ncannasse** [comment]
I have fixed things so that GC compact is only run after we cache modules (= successful compilation) otherwise there's no need to compact https://github.com/HaxeFoundation/haxe/commit/c439f3a01f4660a9a09c2e6533ea790b8386170a

**Comment by Gama11** [comment]
I've added some info to the troubleshooting page:

https://github.com/vshaxe/vshaxe/wiki/Troubleshooting#completion-is-slow

Without further info, I'll assume @serjek's issue was indeed caused by GC.

**Comment by serjek** [comment]
Awesome thanks! Unfortunately all my code is enterprise so I don't really know how to reproduce this on public code but I will certainly check it on problematic project when I have a chance.
