### ISSUE TITLE
Build task freezes when used with haxeshim

### ISSUE THREAD

**Issue by gene-pavlovsky** [vshaxe/vshaxe#201]
I'm using haxeshim. It installs `haxe`, `haxe.exe`, `haxe.cmd` in npm's command directory (which is first directory in my PATH containing `haxe`).

When I run the build task, it freezes. I can see the `haxe` process in the process list. Nothing seems to be happening until I manually terminate the task. The `haxe` file itself is a shell script.

I actually do have Cygwin installed (on Windows 7), and if I run `haxe build.hxml` from Cygwin bash shell, it does work. But I think maybe `vshaxe` (or `VS Code`) doesn't know how to run this script correctly, but still tries to run it somehow (in a wrong way).

A workaround that helps is this setting:
```json
"haxe.executable": {
    "path": "haxe",
    "windows": {
        "path": "haxe.cmd"
    }
}
```

One question I have is what is the point of `haxe` being the default `haxe.executable` on Windows, and not `haxe.exe`?

**Comment by Gama11** [comment]
Seems to work fine for me:

![](https://i.imgur.com/HqMvH48.png)

**Comment by back2dos** [comment]
I can confirm both that this was an issue and that I can't reproduce it anymore ^^

**Comment by Gama11** [comment]
Nice! :)
