### ISSUE TITLE
Using library "signal" breaks completion

### ISSUE THREAD

**Issue by maaniv** [vshaxe/vshaxe#203]
When i use "signal" library (<haxelib name="signal" />) completion no works. Without library all is ok.

**Comment by Gama11** [comment]
Works for me - please provide more details.

![](https://i.imgur.com/46tRMmo.png)

**Comment by maaniv** [comment]
To reproduce:
openfl create project Test
Enter to Test folder and add library signal to project.xml.
After that completion don't work.
My OS is linux.

**Comment by Gama11** [comment]
What does your project setup look like? Are you using the Lime extension? If not, try doing so. :)

https://marketplace.visualstudio.com/items?itemName=openfl.lime-vscode-extension

Also have a look at the output panel, there's probably some errors there.

https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

**Comment by maaniv** [comment]
I use openfl.lime-vscode-extension
VSCode Haxe output panel^
Haxe language server started
Error: Display file was not found in class path
Restarting Haxe completion server: display arguments changed
Initializing completion cache...
Failed - try fixing the error(s) and restarting the language server:

Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /
Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /
[Warn  - 7:01:12 PM] Request textDocument/completion failed.
  Message: Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /
  Code: -32603 
Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /

**Comment by Gama11** [comment]
Huh.. That `invalid character: /` error doesn't really make sense to me.. I'm assuming this happens when you add other libraries as well, not just `signal`?

**Comment by maaniv** [comment]
No. That's happened only with signal library.

**Comment by maaniv** [comment]
With your lines in settings json, output now:
Haxe language server started
Processing Arguments [--cwd,/mnt/data-1/tmp/Test,-D,display-details,--no-output,--display,/mnt/data-1/tmp/Test/Source/Main.hx@0@diagnostics]
> Error: Display file was not found in class path
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Error: Display file was not found in class path
Restarting Haxe completion server: display arguments changed
Initializing completion cache...
Processing Arguments [-main,ApplicationMain,--macro,openfl._internal.utils.ExtraParams.include(),-cp,/mnt/data-1/dev/haxelibs/openfl/7,1,2/src,-D,openfl=7.1.2,--macro,lime.Lib.extraParams(),-cp,/mnt/data-1/dev/haxelibs/lime/6,2,0,-D,lime=6.2.0,-D,signal_stoppable,-cp,-cp,/mnt/data-1/dev/haxelibs/signal/1,0,2/src,-D,signal=1.0.2,-cp,Source,-cp,/mnt/data-1/dev/haxelibs/openfl/7,1,2/src/externs/core/openfl,-cp,/mnt/data-1/dev/haxelibs/openfl/7,1,2/src/externs/extras,-D,tools=6.2.0,-D,howlerjs,-D,no-compilation,-D,openfl-html5,-D,lime-html5,-D,html5,-D,web,--remap,flash:openfl,-js,Export/html5/bin/Test.js,-cp,Export/html5/haxe,-D,html5,-D,display,--no-output]
> Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Failed - try fixing the error(s) and restarting the language server:

Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /
Processing Arguments [--cwd,/mnt/data-1/tmp/Test,-main,ApplicationMain,--macro,openfl._internal.utils.ExtraParams.include(),-cp,/mnt/data-1/dev/haxelibs/openfl/7,1,2/src,-D,openfl=7.1.2,--macro,lime.Lib.extraParams(),-cp,/mnt/data-1/dev/haxelibs/lime/6,2,0,-D,lime=6.2.0,-D,signal_stoppable,-cp,-cp,/mnt/data-1/dev/haxelibs/signal/1,0,2/src,-D,signal=1.0.2,-cp,Source,-cp,/mnt/data-1/dev/haxelibs/openfl/7,1,2/src/externs/core/openfl,-cp,/mnt/data-1/dev/haxelibs/openfl/7,1,2/src/externs/extras,-D,tools=6.2.0,-D,howlerjs,-D,no-compilation,-D,openfl-html5,-D,lime-html5,-D,html5,-D,web,--remap,flash:openfl,-js,Export/html5/bin/Test.js,-cp,Export/html5/haxe,-D,html5,-D,display,-D,display-details,--no-output,--display,/mnt/data-1/tmp/Test/Source/Main.hx@0@diagnostics]
> Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Error: Could not process argument /mnt/data-1/dev/haxelibs/signal/1,0,2/src
invalid character: /

**Comment by maaniv** [comment]
Signal library has file
extraParams.hxml
if i delete them all working fine
File data:
-D signal_stoppable
# -D signal-strict

**Comment by Gama11** [comment]
The arguments contain this section:

```
...,-cp,-cp,/mnt/data-1/dev/haxelibs/signal/1,0,2/src,...
```

Somehow there's an empty classpath being passed to Haxe. What does your Project.xml look like exactly?

**Comment by Gama11** [comment]
Actually, I can reproduce this if I include the signal lib in an OpenFL project rather than a pure Haxe one. This is somehow OpenFL-specific.

**Comment by maaniv** [comment]
That's empty openfl project:
```
<?xml version="1.0" encoding="utf-8"?>
<project>

	<meta title="Test" package="com.sample.test" version="1.0.0" company="Company Name" />
	<app main="Main" path="Export" file="Test" />

	<source path="Source" />

	<haxelib name="openfl" />
	<haxelib name="signal" />

	<assets path="Assets" rename="assets" />

</project>
```
I add only line with signal library.

**Comment by Gama11** [comment]
This is a bug with Lime's command line tools: https://github.com/openfl/lime/issues/1169
