### ISSUE TITLE
Problem with autocompletion

### ISSUE THREAD

**Issue by camoltoni** [vshaxe/vshaxe#204]
Hi, I can't manage to make the plugin work, when I open a file I get this message in the console.

Haxe language server started
Initializing completion cache...
Restarting Haxe completion server: display arguments changed
Initializing completion cache...
Failed - try fixing the error(s) and restarting the language server:

Type not found : ApplicationMain
[Warn  - 17:17:25] Request textDocument/hover failed.
  Message: Error: Display file was not found in class path
  Code: -32603 
I'm running vscode 1.20 the latest version with haxe 3.4.4 on kubuntu 17.10
Thanks in advance

**Comment by Gama11** [comment]
Sounds like you're using OpenFL and haven't built the target you've selected for completion yet? `ApplicationMain` is generated on compilation by Lime.

**Comment by camoltoni** [comment]
I used a template from flixel I build the project with the tasks included. The ApplicationMain.hx is en export/flash/haxe but I can't manage to point the plugin to looking at this folder for ApplicationMain

**Comment by camoltoni** [comment]
I used a template from flixel I build the project with the tasks included. The ApplicationMain.hx is en export/flash/haxe but I can't manage to point the plugin to looking at this folder for ApplicationMain

**Comment by Gama11** [comment]
Have you seen this dropdown? https://github.com/vshaxe/vshaxe/wiki/Configuration#multiple-display-configurations

**Comment by camoltoni** [comment]
Hi, thanks for your help, I'm started a new project and now the plugin works perfect!
It will be a problem from my other project
Are you the owner of the flixel project also? How can I help you with that
