### ISSUE TITLE
Implement interface methods code action

### ISSUE THREAD

**Issue by T1mL3arn** [vshaxe/vshaxe#205]
It'll be useful feature to implement all methods from an interface by command in ctx menu (as HaxeDevlop does) 
1. write something like this:
```Haxe
class Foo implements IFoo {}
```
2. invoke ctx menu on `IFoo`
3. press `Implement interface methods` and get
```Haxe
class Foo implements IFoo {
  public function foo():Void { }
  public function bar():Void { }
}
```

**Comment by Gama11** [comment]
Agreed, but I don't think this is doable currently with the limited info we get from Haxe.

**Comment by Gama11** [comment]
That would require a having a Haxe parser in the language server etc, when instead we actually want the compiler to do the heavy lifting. This should work similarly to override completion, where the compiler sends us the information (the fields to add) [in a structured way](https://github.com/HaxeFoundation/haxe/blob/52862239942262c3f83fa8ff00703d7b99cdb6f0/std/haxe/display/JsonModuleTypes.hx#L251).

**Comment by Gama11** [comment]
This will be supported by vshaxe 2.22.0 in cominbation with latest nightly builds of Haxe 4.2:

![S2ukMw6exc](https://user-images.githubusercontent.com/2620907/87848790-7d16d080-c8e3-11ea-928f-6f9c41c6869b.gif)
