### ISSUE TITLE
janky code completion 

### ISSUE THREAD

**Issue by Geokureli** [vshaxe/vshaxe#207]
<img width="197" alt="screen shot 2018-02-18 at 1 35 15 am" src="https://user-images.githubusercontent.com/2609513/36349417-01782bd4-144c-11e8-82ba-a5242e0d74e5.png">
rather than showing methods of String, it's showing every method and property of every type (and every type) referenced by that file

Edit: also notice, it's alphabetical and charAt is missing

**Comment by Gama11** [comment]
You're not getting any vshaxe completion at all, actually. This is VSCode's builtin, word-based completion. Please check if you're getting any errors: https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

**Comment by Geokureli** [comment]
It's possible my issues are with the lime/openfl extension. I'm still looking into this, will update in a bit

**Comment by Geokureli** [comment]
I made a new project and disabled my lime extension for my workspace

rather than having my src and Project xml at the top of my workspace, it's nested 1 folder deep in the test folder. Also in the workspace is a lib folder which I marked as a dependency in my openfl project with `<classpath path="../lib/src" />` (which became -cp ../lib/src in the hxml)

<img width="218" alt="screen shot 2018-02-18 at 3 15 23 pm" src="https://user-images.githubusercontent.com/2609513/36358260-304573ec-14d1-11e8-9d41-44e2d6f9a6f5.png">

this works fine, the project builds and I can even debug and breakpoint in both directories through vsCode, but when I add `import com.geokureli.LibClassTest;` I lose code completion

**Comment by Gama11** [comment]
The Lime extension has a setting called `lime.projectFile` which you can use for cases such as the `Project.xml` not being in the root directory:

https://github.com/openfl/lime-vscode-extension/blob/master/package.json#L48

**Comment by Geokureli** [comment]
whether I use lime.project file with an xml, or haxe.displayConfigurations with an hxml. I get the same result: complete loss of code completion when I import from the other directory in the workspace

**Comment by Gama11** [comment]
Are you seeing any errors in the Haxe output panel?

**Comment by Geokureli** [comment]
no problems listed

**Comment by Geokureli** [comment]
Looks like I can get around it by setting my workspace to the test folder, moving my .vscode folder there and updating the paths. The lib folder shows in my haxe dependancies. This isn't a perfect solution however my goal was to have 1 workspace containing my 3 related but separate projects and the lib folder that they all reference, but it looks like now I'll need a separate workspace for each project, which is not the end of the world.

While I have your attention, in another project, code completion seems to be broken because of references to embedded/generated swf classes. How do I fix this? in HaxeDevelop this just works, in IntelliJ-idea I mark Export/flash/haxe/_generated as a dependency, but in VsCode I seem to have no direct control over dependancies

**Comment by Geokureli** [comment]
After reading some other issues, it looks like what I'm asking for is Multi root support #170
