### ISSUE TITLE
(Feature Request) Unused Variables!

### ISSUE THREAD

**Issue by Jazz914** [vshaxe/vshaxe#21]
It would be nice to see a green squiggly line under unused variables

**Comment by Gama11** [comment]
Agreed!

**Comment by Simn** [comment]
Good idea, but I guess this should come from the Haxe compiler itself in order to be as accurate as possible.

**Comment by Gama11** [comment]
Isn't this more or less what I suggested in https://github.com/HaxeFoundation/haxe/issues/4744? I guess that'd be a display mode instead of just printing to stdout?

**Comment by Simn** [comment]
It could be part of the diagnostics run. But what I said in that issue stands, we have to figure out which variables actually come from syntax because reporting them is pointless otherwise.

**Comment by Gama11** [comment]
Should that issue be reopened then?

**Comment by Simn** [comment]
I'm still not sure if this can be done properly, but I've reopened it.

**Comment by Simn** [comment]
Useless variables are reported now.
