### ISSUE TITLE
Feature Request: auto-complete for typedef

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#211]
If I have typedef: 
```haxe
typedef MyType = {
  var a:String;
  var b:Int;
}
```

I want that if compiler can infer this type, so auto-complete will be only the fields of this type:

```haxe
type:MyType;

this.type = { 
  // if I click ctrl+space here it will open the auto-competition with only (a,b) options
}
```
Currently, it just open global scope completion.

**Comment by Gama11** [comment]
We used to have that, but it was disabled due to https://github.com/HaxeFoundation/haxe/issues/6005.

**Comment by Gama11** [comment]
Closing this since we already have an open issue for it: #110
