### ISSUE TITLE
Haxe server should not use --wait stdio

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#217]
Communications on stdout/stdin are error prone for several reasons:
- a print left somewhere in the compiler will break the protocol
- a macro starting a command that prints things will break the protocol

I recommend moving to proper socket and drop the hack that makes haxe language server opens a proxy socket

**Comment by Gama11** [comment]
It still seems nice to have a proxy in case we need to restart the server (`haxe.executable` changed or similar).

**Comment by nadako** [comment]
Although I can agree on the second point (the first one is just a compiler bug), I won't change this unless there's a "non-hack" solution to address issues mentioned in https://github.com/HaxeFoundation/haxe/pull/5188.

**Comment by frabbit** [comment]
I also experience problems which i think are related to this, will try to figure that out when i have more time.

**Comment by nadako** [comment]
So I was taking a bath and suddenly it occured to me that we can do the same trick as in the `eval` debugger:
 - bind a free port and start listening on the IDE side
 - start haxe server passing the port to connect to as an argument
 - haxe connects to IDE and both proceed to do normal socket communication

**Comment by Gama11** [comment]
So finding a free port is the only blocker to using `--wait stdio`? Your earlier comment sounded like it was more than that ("issues mentioned in HaxeFoundation/haxe#5188").

**Comment by nadako** [comment]
this should address all issues: free ports (just bind to 0) and knowing when connection can be/is established (Haxe will connect to us itself and then we're ready to communicate)
