### ISSUE TITLE
.hxml: show argument docs on hover

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#22]
Seems like it'd be a really handy feature - should show the documentation text you get with `haxe --help` for that arg.

Potentially even docs for specific `-D` values based on `--help-defines`?

**Comment by Gama11** [comment]
I guess you could do some very advanced stuff here, like having completion + hover hints for `--macro` args.

**Comment by nadako** [comment]
That would work awesomely with https://github.com/HaxeFoundation/haxelib/issues/262

**Comment by nadako** [comment]
merged into #28
