### ISSUE TITLE
Haxelib errors are not reported by diagnostics

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#220]
This is the same issue as #214, but for diagnostics: errors such as missing haxelibs aren't reported by them, even though they stop completion from working.

Unfortunately this is blocked by https://github.com/Microsoft/language-server-protocol/issues/256 - a diagnostic must have a URI associated with it right now.

**Comment by ncannasse** [comment]
Can't you associate the -main class for now ?

**Comment by Gama11** [comment]
There might not even always be one. ;) And finding the file path just from the package + type name involves quite a bit of work too, so I'm not sure it's really worth it.

Ideally, Haxe or haxelib would point to the exact location in the hxml where the corresponding `-lib` is. Then again there's not always a hxml file either.. :(

**Comment by Gama11** [comment]
There several cases in which that's not true. There's no need for a hxml when adding compiler arguments directly to the  `haxe.displayConfigurations` setting. Lime projects also have no HXML, they use vshaxe's `DisplayArgumentsProvider` API.

**Comment by Gama11** [comment]
Maybe we could use the current display file, that always exists. That might lead to the same error appearing multiple times though...

Or perhaps, we could just supply some dummy URI that doesn't actually exist on the file system. It's similar with task compilation anyway, where VSCode thinks the file is called error with Haxelib errors.

**Comment by Gama11** [comment]
>Or perhaps, we could just supply some dummy URI that doesn't actually exist

Looks like that will work. :)
