### ISSUE TITLE
Provide class path to other extensions

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#221]
As discussed here https://github.com/ncannasse/vscode_hl/issues/4 it would be nice if vshaxe could provide some services to other extensions:
- output file
- target platform
- class path
- defines
- all "display" arguments

**Comment by Gama11** [comment]
I thought you just need the classpaths? What's the rest for? :)

**Comment by Gama11** [comment]
I'd prefer to add things on a as-needed basis for now. I thought you were going to use a `program` property in launch.json for the output file for consistency with other debuggers?

**Comment by ncannasse** [comment]
Yes that's still possible

**Comment by ncannasse** [comment]
Any progress on this ? It's blocking https://github.com/vshaxe/hashlink-debugger/issues/4 :)

**Comment by Gama11** [comment]
No, but it shouldn't be too hard to add a method for it to the new display protocol to get the classpaths directly from the compiler.

**Comment by ncannasse** [comment]
How far are we with that ? I would like to remove the need to set an HXML, but I'm not sure I want to rely on compiler being up to date etc. Can't we have something simple to get the current HXML from VSHaxe ?
