### ISSUE TITLE
Compatibility with the Code Outline extension

### ISSUE THREAD

**Issue by Pign** [vshaxe/vshaxe#223]
Symbols are not reported as a tree (following conversation with @Gama11 it seems it's because the entire definition range is not reported).

This is problematic when using the code outline extension.

**Comment by Gama11** [comment]
Details: https://github.com/patrys/vscode-code-outline#language-support

**Comment by Gama11** [comment]
VSCode is actually adding a built-in code outline as well, see  https://github.com/Microsoft/vscode/issues/5605#issuecomment-389420027. I think this will require the same changes on our end though.

**Comment by Gama11** [comment]
Vshaxe 2.2.0 will support hierarchical document symbols! 🎉 Here's an example (the outline of the document symbol implementation itself):

![](https://i.imgur.com/kC3RFFk.png)

This also means that we support the breadcrumbs view that's being added in VSCode 1.26. Here's a screenshot from a current Insider's build:

![](https://i.imgur.com/wywaTo9.png)

**Comment by nadako** [comment]
> the breadcrumbs view

this looks sweet!

**Comment by Gama11** [comment]
It has these nice dropdowns too. ;)

![](https://i.imgur.com/aKfWrQT.gif)
