### ISSUE TITLE
Make the init project command work without a workspace folder

### ISSUE THREAD

**Issue by flashultra** [vshaxe/vshaxe#225]
Using VS Studio Code1.23 and Haxe 1.12 when try to use F1 -> Haxe : Intialize VS Code  Project received the following error " command 'haxe.initProject' not found" . For all other Haxe commands get similar errors.

**Comment by Gama11** [comment]
That sounds like the extension isn't running / activated at all. Do other things work, e.g. code completion in a hello world project?

Is there anything interesting in the dev console (Help -> Toggle Developer Tools)?

**Comment by flashultra** [comment]
Sorry , my mistake. I was never used VS Code before and I choose " Haxe : Intialize VS Code Project " , without open the empty folder. So I was need to create from console new empty folder and after that to choose the command.  Is it more convenient the command to create new folder for the empty haxe project ?  In VS Code doesn't have create new folder command ( have 'New file' and 'Open Folder' ) . I miss the easy way to create new project from FlashDevelop ( i.e . Project -> New Project -> ....)

**Comment by Gama11** [comment]
Oh, I see.. I think this is actually a valid feature request - we could probably make "init project" work if there's no open folder.

Right now vshaxe doesn't activate if there's no folder open, but there's a TODO for it:

https://github.com/vshaxe/vshaxe/blob/55af8777037fe779be76539f69f49ff3c1c55b09/src/vshaxe/Main.hx#L23
