### ISSUE TITLE
Tasks to build "current hxml" ?

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#230]
In hxml build task it is necessary to specify an hxml "file" , however switching the hxml for completion using the blue bottom bar does not switch the task. Could it be possible to have the task use the select hxml when no "file" is specified ? (and have it be the default ?)

**Comment by Gama11** [comment]
I think you want to use the `haxe: active configuration` task that was added in 1.12.0. :)

**Comment by ncannasse** [comment]
Ah I see :) thanks.
Also, could you add a default label "Build" on build tasks, because I need a way to reference them in launch.json if I want F5 to Build & Launch. That should be harmless and helpful :)

**Comment by ncannasse** [comment]
And now I really want to know how to get current hxml from within my HL launcher :D

**Comment by Gama11** [comment]
Why do you need a special prefix to reference them from launch.json?

**Comment by ncannasse** [comment]
In launch.json if I want "preLaunchTask" I need to put a label on the Build task, no?

**Comment by Gama11** [comment]
Well, the tasks generated by vshaxe _have_ labels, i.e. `"preLaunchTask": "haxe: active configuration"` should work?

**Comment by ncannasse** [comment]
The task generated for me is like this:
```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "haxe",
			"args": "active configuration",
			"problemMatcher": [
				"$haxe-absolute",
				"$haxe",
				"$haxe-error",
				"$haxe-trace"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
````

Then if I add:

"preLaunchTask": "haxe: active configuration"

To my launch.json, it complains about task not found.

(vshaxe 1.12)

**Comment by Gama11** [comment]
Are you sure you're in a project with more than one configuration, so the "haxe: active configuration" task actually exists in the Tasks -> Run Task menu? Replacing this line in HaxeRepro works as expected for me:

https://github.com/Gama11/HaxeRepro/blob/master/.vscode/launch.json#L8

```
"preLaunchTask": "haxe: active configuration"
```

**Comment by Gama11** [comment]
Oh, I guess it must be part of your tasks list, otherwise VSCode wouldn't have offered the option to customize it. What VSCode generates into tasks.json there is totally optional btw, and just needed if you want to mark it as the default build task via `isDefault: true`. You can also remove the `problemMatcher` array for a more minmalistic config, if it's missing, the default ones defined by vshaxe will be used.

**Comment by ncannasse** [comment]
If I remove tasks JSON and press F5 I get the following error:

Task "haxe: active configuration" not found.

**Comment by Gama11** [comment]
Any update here / can this be closed?

**Comment by ncannasse** [comment]
In HaxeRepro you have a manual inserted label for each tasks.json, and the
launch.json reference this label in preLaunchTask. I was thinking that the
auto generated task (with Configure Default Build Task) should be able to
automatically define "label" : "Build" so there is no manual editing to be
done here.

**Comment by Gama11** [comment]
That's not the case. Do you mean the labels in `settings.json` here?

![](https://i.imgur.com/nevvXNy.png)

Those actually have nothing to do with _task_ labels, and can't be referenced via a `preLaunchTask`. It just changes how the _configurations_ appear in the UI  (in the status bar or the "Haxe: Select Configuration" command).

**Comment by Gama11** [comment]
The tasks referenced as pre-launch tasks in HaxeRepro (`"preLaunchTask": "Flash (debug)"`) are actually referencing _manually defined_ tasks / tasks that weren't created by vshaxe. So things like `taskPresentation` don't work on those. That's also why they have the complete `problemMatcher` list (for vshaxe-generated tasks that would be redundant).

**Comment by ncannasse** [comment]
a) checkout HaxeRepro
b) remove .vscode/* files
c) Task / Configure Default Task / haxe: active configuration
d) Press F5 , choose HashLink
e) Press F5 again : error "the task Build cannot be found"

At this point it is required to add "label" : "Build" to the haxe
tasks.json, that's what I would like to be done automatically at task
generation

**Comment by Gama11** [comment]
>At this point it is required to add "label" : "Build" to the haxe
tasks.json, that's what I would like to be done automatically at task
generation

No, what's required is to replace:

```
"preLaunchTask": "Build"
```

with

```
"preLaunchTask": "haxe: active configuration"
```

**Comment by ncannasse** [comment]
I get "Task 'haxe: active configuration' cannot be found

**Comment by ncannasse** [comment]
I'm using vscode 1.23.1 + vshaxe 1.12.0 (marketplace) , any reason this wouldn't work with this configuration?

**Comment by Gama11** [comment]
I just tried switching to the identical versions of both of those, and I still can't reproduce the problem. I'm not really sure what it could be at this point...

Sometimes _right after starting up_ vscode, tasks aren't available yet because the tasks providers haven't been called. So if I open VSCode and press the debug button _right away_ I can actually provoke this message:

![](https://i.imgur.com/hpRFKHJ.png)

But when trying again after that it works, it doesn't sound like this is your problem?

Meanwhile, completion features work, the status bar items show up etc? (which would indicate that vshaxe has started up properly and is able to provide tasks)

**Comment by ncannasse** [comment]
Tried various things including emptying my settings: I can't get the
"preLaunchTask" : "haxe: active configuration" to be recognized by VSCode
I'll try tomorrow on my colleague computer.

Completion works, Shift+Ctrl+B builds, but F5 does fail because of missing
task.

Also, if there is a single hxml in the directory, haxe: active
configuration does not show up in the list when selecting tasks. However
this is not related to the error as I also have the bug when there's
several hxml in directory.

**Comment by Gama11** [comment]
>Also, if there is a single hxml in the directory, haxe: active
configuration does not show up in the list when selecting tasks.

That's intentional, we only generate the `active configuration` task if there's at least two configurations (as it would be a bit redundant otherwise, you'd have two tasks doing the same thing).

**Comment by ncannasse** [comment]
It works on my colleague computer. Still no idea what's wrong on mine.

**Comment by ncannasse** [comment]
Removed VSCode and all extensions, reinstalled from scratch, still no luck. I'll open an issue on VSCode

**Comment by Gama11** [comment]
I guess this can be closed now that the corresponding VSCode issue has been closed.

**Comment by ncannasse** [comment]
Actually it's still not working with 1.25 (;_;)

**Comment by ncannasse** [comment]
Ok, with the following it works:

```
"preLaunchTask": {
				"type" : "haxe",
				"args" : "active configuration"
			}
```

But... only if there are several HXML in the workspace directory :'(

**Comment by Gama11** [comment]
Yeah, as mentioned before, that was by design, since it seemed a bit redundant to have two generated tasks that both do the same thing in the "single-HXML-scenario". I guess it's not too important though and the restriction could be lifted.
