### ISSUE TITLE
Add a setting to allow filtering packages in toplevel completion

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#234]
With the new toplevel completion showing everything, not just things that are imported, it may become necessary to have a way of hiding types from certain packages. We could have a setting that's simply an array of packages to be filtered out.

A potential use case for this is Nape's `zpp_nape` package for instance, which is meant to be internal (so you wouldn't want anything from there to show up in the completion results usually).

**Comment by back2dos** [comment]
Uhm, does `@:noCompletion` work on classes? Ideally it'd be based on that. You could still use `--macro addGlobalMetadata` if you can't modify the lib sources.

**Comment by Gama11** [comment]
This is less about hiding classes and more about hiding entire packages (including their contents). Packages show up as separate "entities" in completion too:

![](https://i.imgur.com/1pEDuEG.png)

**Comment by back2dos** [comment]
I guess you could hide packages that don't contain modules having types that are neither private nor marked as `@:noCompletion`, but I see it's trickier than I initially assumed.

**Comment by Gama11** [comment]
It'd also be a bit inconvenient if you have to stick `addGlobalMetadata` in every project, when you could just have some global vscode setting such as:

```json
"haxe.excludePackages": [
    "zpp_nape"
]
```

In general, having to modify _compiler_ arguments for what you want filtered out of code completion doesn't seem right to me.

**Comment by back2dos** [comment]
> In general, having to modify compiler arguments for what you want filtered out of code completion doesn't seem right to me.

I think in general library authors should be provided the means to hide code from completion, instead of expecting every user to modify their VSCode settings - assuming they are using VSCode to start with. If it can be done with reasonable effort, the problem you raise (i.e. with nape's internal package) should be fixed in the compiler services. That said, a complementary setting on VSCode's side probably won't hurt either way ;)

**Comment by Gama11** [comment]
>I think in general library authors should be provided the means to hide code from completion

There is a means: prefixing packages with an underscore. But Nape probably predates that and won't get updated anymore to change that either.

On top of that, there are valid reasons why a _user_ may want to filter out packages (rather than library authors). And I don't think there's a risk of having too many settings any time soon, the JSON schema auto-completion makes it pretty intuitive to edit / browse them anyway.
