### ISSUE TITLE
[Discussion] Multi Launch options

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#236]
In my Heaps samples I came up with the following:
https://github.com/HeapsIO/heaps/blob/master/samples/templates/.vscode/launch.json

It defines different launch options, and links the corresponding preLaunchTask.

However this requires switching both the Launch Configuration and the Haxe Configuration in order to get both completion and compilation using the same context.

We could get rid of tasks.json by using "preLaunchTask" : "haxe: xxxx.hxml" (if I manage to make it work on my computer) or by using new insiders features for preLaunchTasks. 

But would there be a way for Haxe context to use the hxml based on currently selected Launch Configuration, or another way?

**Comment by Gama11** [comment]
>by using new insiders features for preLaunchTasks.

?

**Comment by ncannasse** [comment]
@Gama11 see the response I got here https://github.com/Microsoft/vscode/issues/51431

**Comment by Gama11** [comment]
>But would there be a way for Haxe context to use the hxml based on currently selected Launch Configuration, or another way?

So basically, you want this dropdown menu in the debug menu

![](https://i.imgur.com/mRIWg9M.png)

...to function like the target dropdown in FlashDevelop, i.e. also switch the target used for code completion?

I'm pretty sure that's not possible, since VSCode's API doesn't let us retrieve the state of random UI elements. Besides, it would also be confusing to have two ways of doing that (the status bar item / select haxe configuration command and this).

**Comment by ncannasse** [comment]
What we want ideally is the following:
- select the hxml you can completion with (whatever the platform)
- press F5 to compile + run + debug

So it means you would define a single launch task, which would use the platform debugger you have selected. For additional options, you could have the following:

```js
{
            "name": "HaxeDebug",
            "type": "haxedebug",
            "request": "launch",
            "preLaunchTask": "haxe: current configuration",
            "options": { "hl" : { /* hl specific options to pass to debugger */ } },
}
```

**Comment by Gama11** [comment]
That would work, if you rebind the `Haxe: Debug Selected Configuration`  command to <kbd>F5</kbd>.

**Comment by ncannasse** [comment]
You mean that this definition should be a task in tasks.json, it can't be
inside launch.json ?

**Comment by Gama11** [comment]
No, you'd still need a launch.json config... Its name would simply need a task with a matching label.

**Comment by Gama11** [comment]
I've implemented a "Debug Selected Configuration" command as described earlier. It assumes there's a launch configuration whose name matches the currently selected Haxe configuration. If there is none, it errors.

You have two ways to make the labels match:
- adjust the names of the launch configs in `launch.json`
- create configs in `"haxe.displayConfigurations"` with a fitting `label`

See also [HaxeRepro](https://github.com/Gama11/HaxeRepro) for a working example.

You probably also want to define a keybinding along the lines of this:

```json
{
        "key": "f6",
        "command": "haxe.debugSelectedConfiguration"
}
```

**Comment by Gama11** [comment]
Have you had a chance to use this yet / does it work for your use case?

**Comment by ncannasse** [comment]
No but that doesn't really match what I want to achieve. You don't want to have to override your F5 key as it will break workflow with other languages, so my idea was more about creating a debugger proxy that would launch the corresponding debugger, but maybe that's too much overkill.

**Comment by Gama11** [comment]
You can conditionalize keybindings with [context values](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts). For instance, you could make sure the shortcut is only used / defined when vshaxe is active:

```json
{
        "key": "f5",
        "command": "haxe.debugSelectedConfiguration",
        "when": "vshaxeActivated"
}
```

**Comment by Gama11** [comment]
I've added a section for this command in the wiki:

https://github.com/vshaxe/vshaxe/wiki/Commands#haxe-debug-selected-configuration
