### ISSUE TITLE
Prevent build terminal window to get focus on build

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#237]
When I'm building a Haxe project (`ctrl + shift +b`), the terminal changes its window to the build task. I find this very annoying behavior because I don't care about the output and most of the time I have to change back to the other tab (`problems` tab for example or another terminal tab that run a watcher and auto-restart the process (node process for example).
Is it possible to run build silently?

**Comment by Gama11** [comment]
Yes, you can add this to your (global or workspace) settings:

```json
"haxe.taskPresentation": {
    "reveal": "never"
}
```

**Comment by mikicho** [comment]
Hooray! Maybe this should be the default behavior.

**Comment by Gama11** [comment]
I don't think it would make for a good default unfortunately, because it makes it too easy to miss compiler errors if you don't have the problems view opened at the moment. What we would need is for VSCode to support auto-revealing the problems tab instead of the terminal on errors.

**Comment by mikicho** [comment]
Hm... it's possible: `Vscode.commands.executeCommand("workbench.actions.view.problems");`

**Comment by Gama11** [comment]
Yes, showing the problems view is possible since recent VSCode versions. But we don't really know whether there are compiler errors or not. Technically we might be able to extract that information, but only if `haxe.enableCompilationServer` is true, so that doesn't seem very clean either...

**Comment by mikicho** [comment]
Don't you get the errors in the `stdout`?

**Comment by Gama11** [comment]
No, with the tasks API, we basically just define some command line to run. The actual execution, extracting the problems from it etc is all done by VSCode (problem matchers are declared in a descriptive fashion in package.json). So vshaxe doesn't have much control over this.

**Comment by mikicho** [comment]
I'm sure you guys know this but tasks built to detect errors in the build tasks? https://code.visualstudio.com/docs/editor/tasks#_task-autodetection
I'm curious what the problem with this approach.

**Comment by Gama11** [comment]
There's no problem with it, vshaxe actually uses these problem matchers as mentioned. It's just that vshaxe doesn't know about the errors that result from that / has no way to check if there are any, the extension API doesn't allow for that yet as far as I know. I think something for it may be planned though.
