### ISSUE TITLE
Actual error not always visible from Haxe server output

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#239]
In previous vshaxe, we could easily see from Haxe output what would make it fail to provide some completion.

It seems that the JSON-RPC based completion doesn't do this anymore. I have some errors in my project, but instead of getting these errors in Haxe output in vshaxe, I get some JSON parsing errors (see screenshot below):

<img width="692" alt="capture d ecran 2018-06-13 a 18 40 23" src="https://user-images.githubusercontent.com/164094/41365577-08af0a1e-6f3a-11e8-9999-0d5b9d0c439c.png">

**Comment by Gama11** [comment]
How do I reproduce this? Here's a simple invalid code example witha failed hover (keyword being used as a var name which confuses the parser), and I get the expected error output:

![](https://i.imgur.com/WmFICbQ.png)

**Comment by jeremyfa** [comment]
Can’t say what triggers the issue yet as I just tried over a large project and got into this problem, but I will add some more logs in my local vshaxe installation to see what is the underlying error causing the json parse problem. I will update this issue when I got more info

**Comment by jeremyfa** [comment]
I investigated a bit more, I honestly can't say why at some places it fails to provide hover code completion in the project, and I didn't succeed to reproduce it on a smaller example ☹️.

What I can say is that vshaxe is trying to parse "Not_found" in that case, which is returned by the jsonrpc request:

```
[
    "DResult",
    1,
    "Not_found"
]
```

So I guess there could be some slight improvement on vshaxe side to stop trying to parse a string (Not_found) which is not a JSON string, but that sounds like a minor issue.

For the _why it returns "Not_found"_, I wish I could provide more precise info about it. There seem to be some more error that pop out with haxe 4.0.0+ server from time to time in my project that I need to make sense of first, but this is out of the scope of this issue anyway. The main point here was the "Not_found" causing some JSON parse error in vshaxe.

**Comment by Gama11** [comment]
I think we did actually change some defaults that lead to the "raw" compiler results not being shown anymore with `-v`. Should be better once https://github.com/vshaxe/vshaxe/issues/240 is implemented.
