### ISSUE TITLE
Typedef without terminating semicolon breaks highlighting

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#24]
See this example in `Test.hx`:

![](http://i.imgur.com/3rsID9d.png)

(little-known fact, that's valid Haxe syntax)

**Comment by Simn** [comment]
That could actually be a parser oversight...

**Comment by Gama11** [comment]
I think @nadako wouldn't be happy about that. :D

**Comment by nadako** [comment]
i don't really care. i thought type declarations aren't required to have semicolon

**Comment by Gama11** [comment]
I guess I'll mark this as a 'wontfix' after all. I had to revert the previous fix to fix something else, and considering how rare it is to actually omit the semicolon here...
