### ISSUE TITLE
Too ?many? 

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#244]
I just discovered a new Haxe syntax :)

![image](https://user-images.githubusercontent.com/1022912/41416527-599415d0-6feb-11e8-856f-3c0c08c4065e.png)

**Comment by Gama11** [comment]
`?` is used for printing monomorphs, because the `Unknown<0>` we had previously looks stupid. :) We even highlight this somewhat nicely in hover hints:

![](https://i.imgur.com/KtcI6HX.png)

Open to better suggestions though. Ideally we just wouldn't ever have any monomorphs in completion. ;)

**Comment by Gama11** [comment]
That may be an option. Why it's a monomorph, no idea. @Simn? :)

**Comment by nadako** [comment]
I think that's what I originally did for function arguments (just don't display anything for unknown types)

**Comment by Simn** [comment]
Not sure why that's a monomorph, might be a `return_partial_type` thing.
