### ISSUE TITLE
task with hxml in sub folder won't be recognized

### ISSUE THREAD

**Issue by postite** [vshaxe/vshaxe#247]
i get this error:

    The task will be ignored.
    Error: The hxml task detection didn't contribute a task for the following configuration:
     {
        "label": "bing",
        "type": "hxml",
        "file": "/src/bing.hxml",
        "problemMatcher": [
            "$haxe-absolute",
            "$haxe",
            "$haxe-error",
            "$haxe-trace"
        ]
    }

no probs when hxml is in workspaceroot...

**Comment by Gama11** [comment]
Yes, we don't support detection in subfolders at the moment. It's a bit awkward because we can't really know whether the cwd when calling the hxml should be the subfolder or the workspace root.

**Comment by Gama11** [comment]
I don't think we should change anything here for now, it's easy enough to add the subfolder HXML files you might have in `"haxe.configurations"`.

**Comment by RblSb** [comment]
Is there no way to run task with hxml type and subfolder path? I want to run subproject compilation and then interp or run it as script from task, without moving build-subproj.hxml to root.
