### ISSUE TITLE
--cwd in hxml spoils completion

### ISSUE THREAD

**Issue by RealyUniqueName** [vshaxe/vshaxe#248]
I have this dev-display.hxml in the root of Haxe compiler workspace:
```
--cwd tests/unit
compile-php.hxml
```
The second completion request fails:
```
Haxe language server started
Listening on port 6000
Building Cache...
Failed - try fixing the error(s) and restarting the language server:

Error: Could not process argument dev-display.hxml (file not found)
invalid character: -
```

**Comment by RealyUniqueName** [comment]
Despite the message in output pannel I somehow get completion working for the first request.

**Comment by Gama11** [comment]
@Simn sounds like an issue with Haxe's cwd handling to me?

**Comment by Gama11** [comment]
Fixed by https://github.com/vshaxe/haxe-language-server/commit/320a28533594dca34a75430c854bf2f79999dfff.
