### ISSUE TITLE
Add highlighting for untyped functions (__js__, __java__, etc)

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#25]
Some of these are documented in the manual, but there's actually a lot more than the ones that are documented:

https://haxe.org/manual/target-javascript-untyped.html
https://haxe.org/manual/target-php-untyped.html

The best option to get a comprehensive list seems to be searching the std lib for `__[\w]+__` and manually filtering out false positives.

It would be nice if the highlighting isn't global and only takes effect after the `untyped` keyword (they seem to be valid Haxe variable names for instance).

**Comment by Simn** [comment]
Can we use some color that looks like toxic waste for these?

**Comment by Gama11** [comment]
Depends on the color theme!

**Comment by kevinresol** [comment]
I wonder if we can replace all these "magical syntax" with proper ones (say in Haxe 4). Just like `python.Syntax.pythonCode`
