### ISSUE TITLE
displayPort = "auto" not working?

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#250]
We often experience "The Haxe compiler crashed 5 times" even while having the default (displayPort = "auto"). Are we sure that the port is available and not used by another application ? I would recommend that when the compiler crash this way we increment the port number - just in case.

**Comment by Gama11** [comment]
I wonder if this is related to #235. Do you also get error output similar to that?

**Comment by Gama11** [comment]
Not really sure what to do with this / how to reproduce it.

**Comment by Gama11** [comment]
But we already check if a port is in use and increment until we find a free one... Otherwise this wouldn't work with multiple VSCode instances to begin with.
