### ISSUE TITLE
Completion sometimes doesn't insert correctly

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#252]
I had the following:

```haxe
var copy = new h3d.pass.Copy();
copy.pass.set|(false,false,true,false);
```

| =  cursor position (after writing `set`)

If I auto complete to setColorMask, this will result in the following:

```
copy.pass.setColorMaske,false,true,false);
```` 

Whereas I would have expected:

```
saoCopy.pass.setColorMask(false,false,true,false);
```

It seems it uses replace mode instead of insert. Sometimes :'(

**Comment by Gama11** [comment]
By "sometimes" you mean "in some cases" or "even for the same example, it only reproduces sometimes"? So far I haven't managed to reproduce it.

**Comment by nadako** [comment]
I can confirm that this happens to me "sometimes" too :)

**Comment by Gama11** [comment]
It would be interesting to know what the `replaceRange` that Haxe sends us looks like in such a case.

**Comment by ncannasse** [comment]
I confirm it seems highly reproducible with metadata completion, maybe a bug specific to it ?

**Comment by Gama11** [comment]
Yep, I can reproduce it too there. Definitely an issue with the replaceRange that Haxe sends:

![](https://i.imgur.com/iLqAJDL.png)

**Comment by Gama11** [comment]
https://github.com/HaxeFoundation/haxe/issues/7251
