### ISSUE TITLE
Error message ordering

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#253]
It is important that VSHaxe preserve the ordering of Haxe error messages.
For instance I had some code with the following error:

![image](https://user-images.githubusercontent.com/1022912/41778315-ad03dd9c-762e-11e8-9545-9e92978a92e5.png)

And VSCode reported it as:

![image](https://user-images.githubusercontent.com/1022912/41778343-ca24a0d2-762e-11e8-9a9e-c8f7bee0b7aa.png)

Which gave me a hard time understanding about the `Void should be { x : Int }` error whereas the error was actually the `Unknown identifier` one.

**Comment by Gama11** [comment]
What's the easiest way to reproduce this? With this, I just get two errors and they're ordererd as expected:

```haxe
class Main {
	public static function main() {
		Std.int("");
	}
}
```

![](https://i.imgur.com/uuCnyzd.png)

We probably can't do anything about this anyway, as we don't control the ordering. I'm guessing VSCode sorts by position in the file.

**Comment by Gama11** [comment]
Still no repro case here.

**Comment by Gama11** [comment]
So... like this?

```haxe
class Main {
	public static function main() {
		Foo.foo();
	}
}
```

```haxe
class Foo {
	public static function foo(bar:Invalid) {}
}
```

Looks ok to me:

![](https://i.imgur.com/DWKVeS3.png)

**Comment by ncannasse** [comment]
What about Zoo.hx ?

Le jeu. 26 juil. 2018 13:41, Jens Fischer <notifications@github.com> a
écrit :

**Comment by Gama11** [comment]
Wat?

**Comment by Gama11** [comment]
![](https://i.imgur.com/y2gjZ1i.png)

I mean, yeah, "Defined in this class" is above the message it comes from.. but what do you expect? The problems view groups error by file. :)

Anyway, blocked by https://github.com/Microsoft/vscode/issues/55253.

**Comment by ncannasse** [comment]
You can group and still keep the file order based on compiler errors order,
so at least the first file / first error will correspond to the first
compiler error. But I understand it requires some vscode api to control
this kind of sorting.
