### ISSUE TITLE
Compilation Server timestamps

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#254]
Timestamps checks are disabled for completion/hover which is fine.
However they should be enable to compilation, as currently it requires to close/reopen vshaxe to refresh files that have been modified outside of VSCode.

PS: that's a huge anointment for everyone at Shiro and for any kind of team work, hopefully it will be fixed quickly :-)

**Comment by Gama11** [comment]
I think this would have to be done on the Haxe side.

**Comment by Gama11** [comment]
I think this is the same as https://github.com/HaxeFoundation/haxe/issues/7203.
