### ISSUE TITLE
Recurse into EitherType for expected type generation

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#256]
Right now, the following doesn't offer any function generation:

![](https://i.imgur.com/Pfjwt6H.png)

The `PromiseCallback` type used by `then()` is defined as `EitherType<T -> TOut, T -> Promise<TOut>>`. We should recurse into `haxe.extern.EitherType` and offer to choose between both functions.

Thinking about it more, we should even be smart enough to notice that it doesn't matter in scenarios where only the return type differs and that doesn't impact the code generation (e.g. when we don't print return types, or we're using arrow functions, where we can't have return type hints anyway). So for this specific case, we would only need to show one option by default.

**Comment by back2dos** [comment]
Perhaps `T->EitherType<TOut, Promise<TOut>>` would already improve this?

**Comment by Gama11** [comment]
Perhaps, but you shouldn't have to write your code to fit the IDE / it should be able to deal with both.

**Comment by back2dos** [comment]
Yes and no. 

From a practical perspective, I have to ask: if you want this, should it also work for nested `EitherType`? Should it also work for `@:coreType EitherTypeOfThree<A, B, C> from A from B from C {}`?

But more importantly: `EitherType` quite frankly is a hack that bends existing language features to accomplish something that'd be best expressed with overloads (if they didn't result in such horrible error messages) or type unions.

Either way, it goes beyond IDE support: https://try.haxe.org/#ddF8e

**Comment by Gama11** [comment]
This basically works now:

![](https://i.imgur.com/ozFCYEp.png)

(apart from structures, but that's a Haxe issue https://github.com/HaxeFoundation/haxe/issues/7262)
