### ISSUE TITLE
Setting haxe.executable seems to be ignored suddenly

### ISSUE THREAD

**Issue by flipflophhj** [vshaxe/vshaxe#259]
It insists on finding haxe in c:\Haxetoolkit\haxe 

I can configre haxe.executable to whatever with no effect.

I hadn't even changed it since it worked fine with the haxe accessible through path and environment but suddenly it started complaining about not being able to find c:\Haxetoolkit\haxe\haxe,exe which is not where I have it installed.

Currently worked around it with a symlink dir

**Comment by Gama11** [comment]
Do you maybe have `haxe.executable` specified both in your workspace and global settings, the former overriding the latter?

Are you using Lix? It does some weird things with your Haxe executable. :)

**Comment by flipflophhj** [comment]
No I hadn't had any reason to change the default "haxe" until it suddenly stopped working.

I can run haxe from commandline fine. Just to verify that "haxe" still should work.

**Comment by Gama11** [comment]
So, to clarify, you're getting an error about vshaxe not being able to find `C\HaxeToolkit\haxe`..? What's the exact error, and what do your settings look like?

**Comment by flipflophhj** [comment]
I have found the problem. Some other guy on the team had committed a folder settings file with the haxe path in it.

Sorry to bother you..

**Comment by Gama11** [comment]
No problem! I have some ideas of how to improve `haxe.executable` handling in the future with "named" Haxe versions / executables. That would allow you to have a customized Haxe version for a specific project without needing to check in a system-specific path into version control by referencing some executable name defined in the global `settings.json`.

**Comment by flipflophhj** [comment]
That would be nice. It's a bit of a nightmare with the haxelib path and haxelib versions also differing from project to project. Thankfully the environment variable HAXELIB_PATH was introduced in haxe 3.2 I think. But for all the projects we have using prior versions it is causing some headache on the buildserver..
