### ISSUE TITLE
Overloaded functions don't display the "Void args" case

### ISSUE THREAD

**Issue by jcward** [vshaxe/vshaxe#260]
(I'm not sure if this bug is in Haxe or in vshaxe, cc @nadako @Gama11)

The `Void -> <anything>` case is always ignored by overload completion:

For example, this function correctly shows the proper overloads, two of  them:

![image](https://user-images.githubusercontent.com/2192439/42333114-124f0dc2-8037-11e8-969e-7a887d8f959e.png)

However, adding a third case with no args, should make another option show up, but it doesn't:

![image](https://user-images.githubusercontent.com/2192439/42333202-58a22548-8037-11e8-861f-0fbacbb167c0.png)

It's ignored regardless of the return type:

![image](https://user-images.githubusercontent.com/2192439/42333247-7a4e0310-8037-11e8-8f4c-10873d4be04b.png)

It's ignored even if it was the explicit type signature, and others were overloaded:

![image](https://user-images.githubusercontent.com/2192439/42333278-90448e28-8037-11e8-9d81-f230590e3b90.png)

Tangentially related to https://github.com/HaxeFoundation/haxe/issues/5201 - an updated `@:overload` that would allow multiple comment docs.

**Comment by Gama11** [comment]
Looks like a Haxe bug, the `display/signatureHelp` method only returns two signatures:

![](https://i.imgur.com/b5WVkDI.png)

Interestingly, `display/completion` contains all three overloads.

**Comment by Gama11** [comment]
Moved to https://github.com/HaxeFoundation/haxe/issues/7249.

**Comment by Gama11** [comment]
The Haxe issue has been resolved now:

![](https://i.imgur.com/2Z2tgRX.png)
