### ISSUE TITLE
about --connect PORT on task build 

### ISSUE THREAD

**Issue by R32** [vshaxe/vshaxe#262]
when i run task build, i got the following cmd:

```cmd
haxe.exe build.hxml --connect 6000
```
I feel it's not quite right if there is `--each` in `build.hxml`, so i think it shoud be:
```cmd
haxe.exe --connect 6000 build.hxml
```
Because I think `--connect 6000` should be placed in front of `--each`, I know that neither `--next` nor `--each` are recognized by any Haxe IDEs, But I hate putting too much `build-XXX.hxml` on a project.

**Comment by Gama11** [comment]
So it actually behaves differently depending on the order? :/

**Comment by R32** [comment]
putting "--connect 6000" in front or behind of "build.hxml" will produce different output.

https://github.com/HaxeFoundation/haxe/issues/4577

**Comment by Gama11** [comment]
Seems you're right, I changed the order.
