### ISSUE TITLE
Dependency listed twice

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#263]
Not sure exactly why, but it happens quite often:
![image](https://user-images.githubusercontent.com/1022912/42417950-c5ffb6ea-8295-11e8-92bf-c6be37539e5b.png)

**Comment by Gama11** [comment]
Is there an easy way to reproduce with a sample project or something? I don't think I've seen this before.

**Comment by ncannasse** [comment]
You can open any heaps sample

**Comment by Gama11** [comment]
This is an interesting one. Your hxml includes heaps twice:

```hxml
-lib heaps
[...]
-cp ../..
```

Normally this wouldn't be an issue, we already check for duplicate paths. But somehow, one of them ends up with a lowercase `c:\` and the other one with an uppercase `C:\`. It's the mix of `-cp` and `-lib`, two of the same wouldn't produce this issue.
