### ISSUE TITLE
No code action to generate arguments/closures with dev Haxe 

### ISSUE THREAD

**Issue by RealyUniqueName** [vshaxe/vshaxe#264]
It works with 3.4.7, but with dev Haxe there are no code actions available.
![](http://dl3.joxi.net/drive/2018/07/12/0018/2666/1194602/02/9df90a5fd8.jpg)

**Comment by Gama11** [comment]
This is now done with completion instead of code actions (<kbd>Ctrl</kbd>+<kbd>Space</kbd>):

https://github.com/vshaxe/vshaxe/wiki/What's-New-in-2.0.0#expected-type-completion
