### ISSUE TITLE
What's New in 2.0.0

### ISSUE THREAD

**Issue by peteshand** [vshaxe/vshaxe#268]
The What's New in 2.0.0 page lists a few feature, but doesn't actually say what keys need to be pressed to use them. For example the "Expected Type Completion" feature looks great, but how is this activated? In the video it looks like the cursor is pressed after the PosInfos typedef, does a key also need to be pressed as the same time, or some setting enabled?

**Comment by peteshand** [comment]
Ok, it mentions it a little bit further down the page, Ctrl+Space

**Comment by Gama11** [comment]
Still, good point, it was a bit hidden - I moved it to the top of that section. :)

**Comment by peteshand** [comment]
Great thanks.. one other thing while I've got you.. it might be worth adding a section to the wiki for "recommended Haxe settings", So you can see all the settings one place? 

{
    "files.autoSave": "afterDelay",
    "haxe.displayServer": { // configuration for starting haxe completion server itself
        "arguments": [], // arguments before --wait (-v is useful for debugging)
    },
    "haxe.codeGeneration": {
        "functions": {
            "anonymous": {
                "argumentTypeHints": true,
                "returnTypeHint": "always",
                "useArrowSyntax": true
            }
        },
        "imports": {
            "enableAutoImports": true
        }
    },
    "haxe.enableDiagnostics":true,
    "haxe.diagnosticsPathFilter":".*?",
    "haxe.enableCodeLens": false,
    "haxe.enableMethodsView": true
}

**Comment by Gama11** [comment]
Have you seen that settings are listed on the extension's contributions tab?

![](https://i.imgur.com/g85OEoa.png)

**Comment by peteshand** [comment]
Nope, that would have been VERY helpful yesterday :)
Thanks for pointing me in the right direction
