### ISSUE TITLE
Unable to build cache - completion features may be slower than expected.

### ISSUE THREAD

**Issue by Hersir88** [vshaxe/vshaxe#270]
Hi,
not sure if correct place, as I get this in lime vscode project, but anyway. Got error message `Unable to build cache - completion features may be slower than expected.` More info on error `[Error - 09:35:52] Request textDocument/codeLens failed.
  Message: src/Main.hx:35: characters 8-47 : Type not found : extensions.admob.AdmobAne
  Code: -32603 `

This type is part of adobe air `ane` file (native extension) and added in `project.xml` `<dependency name="extensions.admob.AdmobExtension" path="ext/Admob.ane" if="air" />`

I know that haxe flash target is dying slowly but if not fixed maybe could somehow be excluded (by classpath list or so)?

**Comment by Gama11** [comment]
This is not a problem with the Haxe Flash target, but more likely the arguments `lime display` provides for code completion. Apparently this `extensions.admob.AdmobAne` type is missing from the classpaths reported by it there?

Is this admob extension public somewhere so I could reproduce this?

**Comment by Hersir88** [comment]
I compiled it myself so can attach it here (will add other smaller ane) but really could be that all ane files have this issues, as I have 3 other with same errors.
[SettingsANE.zip](https://github.com/vshaxe/vshaxe/files/2216017/SettingsANE.zip)


`<dependency name="lv.hansagames.extensions.settings.SettingsANE" path="ext/SettingsANE.ane" if="air" />`

`import lv.hansagames.extensions.settings.SettingsANE;`

**Comment by Gama11** [comment]
When including that `.ane` directly with `<dependency>` like you did there, I got this error:

```
Error: Create OpenFLProject\ext/adl directory, and extract your ANE files to .ane directories.
``` 

After extracting it, it doesn't complain anymore, but `lime build air` also doesn't work:

```
src/Main.hx:2: characters 8-53 : Type not found : lv.hansagames.extensions.settings.SettingsANE
```

What am I missing?

**Comment by Hersir88** [comment]
So lets check libs 

- openfl - 8.3.0

- lime - 6.4.0

- adobe air 30 sdk

- haxe - 4 preview 4

also newsest vscode lime and haxe from marketplace, and I compile for mobile xcode simulator
`lime test air -ios -debug -simulator`

Some more props in `project.xml`
`<config:air sdk-version="30.0" />`
`<set name="SWF_VERSION" value="30.0" />`

**Comment by Gama11** [comment]
Hm... actually, it works now, but I'm not sure what I did differently.

Anyway, this is indeed a bug in `lime display air`. The `.hxml` files used for compilation (e.g. `bin/air/haxe/release.hxml`) have this line, which is missing from the display arguments:

```hxml
-swf-lib ext/SettingsANE.ane
```

Unsurprisingly, the compiler can't find any types the native extension if it's missing.

https://github.com/openfl/lime/issues/1212
