### ISSUE TITLE
Display file was not found in class path

### ISSUE THREAD

**Issue by Hersir88** [vshaxe/vshaxe#273]
Got error in vscode, after clicking show more, got this message every time I open my project in vscode.
![screen shot 2018-07-22 at 20 32 19](https://user-images.githubusercontent.com/8036190/43048364-34e041c4-8def-11e8-9d71-c48ef7568576.png)
![screen shot 2018-07-22 at 20 34 20](https://user-images.githubusercontent.com/8036190/43048368-4102b8d8-8def-11e8-85f7-4d328de97dc6.png)

It tries to find the `Error` file in the root of the project.

**Comment by Hersir88** [comment]
Found more in output
```
Error: Display file was not found in class path
Failed - SyntaxError: Unexpected token H in JSON at position 0
[Error - 20:31:52] Request textDocument/codeLens failed.
  Message: Error: Display file was not found in class path
  Code: -32603 
```

**Comment by Gama11** [comment]
For which file do you get that error? Are you sure it's ... in your classpath?

>It tries to find the Error file in the root of the project.

That's "by design" - VSCode doesn't allow showing errors that are not associated with a file in the problems view right now. Using the "Error File" is a workaround for that. See also https://github.com/vshaxe/vshaxe/issues/214.

**Comment by Gama11** [comment]
Try to add this to your settings to get more detailed output in the Haxe output channel:

```json
"haxe.displayServer": {
        "arguments": ["-v"]
}
```

Chances are there's an invalid argument or something.

**Comment by Gama11** [comment]
More info is needed here (ideally a way to reproduce).

**Comment by carlito767** [comment]
Hi,

I encounted the same issue with my Kha project (Haxe 3.4.7, only Haxe extension installed)

Here is my output:

```
Haxe language server started
[Error - 10:31:24 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
Listening on port 6000
Processing Arguments [--cwd,w:/ChineseCheckersKha,-D,display-details,--no-output,--display,{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"supportsResolve":true}}]
Haxe version does not support JSON-RPC, using legacy --display API.
> Error: Invalid format: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"supportsResolve":true}}
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
Processing Arguments [--cwd,w:/ChineseCheckersKha,-D,display-details,--no-output,--display,w:/ChineseCheckersKha/Sources/Localization.hx@0@diagnostics]
> Error: Display file was not found in class path
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.001s
Error: Display file was not found in class path
```

I just need to open a .hx file to get the error.

**Comment by carlito767** [comment]
> Do you always get that error? I get it sometimes and just can't make out a pattern.

Yes. With Haxe 3.4.7, after disabling [Build Completion Cache](https://github.com/vshaxe/vshaxe/issues/284#issuecomment-410538301), I instantly get the error each time I open an .hx file. Same issue with Haxe 4.0 preview 4.

**Comment by RobDangerous** [comment]
Oh, I think I figured out what provoked the error for me - khamake's new parallel shader compilation was triggered, never finished and then the actual hxml file was not updated. So the error message was correct, but I'll have to watch it for a few more days to make sure it was the only situation where it happened.
Anyways, carlito, I'd like to have a look and I found your github project but it doesn't contain your vscode config.

**Comment by RobDangerous** [comment]
Uh oh, it's still happening but only in a fresh project and it looks like now I can reliably resolve it by restarting the language server. I think I'll be able to fix that...

**Comment by mundusnine** [comment]
### Haxe version: 4.0.0-preview.4+1e3e5e0
### OS: Debian
This still happens.Here is where it happens for me : 
- I have a main directory that contains git submodules
- I did `haxelib setup` for my submodule in the path `~/Documents/projects/godot-hx`
- I only have haxe code in submodules or subdirectory example:
```
godot-hx
|-externgenerator-hx/
|   |-my haxe code that uses haxelibs(tink_cli) and has a Main.hx file
|-Sources/
|  |-godot/
|  |  |-other haxe code
```
- It then gives me this error
- If I look at the error it gives me : `Unable to open 'Error': File not found (file:///home/jsnadeau/Documents/projects/godot-hx/Error).`


When I go in my git clone that is not a submodule externgenerator-hx, haxe works as is.

**Comment by koonsolo** [comment]
I had this same issue, and was able to fix this by setting "haxe.executable" to the proper version.

I'm using Kha and the haxe version that is bundled with it (now 4.0.0). But vshaxe was using an older haxe version installed on my OS. After setting "haxe.executable" to the version that comes with Kha, this issue was fixed.

I also noticed there is a difference in configuration when opening a folder vs opening a workspace in vscode, so make sure you are doing the config in the right file!!!

**Comment by RobDangerous** [comment]
Oh, this stopped happening for me by the way (unless of course I actually open a file which is not in the classpath) and with the latest Kha extension Kha's own Haxe should always be used automatically (via a weird hack which I still have to replace with a proper vshaxe API).

**Comment by gcardozo123** [comment]
I was having the same problems @Hersir88 reported. Not sure if it's related (I'm new with VSHaxe and Heaps), but in my case, I was running [Heaps Hello HashLink tutorial](https://heaps.io/documentation/hello-hashlink.html) and my `compile.hxml` had 
```
-lib heaps
-lib hlsdl
-hl hello.hl
-main Main
```
the error messages stopped after I've changed `-hl hello.hl` to `-hl Main.hl`.

**Comment by muchitto** [comment]
Sorry to revive an old issue, but this is happening to me now. I have a simple haxe heaps setup. The autocomplete isn't working for me now at all.

Here is some additional info:
https://gist.github.com/muchitto/4e9428fd402c69b8c34a7eae29e48280

**Comment by Gama11** [comment]
@muchitto This looks suspicious:

>src/Engine/Animation/Animation.hx

Package names in Haxe must be lowercase.

**Comment by muchitto** [comment]
Oh, that did the trick. It was just confusing, because the program would compile without a problem, so it wasn't apparent what the deal was. :)

**Comment by Gama11** [comment]
Was `Animation.hx` actually included in the compilation though?

**Comment by muchitto** [comment]
Yeah, "TEST" is shown in the console and everything. The autocomplete just doesn't work in Animation.hx (but in Main.hx, it works) and it can't find for example the h2d.Tile fields/properties or anything.
