### ISSUE TITLE
Completion in platform/_std/ gives error

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#280]
`Message: Invalid commandline class : hl._std.sys.db.Mysql should be sys.db.Mysql`

**Comment by ncannasse** [comment]
To reproduce, try completion in one of  haxestd/<platform>/_std classes

**Comment by Gama11** [comment]
I'm surprised you even got that far, I usually get a compiler hang: https://github.com/HaxeFoundation/haxe/issues/7236

**Comment by Gama11** [comment]
Oh, I guess you must still have diagnostics disabled? :)

**Comment by ncannasse** [comment]
Indeed :)

**Comment by Gama11** [comment]
Did you have some `.hxml` file there? Without any arguments, when I have haxe itself opened as a workspace, the error I get is:

>You cannot access the hl package while targeting cross (for hl._std.sys.db.Mysql)

If I open that file from a project that has `-hl` in its hxml, completion appears to work fine:

![](https://i.imgur.com/u6KF9gc.png)
