### ISSUE TITLE
haxe.diagnosticsPathFilter filters doesn't seem to work

### ISSUE THREAD

**Issue by peteshand** [vshaxe/vshaxe#282]
It seems like regardless of what I set haxe.diagnosticsPathFilter to, all haxelibs are being included in the diagnostics.

**Comment by Gama11** [comment]
What have you tried exactly? `"haxe.diagnosticsPathFilter": "${workspaceRoot}"` limits diagnostics to the current workspace for me.

**Comment by peteshand** [comment]
Hey there

Yeah so I've tried a few different settings, `"haxe.diagnosticsPathFilter": "${workspaceRoot}",` being one of them, however after restarting the language server I'm still see a the follow error message

`Unable to build cache - completion features may be slower than expected. Try fixing the error(s) and restarting the language server.`

Clicking "Show Error" displays about 10 errors from haxelib libraries, eg:
`lime/6,4,0/lime/_backend/air/AIRWindow.hx:105`

**Comment by Gama11** [comment]
The completion cache is unrelated to diagnostics. What are the exact errors?

Perhaps this is related to https://github.com/vshaxe/vshaxe/issues/270? Does it work if you have another target selected?

**Comment by peteshand** [comment]
Oh ok, I was under the impression that the completion cache were related to diagnostics. So what does the diagnostics do exactly?

I can work around / fix the issues with lime, so it's not really a huge deal, it just seems like the diagnosticsPathFilter wasn't working so I figured I report it.

**Comment by Gama11** [comment]
Have you seen the respective wiki pages?

- https://github.com/vshaxe/vshaxe/wiki/Completion-Cache
- https://github.com/vshaxe/vshaxe/wiki/Diagnostics

Diagnostics provide error messages as-you-type / without compiling. They're also responsible for graying out unused code. The completion cache is used by almost _all_ language-specific features : completion, signature help, hover, goto definition, etc... As such, diagnostics also benefit from the completion cache, so technically they _are_ related - but not any more than any of the other mentioned features.

**Comment by peteshand** [comment]
Cool, thanks for the info
