### ISSUE TITLE
WSL Supports

### ISSUE THREAD

**Issue by FuriouZz** [vshaxe/vshaxe#283]
Hello,

Do you have any plan for WSL (Windows Subsytem for Linux) supports ?

Actually I configured the haxe path to a batch file. This file execute wsl environment and pass arguments to my haxe installation.

```shell
wsl $(haxe %*)
```
Thanks to that tricks I can build my haxe project. But I still have issues, I cannot precise the HAXE_STD_PATH and I got an error with the version of Haxe when I try to use 4.0.0.preview.4.

Any suggestions?

**Comment by FuriouZz** [comment]
Finally, I use the windows haxe version and put haxe/haxelib/hl into Windows %PATH%. Now, I can use these commands in WSL environment.

**Comment by kLabz** [comment]
I am curious, how does this script work? I'd like my vshaxe to use haxe from WSL too.

**Comment by FuriouZz** [comment]
@kLabz 
I do not use any script file anymore. I installed haxe for Windows, then I created symlinks in WSL.

```
ln -s $(which haxe.exe) /usr/local/bin/haxe
ln -s $(which haxelib.exe) /usr/local/bin/haxelib
ln -s $(which hl.exe) /usr/local/bin/hl
```

If you do not want to create a symlink, you can make aliases into your .bashrc
```
alias haxe=haxe.exe
alias haxelib=haxelib.exe
alias hl=hl.exe
```

**Comment by kLabz** [comment]
Yeah but I need to do the reverse (what you were doing with the script)

**Comment by FuriouZz** [comment]
You need to call WSL command from Windows ?

Create a .bat file and add this
```
wsl $(MYCOMMAND %*)
```

For example for a `git.bat`
```
wsl $(git %*)
```
