### ISSUE TITLE
Stuck in "Haxe: Building Cache.."

### ISSUE THREAD

**Issue by prnxdev** [vshaxe/vshaxe#284]
Hi,

I installed today this extension but it looks like it stuck in "Haxe: Building Cache..". I have really simple project where I have one haxelib.json and one .hx file. I'm using newest VSC, MacOS High Sierra, Haxe 3.4.7.

haxelib.json:

```
{
  "version": "0.0.0",
  "name": "mtasa-haxe-types",
  "license": "MIT",
  "tags": ["mta", "gta"],
  "description": "Multi Theft Auto San Andreas variables and classes types",
  "releasenote": "Look at CHANGELOG.md",
  "contributors": ["pawel-miczka"]
}
```

My .hx code:

```hx
package mtasa.server;

@:native("_G")
extern class Functions {
  /**
    This function adds an account to the list of registered accounts of the current server.

    @see https://wiki.multitheftauto.com/wiki/addAccount

    @param name The name of the account you wish to make, this normally is the player's name.
    @param pass The password to set for this account for future logins.
    @param allowCaseVariations Whether the username is case sensitive (if this is set to true, usernames "Bob" and "bob" will refer to different accounts)
  **/
  public function addAccount (name:String, pass:String, ?allowCaseVariations:Bool = false):Bool; // TODO zaktualizować, bo to nie zwraca Bool

  /**
    This function copies all of the data from one account to another.

    @see https://wiki.multitheftauto.com/wiki/CopyAccountData

    @param theAccount The account you wish to copy the data to.
    @param fromAccount The account you wish to copy the data from.
  **/
  public function copyAccountData (theAccount:String, fromAccount:String):Bool; // TODO zaktualizować stringi, bo to są konta
}
```

**Comment by Gama11** [comment]
I can reproduce this with Haxe 3.4.7, but not Haxe 4 preview 4. Could you try updating?

**Comment by pawel-miczka** [comment]
Any idea how to do it with homebrew? I mean update from 3.4.7 to 4.0?

**Comment by Gama11** [comment]
I'm not sure if preview releases are available there, but I'm not a Mac user.

**Comment by commandline-be** [comment]
Same problem here, alse running 3.4.7

**Comment by fullofcaffeine** [comment]
Having the same problem on Linux (Mint 18.3). Disabling the completion cache helped, but not ideal as @pawel-miczka mentioned. I'm also using Haxe 3.4.7.

@Gama11 Since you were able to reproduce with 3.4.7, do you have any idea on what causes this?

**Comment by Gama11** [comment]
>do you have any idea on what causes this?

No.

**Comment by bary12** [comment]
Happened to me as well, my hxml file didn't have a `-main` flag, and after adding it, it started working again.
