### ISSUE TITLE
Failed to build cache (JSON-RPC problem)

### ISSUE THREAD

**Issue by Arcnor** [vshaxe/vshaxe#288]
I've been following the Flixel documentation to the letter, but when it comes to the first time opening my project (empty, from their templates, just using `flixel template -n "MyProject" -ide vscode`), I get the following error:

```
Haxe language server started
Listening on port 6000
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Failed - try fixing the error(s) and restarting the language server:

Type not found : ApplicationMain
```

My version of Haxe is 3.4.7, and I installed it (on macOS) using `brew install haxe`, not sure if that's somehow different or I need to install something else?

Searching for this error on the Internet doesn't give me any results either.

**Comment by Arcnor** [comment]
Ok, somehow I just restarted VSCode and now it seems it could build whatever it needed?

```
Haxe language server started
Listening on port 6000
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Done.
```

Still, this might be something worth fixing. Also, I still don't understand where to get Haxe with "JSON-RPC" or if that's going to affect my experience lots (I'm guessing using "--display" is just parsing the text the compiler is printing instead of some nice structured version of it?)

**Comment by Gama11** [comment]
The ApplicationMain error is an issue with the Lime extension, see https://github.com/openfl/lime-vscode-extension/issues/44. Basically, the project needs to be built at least once for the selected target for completion to work.

Regarding JSON-RPC - that requires Haxe 4 preview 4 or newer, and the overall experience should be much better with it:

https://github.com/vshaxe/vshaxe/wiki/What's-New-in-2.0.0

**Comment by Arcnor** [comment]
I see, thanks! I guess this can be closed then, not sure if the experience can be improved.

**Comment by Gama11** [comment]
It certainly can, but that's something to be implemented in the Lime extension or Lime. :)
