### ISSUE TITLE
Unresolved identifier when using import.hx

### ISSUE THREAD

**Issue by pawel-miczka** [vshaxe/vshaxe#289]
With Haxe 3.3 there is new feature that I can use import.hx file to global variables (using and import). This package still shows me Unresolved Identifier error but Haxe file still compiles properly.

**Comment by Gama11** [comment]
Can you provide more details? What does your `import.hx` look like, and what Haxe version are you using?

`import.hx` files should generally be working fine, there are several in vshaxe itself.

**Comment by pawel-miczka** [comment]
My main code looks like this:

```haxe
package src.client;

import mtasa.client.DxTexture;
import mtasa.client.Functions.showCursor;
import mtasa.client.Functions.showChat;
import mtasa.client.Functions.guiGetScreenSize;
import mtasa.client.Functions.dxDrawImage;
import mtasa.shared.Functions.addEventHandler;

class Main {
  public static function main () {
    showChat(false);
    showCursor(true);

    var screenSize = guiGetScreenSize();
    var texture = new DxTexture('static/login-button.png');
    trace(screenSize);

    addEventHandler('onClientRender', root, function () {
      dxDrawImage({x: 0, y: 0}, {x: 300, y: 60}, texture);
    });
  }
}
```

import.hx:

```hx
import mtasa.shared.Variables.root;
```

Unexpected identifier is in this line:

```hx
 addEventHandler('onClientRender', root, function () {
```

I'm using Haxe 3.4.7

**Comment by Gama11** [comment]
So that's an error from diagnostics?

Is this reproducible? Have you restarted VSCode / the language server since adding the import.hx?

**Comment by Gama11** [comment]
Feel free to reopen if you have something reproducible, but there's not much we can do with this info as is (your code snippet has external dependencies, so I can't run it).

`import.hx` is definitely supported, even with Haxe 3.4.7 and static imports. This simple example works fine:

![](https://i.imgur.com/Ql9tBJO.png)
