### ISSUE TITLE
Highlighting for non *.hx files

### ISSUE THREAD

**Issue by sh-dave** [vshaxe/vshaxe#291]
I'm currently playing with [hscript](https://github.com/haxefoundation/hscript), and i'd like to have syntax highlighting there as well. Is it already somehow possible to customize what files are considered for syntax highlighting? I started looking for it and found some `**/*.hx` pattern in `vshaxe/server/LanguageServer.hx`, but changing that to `**/*.hx*` didn't do anything for me (i call my scripts files `*.hxs`), so i guess it's the wrong code or i'm missing some other place as well.

**Comment by back2dos** [comment]
Open the command palette and use `Change Language Mode`, then `Configure File Association for '.hscricpt' ...` and then set it to Haxe ;)

**Comment by sh-dave** [comment]
Awesome, thanks!
