### ISSUE TITLE
Weird completion results

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#293]
Today I'm getting a lot of weird completion results. Here's one:

Hover is correct:

![image](https://user-images.githubusercontent.com/1022912/45428342-519c7c80-b6a1-11e8-8baa-dc075570c7ea.png)

Completion is not:

![image](https://user-images.githubusercontent.com/1022912/45428388-6ed14b00-b6a1-11e8-9d58-943610e2fc8a.png)

**Comment by Gama11** [comment]
That's not very useful without the code needed to reproduce it.

**Comment by Simn** [comment]
Try if `-D no-copt` helps :D

**Comment by Gama11** [comment]
Again, not sure what to do with this without a way to reproduce.
