### ISSUE TITLE
Vscode strange lowercase file suggestion 

### ISSUE THREAD

**Issue by djaonourside** [vshaxe/vshaxe#294]
Win 8 + vshaxe 2.4.0 + haxe 4 preview 4
Vscode finds lowercase named file that doesn’t exist.
![2018-09-04 11_21_09-dashboard hx - almreports-front - visual studio code](https://user-images.githubusercontent.com/12369638/45437811-486dd880-b6be-11e8-9d56-06a10847923b.png)

**Comment by Gama11** [comment]
There used to be some issues where vshaxe would open lowercased versions of a file via workspace symbols or goto definition. VSCode doesn't really check for that and simply adds it to the recently opened files cache. As far as I know that's no longer an issue though, try running the "File: Clear Recently Opened" command.

**Comment by djaonourside** [comment]
Running "File: Clear Recently Opened" didn't help.

**Comment by Gama11** [comment]
Hm, it should, at least temporarily.. Did you still have the lowercase version of that file open in a tab while doing so?

**Comment by djaonourside** [comment]
Yes, it still can be opened
![2018-09-13 10_51_33-dashboard hx - almreports-front - visual studio code](https://user-images.githubusercontent.com/12369638/45474770-4568fb80-b743-11e8-90ad-4cd6cbac2098.png)

**Comment by Gama11** [comment]
What I meant is that you can't have `dashboard.hx` open while clearing the recent files cache, otherwise it would just immediately get added to the cache again, I think. If that doesn't help, I'm not sure what's going on.

Either way, I don't think there's anything vshaxe can do about this, Quick Open and its cache are completely managed by VSCode.

**Comment by djaonourside** [comment]
dashboard.hx doesn't exist in the project folder only Dashboard.hx but it can be opened via Quick Open. Yep, it's possibly a vscode bug.

**Comment by Gama11** [comment]
Unfortunately, there's not much we can do here without a way to reproduce.
