### ISSUE TITLE
Auto-discovered HXML takes higher priority than settings.json

### ISSUE THREAD

**Issue by jgranick** [vshaxe/vshaxe#295]
In OpenFL, VSHaxe finds two "auto-discovered" HXML files for completion, but OpenFL also includes a settings.json to specify exactly the completion parameters that should be used when updating the library.

The workspace (as I understand) does remember which option you select, but initially, it appears to select one of the auto-discovered files first (perhaps alphabetically?)

I think completion defined in the workspace settings.json should take higher priority by default. Thank you :smile:

**Comment by Gama11** [comment]
Hm.. I remember this being an issue, but I can't reproduce it anymore - when I open a freshly cloned OpenFL repo, `scripts/completion.hxml` is selected by default. The same is true for this simple test workspace: [test.zip](https://github.com/vshaxe/vshaxe/files/2379377/test.zip)

Do you see different results?

**Comment by jgranick** [comment]
I recently re-installed Visual Studio Code, and this occurred, but perhaps (?) it's possible that it defaults differently, and this machine had residual settings to save the default as being the wrong choice.

Is there code in the plugin that decides which to favor?

**Comment by Gama11** [comment]
Not explicitly, but the default configuration index is 0:

https://github.com/vshaxe/vshaxe/blob/0876fad1b58d1fe98eb5620f4fcff5367e7a33a1/src/vshaxe/display/HaxeDisplayArgumentsProvider.hx#L143

And the list of configurations is constructed in such a way that configured ones come first, then discovered ones:

https://github.com/vshaxe/vshaxe/blob/0876fad1b58d1fe98eb5620f4fcff5367e7a33a1/src/vshaxe/display/HaxeDisplayArgumentsProvider.hx#L49-L71

**Comment by jgranick** [comment]
Okay, so perhaps this was saved somewhere. I'll comment again if this seems not to be the case, but there's a high likelihood that _I did_ use VSCode to open the OpenFL directory before, and this workspace setting might have been saved already.

Although, now that I think about it, one other question -- If a user opens a project with only auto-discovered options, and does not choose it themselves, will it save the auto-selected setting, or will it remain unsaved until they change it themselves? Might be good not to save a setting if they don't make one themselves, so if the default improves over time for a library, they benefit immediately

**Comment by Gama11** [comment]
That should already be the case, nothing is saved unless the user explicitly selects something in the UI.

**Comment by Gama11** [comment]
Hm, actually, the code doesn't seem to be making that distinction... I might be thinking of completion providers.
