### ISSUE TITLE
VSHaxe infinite loop

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#298]
I'm getting sometimes what I think are infinite loop in VSHaxe:

- one Code.exe process is taking 25% constant CPU
- haxe.exe is stalled
- `Generation...` is printed in VSCode blue bar
- Building again ask to stop generation. Doing it stop showing "Generation..." but does not kill the faulty process
- Killing it by hand then rebuilding works

Is there any way I can get more information in order to report more details about where it happens?

**Comment by ncannasse** [comment]
Erratum : building again after the process was killed did not build correctly

**Comment by Gama11** [comment]
>haxe.exe is stalled

So there's a compiler hang? Does this still happen with current Haxe versions?

**Comment by ncannasse** [comment]
Haven't got the issue lately...

**Comment by Gama11** [comment]
Let's assume it's fixed for now then until it reappears. :P

(and wouldn't it be a compiler bug anyway if haxe.exe hangs?)
