### ISSUE TITLE
There is no launch configuration named 'build.hxml'

### ISSUE THREAD

**Issue by kaefert** [vshaxe/vshaxe#299]
Hi there!

This might be a misunderstanding of a complete noob (me) to Haxe & Visual Studio Code, but I did not manage to get Visual Studio Code with the vshaxe plugin to actually compile / run the generated HelloWorld sample from within the GUI following the Getting Started guides I found.

What I did:

1.) Install Haxe on my Linux Mint 18.3 laptop using this guide: https://haxe.org/download/linux/ (which gives me Haxe version 3.4.7, sadly not Haxe 4.0.0-preview.4 which according to https://github.com/vshaxe/vshaxe/wiki/Installation works best with vshaxe..)

```
sudo add-apt-repository ppa:haxe/releases -y
sudo apt-get update
sudo apt-get install haxe -y
mkdir ~/haxelib && haxelib setup ~/haxelib
```

2.) Running this example https://code.haxe.org/category/beginner/hello-world.html (nearly identical duplicate of the guide found here: https://haxe.org/manual/introduction-hello-world.html )
`haxe -main HelloWorld --interp`

3.) Getting binaries to run on linux:

```
haxelib install hxcpp
haxe -main HelloWorld -cpp cppOut
cppOut/HelloWorld
```

4.) Download & install https://code.visualstudio.com/download (https://haxe.org/documentation/introduction/editors-and-ides.html lists it as the first IDE that runs on Linux)

5.) Open vscode, press `Ctrl+P` and enter `ext install vshaxe` (as instructed by https://github.com/vshaxe/vshaxe/wiki/Installation )

6.) Open an empty folder in Visual Studio Code, Press F1 and run `Haxe: Initialize VS Code Project` (as seen in https://github.com/vshaxe/vshaxe/wiki/Commands )

**PROBLEM 1:** The Demo for this command shows the usage of a Menu item "Tasks" between Debug & Help with a Sub-Menu-Item `Run Build Task.. F5` which does not exist for me (Visual Studio Code Version 1.27.2). Pressing `F5` gives me a Popup titled "Select Environment" with the two options "Node.js" and "More..."

7.) Use F1 command `Haxe: Select Configuration` to select the generated `build.hxml` config file (which I btw. find a very strange extension naming convention since this is clearly not xml..)

8.) Use F1 command `Haxe: Debug Selected Configuration` which I thought would have run the sample.
**PROBLEM 2:** Sadly all it does for me is show the error in the title:
> There is no launch configuration named 'build.hxml'

**Comment by Gama11** [comment]
>with a Sub-Menu-Item Run Build Task.. F5 which does not exist for me

Right, that menu was renamed to "Terminal" in a recent VSCode version. I just updated the [Tasks wiki page](https://github.com/vshaxe/vshaxe/wiki/Tasks) accordingly, try `Terminal` -> `Run Task...`. I should re-record that .gif you mentioned without custom shortcuts, `F5` is for debugging instead of tasks by default..

You don't need to run the `Haxe: Select Configuration` command if there's only one config - it's selected by default.

____

Debugging and the `Haxe: Debug Selected Configuration` is completely separate from compilation / tasks. You need a `launch.json` for that, and the target needs to support debugging. `--interp` doesn't, in Haxe 3.4.7 (although Haxe's 4 new "Eval" interpreter [does have a debugger](https://github.com/vshaxe/eval-debugger)).

For the CPP target, debugging requires this extension - there's usage instructions in the readme: https://marketplace.visualstudio.com/items?itemName=vshaxe.hxcpp-debugger

**Comment by kaefert** [comment]
Ah, nice, thank you!

So "Terminal" -> "Run Task..." makes the Sample run.
However after that Visual Studio code shows me a "Problem":
>Unable to open 'Main.hx': File not found (file:///home/kaefert/Development/Visual-Studio-Code_Haxe_workspace/One/Main.hx).

The file is found in a "src" subdir (that's how it has been generated..)

-----------------------------

About the debugging: I will take a look at that CPP extension in the next days, don't have time for it right now. Will report on my experience here afterwards.

Thank you!!

**Comment by kaefert** [comment]
This problem:
![screenshot from 2018-09-21 15-14-40](https://user-images.githubusercontent.com/1448723/45883363-26a4dd80-bdb1-11e8-9e30-b2a6afad1b3f.png)

**Comment by Gama11** [comment]
Ah. That's not exactly a "problem" / error, it just also adds traces there. I guess clicking it will indeed fail with Haxe 3.4.7 because it requires a Haxe 4 fix to map it to the file correctly.

**Comment by kaefert** [comment]
Okey, so back to the debugger:

I installed the plugin you mentioned: https://marketplace.visualstudio.com/items?itemName=vshaxe.hxcpp-debugger

I've added a second hxml file, `debug.hxml` which is a copy of the default `build.hxml` with the 4th line `--interp` replaced by `-lib hxcpp-debugger`

(which btw. in the guide of the extension reads `-lib hxcpp-debug-server` which doesn't work because there is no Haxe library called that. Visual Studio Code will repeat telling you to install it with that line in the selected hxml file.)

The step I have a problem with now is what binary to place in the launch.json config in the line 
`"program": "${workspaceRoot}/bin/yourExecutable.exe"`?

**Comment by Gama11** [comment]
`hxcpp-debugger` is not the correct lib. You don't run `haxelib install` to install it, is is packaged with the extension. From the readme:

>First, run the "HXCPP: Setup" command from the command palette (F1) to install the library.

___

>The step I have a problem with now is what binary to place in the launch.json config

Well.. the binary you get when you compile to cpp? :)

**Comment by kaefert** [comment]
> Well.. the binary you get when you compile to cpp? :)

hmmm, well that sounds like a strange concept. So I need to manually compile a binary of my app every time before I can use the debugger?

**Comment by Gama11** [comment]
Either that, or you add the task as a `preLaunchTask` for the launch config.

**Comment by Gama11** [comment]
It's simply the name of the task to run. Since in your case, the hxml is named `debug.hxml`, it should look something like this:

```json
{ 
    "version": "0.2.0",
    "configurations": [
        {
            "name": "HXCPP",
            "type": "hxcpp",
            "request": "launch",
            "program": "${workspaceRoot}/bin/application.exe",
            "preLaunchTask": "haxe: debug.hxml"
        }
    ]
}
```

**Comment by kaefert** [comment]
Beautiful! Thank you!
![screenshot from 2018-09-21 22-42-13](https://user-images.githubusercontent.com/1448723/45905157-ae114180-bdef-11e8-9026-94324cdf58e5.png)

(This question is kind of unrelated but I thought maybe I can be a little bit cheeky and ask you if you can help me with that problem too: )

https://community.haxe.org/t/static-linux-build/1079
I would like to be able to run a compiled linux binary on linux system with different (or no) GLIBCXX installed. So statically linking it. @RobDangerous told me in the forums that I need to make haxe pass the paramters `-static-libgcc` and `-static-libstdc++` to the C++ compiler, though I have not found out how to yet... Can you help me with that?

**Comment by Gama11** [comment]
Can't really help you there, never needed to modify the parameters for native C++ compilation.

**Comment by kaefert** [comment]
Okey. Still huge thanks for helping me so far! And also of course huge thanks for your contributions to this amazing project! :)
