### ISSUE TITLE
Project-wide diagnostics run

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#30]
I'd imagine a common use case for diagnostics is having them run on an entire project so you can fix all the issues at once. This is similar to what haxe-checkstyle is usually used for.

My use case is that I'd like to get rid of unused imports in Flixel code, but I don't really want to go through each file manually for that (which would be necessary right now).

Of course, this would also be helpful for debugging this feature.

**Comment by Simn** [comment]
This has been added. Probably has some problems still, but should work in principle.
