### ISSUE TITLE
Go to Definition doesn't work when types are located in different classpaths

### ISSUE THREAD

**Issue by djaonourside** [vshaxe/vshaxe#301]
![pic1](https://user-images.githubusercontent.com/12369638/47487686-917f8380-d84b-11e8-979a-c688fd8d5e2d.png)
build.hxml:
-cp src/client
-cp src/common
OperationUtil from src/client
BaseOperationData  from  src/common

**Comment by Gama11** [comment]
I don't think the classes being in separate classpaths could be the issue here, that works just fine for me. Do any errors appear in the [Haxe output channe](https://github.com/vshaxe/vshaxe/wiki/Troubleshooting)l when you invoke go to definition?

What Haxe version are you using?

**Comment by Gama11** [comment]
Can you share the project (or a trimmed-down version of it) as a .zip or something? Haven't had any luck reproducing this by replicating the project structure.

**Comment by djaonourside** [comment]
Ok, I'll try

**Comment by djaonourside** [comment]
Sorry, it was my fault. The type was dublicated in both classpaths.
