### ISSUE TITLE
Haxe: Building Cache runs forever

### ISSUE THREAD

**Issue by bluelemonade** [vshaxe/vshaxe#303]
Hi, 

the Haxe building cache runs forever, I can't get api infos.

it throwos this error wenn the Lime extension is installed:
```
Haxe language server started
Listening on port 6000
[Error - 5:18:48 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 5:18:48 PM] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Failed - try fixing the error(s) and restarting the language server:
```

regards

**Comment by commandline-be** [comment]
Same problem, haxe 3.4.7 on vscode 1.29.1 with vshaxe 1.3.0

**Comment by Gama11** [comment]
Are you sure you're on vshaxe 1.3.0? That's... really outdated: https://github.com/vshaxe/vshaxe/blob/master/CHANGELOG.md

**Comment by bluelemonade** [comment]
all tool are updates, current vsc and vshaxe 1.3.0

**Comment by fullofcaffeine** [comment]
I seem to have the same problem. It also sucks most of my CPU :/

**Comment by gusg21** [comment]
I've been having this problem as well. Latest of everything. vshaxe 2.4.5, haxe 3.4.7, vscode 1.31.0-insider

**Comment by watabou** [comment]
Any update on this one?

**Comment by RonaldTinashe** [comment]
According to a reply to @commandline-be on gitter, https://gitter.im/HaxeFoundation/haxe?at=5bf9e535cfa682348d7c1a52 , restarting the language server resolves the issue.

**Comment by Gama11** [comment]
As far as I can tell from the reports, this only happens with Haxe 3.4 and is fine with any of the recent Haxe 4 releases (Haxe 4.0.0-rc.1 for instance). Since it's likely an issue in the old compiler, we can't really fix that on the vshaxe side.

**Comment by fullofcaffeine** [comment]
But Haxe 4 is not officially released yet, shouldn't vscode support Haxe
3.x as well until 4 is out? New people coming to Haxe will probably get the
stable version, and they will probably stumble upon this issue.

**Comment by fullofcaffeine** [comment]
s/vscode/vshaxe*

**Comment by Gama11** [comment]
It does generally support it, I switch between Haxe 3.4 and latest dev all the time to test things, and completion works with either of them.

Nobody has posted any details on how to even reproduce this, but as I mentioned it sounds like an issue with the compiler, not vshaxe (there's several compiler hangs that got fixed between 3.4 and 4) - so nothing we could do on the vshaxe side anyway.

**Comment by Gama11** [comment]
(vshaxe doesn't really "do" anything for "Building Cache", it just calls Haxe to run a compilation)

**Comment by davispuh** [comment]
Having same issue with Haxe 3.4.7 on ArchLinux, it's been such a while but still doesn't appear to be fixed, same as #284

Using Haxe 4.0 works fine.

**Comment by Gama11** [comment]
@davispuh It's unlikely that there will be a fix for this, so I'd recommend sticking to Haxe 4.

**Comment by hasen6** [comment]
Same problem with Haxe 4.0.5 on OSX.

**Comment by matronator** [comment]
Yup, also having this issue on Haxe 4 and macOS. It was working for a while, but today it stopped.

**Comment by ghtalpo** [comment]
Same problem with haxe 4.1.3 on linux.

**Comment by RonaldTinashe** [comment]
Does anyone have an idea what would be the recurring cause?

**Comment by varadig** [comment]
+1 this is very frustrating.
