### ISSUE TITLE
Completion removing package

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#307]
I'm in package `ent.npc`, and I'm doing the following

![image](https://user-images.githubusercontent.com/1022912/49432745-a9ceb080-f7b0-11e8-9ef8-2c1be39cfb5a.png)

Hitting `TAB` to complete here replaces `ent.b.Level`  by `Level`, while I have disabled auto import generation.

**Comment by Gama11** [comment]
Is it actually generating an import though? Apparently it is already imported, according to the (imported) hint on the right (through an `import.hx` maybe)?

**Comment by ncannasse** [comment]
And no its not already imported since it fails to compile without the
package prefix

**Comment by ncannasse** [comment]
It's not generating an import and I don't have an import.hx defined in this
project.

**Comment by Gama11** [comment]
So the bug seems to be that Haxe reports the type as already imported.

**Comment by ncannasse** [comment]
yes. I have a (not imported) Data.hx module which defines a type Level (using CastleDB macros)

**Comment by Gama11** [comment]
>So the bug seems to be that Haxe reports the type as already imported.

In that case, this should be reported on the Haxe repo, preferably with a way to reproduce.
