### ISSUE TITLE
Error highlighting not working on macOS

### ISSUE THREAD

**Issue by fullofcaffeine** [vshaxe/vshaxe#308]
See the following screenshot, check the output drawer and the line in question: https://www.dropbox.com/s/ex8acpyeml4xgje/Screenshot%202018-12-10%2021.52.14.png?dl=0.

The ouput is showing the error Haxe found, but VSHaxe is not highlighting it in the code nor in the file browser (where the file in question should be red). 

macOS Mojave
VSCode version: 1.29.1
VSHaxe is the latest version: 2.4.5
Haxe 3.4.7 installed from the official macOS installer.

Any hints?

**Comment by Gama11** [comment]
The file appears to be unsaved? Diagnostics are updated on save.

**Comment by fullofcaffeine** [comment]
Yes, that was the problem 🤦‍♂️ 

Thanks for taking time to look into this issue!

**Comment by Gama11** [comment]
Fyi, a nice side-effect of having auto save enabled is that diagnostics also update automatically. :)
