### ISSUE TITLE
"Remove all unused imports" quick fix

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#31]
Right now, it's a bit tedious to apply the quick fix to each unused individually if there are multiple in a file.

I guess ideally, there'd be a context menu here with an entry for that, so you could do it for all warnings in a file at once (sort of works like that in IntelliJ IDEA for Java):

![](http://i.imgur.com/uFnFsPW.png)

But I suspect VSCode does not support that? I guess an easy solution would be to just have it as an additonal quick fix entry on the current file.

**Comment by Simn** [comment]
Closed by https://github.com/vshaxe/haxe-languageserver/commit/585dd42570f057b1e273b7cc335afba8af9747e3

We'll have to figure out how document versioning works exactly. I think stupid  things happen if you change the document and then apply an code action like this.
