### ISSUE TITLE
[Request] Ability to set CWD for completion HXML

### ISSUE THREAD

**Issue by jgranick** [vshaxe/vshaxe#310]
There does not appear to be a way to have a completion HXML that is not relative to the root path of a workspace. Attempting to add `--cwd` doesn't work properly with the latest Haxe 4 preview, perhaps there should be another method to set the path for completion arguments? Thanks :smile:

**Comment by Gama11** [comment]
I think this should work as expected now with the recent changes to cwd handling in vshaxe 2.10.0, which will be released soon (which also fixed #248). Let me know if that's not the case though!
