### ISSUE TITLE
Why is this written in Haxe 4?

### ISSUE THREAD

**Issue by Sunjammer** [vshaxe/vshaxe#311]
Haxe 4 is unstable/different enough to where it cannot be used for legacy projects, yet this extension is written for it. This actively prohibits contribution.

I'm all for moving to Haxe 4, but to me that seems like something you'd refactor for post RC or release, not lean on during active development of what is, from my perspective, the closest thing to a real xplat IDE the community has. What Haxe 4 features are really necessary for this extension?

**Comment by Simn** [comment]
There's a large overlap between Haxe and vshaxe devs and we like using vshaxe as a sort of test-case against regressions. It should work fine with the preview.5 release and we're gonna hit RC phase soon anyway, at which point this becomes a non-issue.
