### ISSUE TITLE
Dependency Explorer - Sub Dependencies

### ISSUE THREAD

**Issue by peteshand** [vshaxe/vshaxe#313]
Does the Dependency Explorer currently support sub dependencies of haxelibs. For example if I include 'tink_http' which itself has 4 sub dependencies (tink_anon, tink_io, tink_url, http-status) I see tink_http appear in the Dependency Explorer, but not it's sub dependencies. Is this a problem with my setup or it's simply currently not supported?

**Comment by Gama11** [comment]
Works fine for me:

![](https://i.imgur.com/bZJ1bn5.png)

Are you using lix by chance? https://github.com/lix-pm/lix.client/issues/27

**Comment by peteshand** [comment]
Hmm ok, so it must be something to do with my setup.
I'm not using lix
I am using the Lime VS extension, so maybe there is an incompatibility there

**Comment by peteshand** [comment]
Electron
