### ISSUE TITLE
Autocompletion doesn't work with macros after preview 4

### ISSUE THREAD

**Issue by ciscoheat** [vshaxe/vshaxe#315]
On 4.0.0 preview 4, autocompletion works fine for the arguments of macro functions:

![autocompletion works](https://user-images.githubusercontent.com/130450/51389551-f554d800-1b2c-11e9-9ab2-b700912c63d2.png)

But after preview 5, I've tried a couple of nightly builds, the latest 2019-01-17, it doesn't work anymore. It works fine in other places.

![autocompletion broken](https://user-images.githubusercontent.com/130450/51390294-2e8e4780-1b2f-11e9-85d9-129e34944c9e.png)

**Comment by Gama11** [comment]
This is an issue with Haxe, not vshaxe: https://github.com/HaxeFoundation/haxe/issues/7699
