### ISSUE TITLE
VScode 1.31.0 breaks tasks & launches

### ISSUE THREAD

**Issue by deepnight** [vshaxe/vshaxe#316]
I saw a quite recent commit fixing that issue (5a6bb24dff39403318713ab7a8f38b578f46edac) thanks to @Gama11 . 

Is it possible to update the extension on the marketplace? 🤔 

Thanks :)

**Comment by Gama11** [comment]
Yep, @nadako is looking into that.

**Comment by Gama11** [comment]
Vshaxe 2.5.1 should work for both 1.30 and 1.31.
