### ISSUE TITLE
Rename doesn't work correct with static extension

### ISSUE THREAD

**Issue by markknol** [vshaxe/vshaxe#318]
The actual field isn't renamed, while the function is.

![vscode-rename-staticextension](https://user-images.githubusercontent.com/576184/52944888-cd95a180-3370-11e9-949f-aec64232288e.gif)

vshaxe extension: 2.6.0
```
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393
```

**Comment by Gama11** [comment]
Rename currently isn't meant to support non-local variables / functions at all. This actually used to throw an error, but due to some Haxe 4 fixes to "goto declaration", the detection no longer works properly.
