### ISSUE TITLE
Error parsing Haxe version

### ISSUE THREAD

**Issue by gene-pavlovsky** [vshaxe/vshaxe#319]
This was reported before, but it's still happening to me. I have the latest vshaxe.
Using lix and a recent haxe nightly.
VS Code shows this error: `Error parsing Haxe version "4.0.0-rc.1+982befb24"`

```
 # haxe --run show-version
-D haxe-ver=4.0.0-rc.1+982befb24
-cp C:\usr\local\haxe/versions/982befb/std
```

**Comment by Gama11** [comment]
What's the output for `haxe --version` with lix?

**Comment by gene-pavlovsky** [comment]
Naturally it's
`4.0.0-rc.1+982befb24`

**Comment by Gama11** [comment]
Well, I'm not sure why it would have issues with parsing that _with lix only_. So there must be some difference...

The code is quite straightforward, at the end of the day it comes down to:

```haxe
~/^(\d+)\.(\d+)\.(\d+)(?:\s.*)?/.match(version);
```

Which has no issues with that string: https://try.haxe.org/#Ed217

**Comment by gene-pavlovsky** [comment]
Well it seems I'm not having that issue now - after having restarted VS Code three times. Weird?

**Comment by gene-pavlovsky** [comment]
Thanks for checking
