### ISSUE TITLE
"Remove import" should say "Remove using" for using

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#32]
Minor, but would be nice to have fixed:

![](http://i.imgur.com/SYZif1a.png)

**Comment by Simn** [comment]
I feel like changing this to `Remove line` and call it a day...

**Comment by Gama11** [comment]
Seems ok to me! But @nadako might have concerns with multiple imports / using in a single line? :P

**Comment by nadako** [comment]
Remove statement? :)
