### ISSUE TITLE
Ignore extraParams.hxml as configuration

### ISSUE THREAD

**Issue by Simn** [vshaxe/vshaxe#320]
I just opened utest in vscode and the first thing vshaxe tried to do was compiling `haxe extraParams.hxml`. I'm no friend of conventions, but given that this one comes from haxelib, I think we should just ignore extraParams.hxml.

**Comment by Gama11** [comment]
Yeah, that's also annoyed me before. I guess there's not much of a use case to have it for completion _or_ compilation, so it could probably just be hidden from the list entirely as you say..

**Comment by Gama11** [comment]
Somewhat related to #269.
