### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ConfidantCommunications** [vshaxe/vshaxe#321]
- Issue Type: `Performance`
- Extension Name: `vshaxe`
- Extension Version: `2.6.0`
- OS Version: `Darwin x64 14.5.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/allan/nadako.vshaxe-unresponsive.cpuprofile.txt` :warning:
[nadako.vshaxe-unresponsive.cpuprofile.txt](https://github.com/vshaxe/vshaxe/files/2921095/nadako.vshaxe-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by nadako** [comment]
Meh, I can't see anything useful in that profile :-/ It just says about some `Script` being executed for 3 seconds, apparently while loading the module.

In what situation did you get that? We're aware of such issues, but are seriously struggling to reproduce this...

**Comment by ConfidantCommunications** [comment]
Thanks for the response; I did not check the profile, sorry. This happened at the same time as an identical issue with vscode-live-server. Looks like they have a lot of those reported: https://github.com/ritwickdey/vscode-live-server/issues
This incident happened to me after leaving VS Code open and sleeping/restarting my Macbook. 
I have also been noticing that the "Haxe: Building Cache" message often goes forever—don't know if that helps at all.

**Comment by Gama11** [comment]
Are you using Haxe 3.4.x? https://github.com/vshaxe/vshaxe/issues/284

**Comment by Gama11** [comment]
Also https://github.com/vshaxe/vshaxe/issues/303

**Comment by ConfidantCommunications** [comment]
Yes, I'm on 3.4.7.

**Comment by Gama11** [comment]
Unfortunately, I don't think there's much we can do here without more info. As @nadako said, that CPU profile doesn't seem to be all that helpful. :(

As for the "Haxe: Building Cache" getting stuck, that seems to be a common problem with Haxe 3.4, and should go away when you update to Haxe 4.

**Comment by ConfidantCommunications** [comment]
Thanks for your attention! This is not a show-stopper for me and is not common. Carry on! :)
