### ISSUE TITLE
HaxeServerView vs. null-safety

### ISSUE THREAD

**Issue by Simn** [vshaxe/vshaxe#323]
It currently has `@:nullSafety(Off)` because I was struggling to get the constructor right:

```
src/vshaxe/view/server/HaxeServerView.hx:38: characters 66-70 : Null safety: Cannot unify vshaxe.view.server.HaxeServerView with vscode.TreeDataProvider<vshaxe.view.server.Node>
src/vshaxe/view/server/HaxeServerView.hx:39: characters 50-54 : Null safety: Cannot unify vshaxe.view.server.HaxeServerView with vscode.TreeDataProvider<vshaxe.view.server.Node>
```

**Comment by RealyUniqueName** [comment]
Most like there is a nullable field somewhere in `vscode.TreeDataProvider<vshaxe.view.server.Node>` at any level (e.g. a field of a field) and the non-nullable counterpart in vshaxe.view.server.HaxeServerView.

**Comment by Simn** [comment]
Indeed, I had a rogue question mark on a function argument.

Note that unlike https://github.com/HaxeFoundation/haxe/issues/7855, this is not about readability. It's outright missing crucial information, i.e. which field failed to unify.
