### ISSUE TITLE
HaxeServerView type-safety

### ISSUE THREAD

**Issue by Simn** [vshaxe/vshaxe#324]
There's currently code like this which isn't very haxe-idiomatic:

```
commands.executeCommand("haxe.runMethod", "server/contexts").then(function(result:Array<HaxeServerContext>)
```

I guess we need a Protocol.hx for the `runMethod` command to nicely abstract this. I'm not quite sure where to put this though.

**Comment by Gama11** [comment]
I guess we could use the already existing `LanguageServerMethods.hx` if we add `server/src` as a classpath.

**Comment by Gama11** [comment]
Actually I guess this would be more about `haxeLanguageServer.protocol.Server` (and adding the server methods there), but same difference.
