### ISSUE TITLE
Source or whatever from compiler errors is `undefined`

### ISSUE THREAD

**Issue by Simn** [vshaxe/vshaxe#326]
I have no idea about the exact terminology so here's a picture instead:

![code_2019-03-06_15-32-43](https://user-images.githubusercontent.com/634365/53893420-765d2580-402e-11e9-8f29-2e860455c354.png)

**Comment by Gama11** [comment]
This should be fixed in current Insider's builds / VSCode 1.32. I think that was a regression in VSCode 1.31 or something.

They actually re-modeled the problem hints a bit:

![](https://i.imgur.com/NonnhTn.png)
