### ISSUE TITLE
[request]can you make a haxe-cli tool for beginner use vshaxe?

### ISSUE THREAD

**Issue by sonygod** [vshaxe/vshaxe#327]
can you make a haxe-cli tool for beginner use vshaxe?

such like vue-cli ,

current from the wiki I still don't know how to create haxe project use vshaxe.

**Comment by sonygod** [comment]
what's wrong in my config? Message: Error: Multiple targets

![image](https://user-images.githubusercontent.com/748320/54009797-30779d00-41a7-11e9-8c33-06228a3a824b.png)
![image](https://user-images.githubusercontent.com/748320/54009804-37061480-41a7-11e9-966a-2918d75009d9.png)
![image](https://user-images.githubusercontent.com/748320/54009818-42f1d680-41a7-11e9-924c-f924a150cb34.png)

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/54010045-273b0000-41a8-11e9-9c7f-476e591284b7.png)

**Comment by sonygod** [comment]
oh,it's eval target.

**Comment by Gama11** [comment]
>current from the wiki I still don't know how to create haxe project use vshaxe.

It's documented here: https://github.com/vshaxe/vshaxe/wiki/Commands#haxe-initialize-vs-code-project.
