### ISSUE TITLE
Completion: list possible superclasses when triggered after extends keyword

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#330]
Consider the following code:

``` hx
package com.example;

class MyClass extends 
```

I would like to see all of the available classes when I trigger the completion list after the `extends` keyword.

**Comment by Gama11** [comment]
This already works, provided you're using a Haxe 4 preview build. In general, all code completion features are vastly superior with Haxe 4 compared to 3.4, almost nothing [listed here](https://github.com/vshaxe/vshaxe/wiki/What's-New-in-2.0.0) works with 3.4.

**Comment by joshtynjala** [comment]
Thank you. I am seeing better results from Haxe 4 rc1.

However, I found a variation of the same issue. With the following code, triggering completion with Ctrl+Space after `Spr` does not provide classes with names that start with the string "Spr":

``` hx
package com.example;
	
class MyClass extends Spr
```

The completion list contains `openfl.display.Sprite` only if nothing appears after `extends`.

I checked with variable declarations, and I see the expected classes when triggering the completion after `Spr` in the following code:

``` hx
var s:Spr
```

**Comment by Gama11** [comment]
Indeed, nice catch. That's an issue with the compiler's display API that haxe-language-server uses, so I've filed an issue there: https://github.com/HaxeFoundation/haxe/issues/8014

**Comment by Simn** [comment]
Fixed, thanks for catching that!

**Comment by joshtynjala** [comment]
Thanks for the quick turnaround. And for the project!
