### ISSUE TITLE
Function toggling labeled as "code has no effect"

### ISSUE THREAD

**Issue by Ghouly-The-Ghost** [vshaxe/vshaxe#331]
My (tested) working code is being grayed out and labeled as "code has no effect.

**Preview:**
![image](https://user-images.githubusercontent.com/29788070/54745262-537e5580-4b86-11e9-9415-e76a9825661d.png)

**Snippet**:
```haxe
var active = false;
var callback: ()->Void;  // Can't even declare it on the same line . . . (language issue)
callback = function original(){
    if( active ){ return; }
    active = true;
    // Do any sort of mutation here ( 'active = true' already is one )
    callback = function(){
        active = false;
        callback = original;
    };
};

callback();
callback();
```

*Note*: This snippet is very dirty and is a result of quickly prototyping some code.

Thanks!

**Comment by Ghouly-The-Ghost** [comment]
An ugly workaround I just found works like this:

```haxe
var callback: ()->Void;
function original() {
  ... same contents ...
}
callback = original;
```

Problem is gone, but this is the same thing.

**Comment by Simn** [comment]
That would be a Haxe issue, but we can track it here.

**Comment by Gama11** [comment]
Decided to move this issue to the Haxe repo after all: https://github.com/HaxeFoundation/haxe/issues/8359
