### ISSUE TITLE
imports displayed dimmed and completion isn't working

### ISSUE THREAD

**Issue by Dimous** [vshaxe/vshaxe#332]
It stopped working after update

**Comment by Gama11** [comment]
Going to need more infos than that. How can that be reproduced? What Haxe version do you have? Is there an error message in the output channel? (https://github.com/vshaxe/vshaxe/wiki/Troubleshooting)

**Comment by Dimous** [comment]
Haxe 4.0.0-rc.2+78b5593f5

Output:
```
Haxe language server started
Listening on port 6000
[Error - 21:37:13] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
Building Cache...
Parsing Classpaths...
[Error - 21:37:16] Request textDocument/hover failed.
  Message: This class is not available on this target
  Code: -32603 
Done.
```

**Comment by Gama11** [comment]
>This class is not available on this target

Sounds like something is being imported that shouldn't be with the currently selected target. This is probably one of the `#error` messages from the new `sys.thread` package in Haxe 4 rc 2 (https://github.com/HaxeFoundation/haxe/pull/7999).

Is the project to reproduce this public? What's your target?

**Comment by Dimous** [comment]
It is private and is multiplatform

**Comment by Simn** [comment]
Do you have something like Haxe's ImportAll.hx that browses class paths to find .hx files? Or maybe a macro which does something to that effect?

**Comment by Gama11** [comment]
Ok, but what's the platform you've _selected_ for completion?

Probably compilation fails with the same error if you try to compile the HXML you've selected.

**Comment by Dimous** [comment]
I have no ImportAll
Only macro is Safety.safeNavigation
Neko target
Code completion not compilation

**Comment by Gama11** [comment]
What are you using for code completion? Is it possible that it's a HXML file that's missing a `-neko` argument?

Those classes should be available on Neko.

**Comment by Dimous** [comment]
```
-cp source
#-main Main
-neko export/neko
-lib lime
-lib openfl
-lib safety
-lib haxe-kiwi
-lib exception
--macro Safety.safeNavigation('')
```

**Comment by Gama11** [comment]
You're using a manually written HXML file for code completion with OpenFL? Why not the [Lime extension](https://marketplace.visualstudio.com/items?itemName=openfl.lime-vscode-extension)?

**Comment by Dimous** [comment]
Thanks for the suggestion. I installed lime extension  and got rid of custom hxml.
I'll try to roll back vshaxe.

**Comment by Gama11** [comment]
>I'll try to roll back vshaxe.

That's not going to help. This is not an issue with vshaxe, but likely a combination of Haxe 4 rc2 and your project.

**Comment by Dimous** [comment]
Oh, ok. I'll investigate project changes then.

**Comment by Dimous** [comment]
Wow! My custom hxml caused this mess!

Sorry!

**Comment by Dimous** [comment]
It suddenly stopped working and I associated it with recent vshaxe update.
