### ISSUE TITLE
Disabling "method":"display/hover" completion

### ISSUE THREAD

**Issue by kiroukou** [vshaxe/vshaxe#335]
Hello,

Is it possible, or would it be possible, to disable the completion requested on hover ?

It seems we cannot force vscode to disable it, unless using the (still valid?) masked "editor.hover":false, settings.

Unfortunately, on the haxe plugin, despite this settings, the completion is requested.

**Comment by Gama11** [comment]
If requests still happen even with `"editor.hover":false`, that sounds like a VSCode bug.

**Comment by kiroukou** [comment]
yeah it seems so.  But do you think there's any way to prevent the call on the haxe plugin ?

**Comment by Gama11** [comment]
Theoretically we could have a setting. Is this really a big issue in practice though?

Is this already reported on the VSCode repo somewhere?

**Comment by Gama11** [comment]
Oh, I think you actually just used the wrong setting. It's

```json
"editor.hover.enabled": false
```

Not

```json
"editor.hover": false
```

The former works fine for me. :)

**Comment by kiroukou** [comment]
Oh my... sorry, certainly found the config in a pretty old issue .. Thanks for the clarification, it does perfectly the job.

Otherwise, the reason behind the request was a problem we currently have on the completion server, which invalidates a CastleDB file at every compilation AND completion requests...
That issue added to the permanent onver completion request was making the project an hell.
Now we can focus on the original problem with less logs and side effects !
