### ISSUE TITLE
Don't generate parenthesis in "switch" postfix completion

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#336]
Because that is unnecessary.

**Comment by Gama11** [comment]
It is, but I'd say most people still expect them to be there? Not sure, we should at least have a setting for it though.

**Comment by kevinresol** [comment]
I suppose if that is the case then they should be educated.

**Comment by back2dos** [comment]
Related question: to what degree are all these code generators customizable?

**Comment by Gama11** [comment]
To whatever degree the `"haxe.codeGeneration"` struct in the settings allows. Are you looking for something specific?

Regarding code style, we might simply use the workspace's `hxformat.json` for generated code at some point. This wouldn't include stuff like parens though, haxe-formatter doesn't add or remove any tokens.

For postfix completion, I definitely want to have a setting that allows contributing custom items, see #231.

**Comment by back2dos** [comment]
Oh, nothing specific, just a general question. I was just wondering if there are perhaps some templates one can edit, as you can in FD - and indeed the `insertText` in #231 is a type of template, if you will ^^.

**Comment by Gama11** [comment]
You can't really mess with the built-in snippets right now, but VSCode lets you define your own:

https://code.visualstudio.com/docs/editor/userdefinedsnippets

I don't think you'll be able to make those context-sensitive as the ones built into vshaxe are though.
