### ISSUE TITLE
vshaxe build error

### ISSUE THREAD

**Issue by nabezokodaikon** [vshaxe/vshaxe#338]
An error occurs when building with my vshaxe.

I used Mac.
Haxe version 4.00-rc.2

Reference
[Installation#from-source](https://github.com/vshaxe/vshaxe/wiki/Installation#from-source.)

Error
```
Updating json-rpc version git ...
/Users/nabezokodaikon/workspace/develop/vshaxe/vscode-extern/src/import.hx:2: characters 8-20 : Type not found : js.lib.Error
'haxe -lib hxnodejs -lib jstack -lib json-rpc -cp vscode-extern/src -cp server/src -cp server/protocol/src -cp src -cp src-api -D analyzer-optimize -D js-enums-as-arrays -D js-es=6 -D js_unflatten -D JSTACK_MAIN=vshaxe.Main.main -D JSTACK_ASYNC_ENTRY -D JSTACK_NO_SHUTDOWN -dce full -debug --macro nullSafety('vshaxe') -js bin/client.js vshaxe.Main' exited with 1
```

**Comment by Gama11** [comment]
vshaxe depends on a nightly build of Haxe after https://github.com/HaxeFoundation/haxe/commit/88e519536951213b16b3d7cb3ff510070fb07c29. You can get nightly builds here: http://build.haxe.org/

**Comment by nabezokodaikon** [comment]
thanks!

**Comment by Gama11** [comment]
I added a note about this to the "installing from source" instructions, as you're not the first one to run into this.
