### ISSUE TITLE
Conditional breakpoints not working with eval-debugger

### ISSUE THREAD

**Issue by fullofcaffeine** [vshaxe/vshaxe#342]
### Steps to reproduce:

1) Correctly configure your [launch.json](https://github.com/fullofcaffeine/pwa-ts-haxe-sample/blob/master/.vscode/launch.json) with the eval target;
2) Create a conditional breakpoint somewhere where eval can pick it up (any macro context, AFAIK), to make things simpler for this scenario, we'll add a `false` as the condition, meaning that when triggering the eval debugger, it __should not__ stop at it.
3) Start the debugging session;
4) The debugger stops at the aforementioned breakpoint.

### Version info:
* Linux Mint `18.3`;
* Haxe version: `Haxe 4.0.0-rc.2+77068e1 through Lix`;
* Lix version: `15.3.12`;
* vscode version: `1.33.1 (linux mint)`;
* vshaxe version: `2.9.2`.

__Also reported on the Haxe Gitter channel, see full transcript [here](https://www.pastiebin.com/5cc74a08158d6).__

**Comment by Simn** [comment]
Assuming vshaxe sends this correctly, this is a Haxe issue.

**Comment by fullofcaffeine** [comment]
Actually, if it's related to eval-debugger, I should probably have created it in `eval-debugger` extension's repo. Sorry @Gama11, let me know if it's okay to leave it here or if I should report it there.

@Simn I cross-posted this issue in the Haxe repo. Feel free to close it if it's not Haxe related, or @Gama11, close this one if it's not related to vshaxe/eval-debugger extensions.

Thanks!

**Comment by Simn** [comment]
Fixed in Haxe
