### ISSUE TITLE
Compiler query queue

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#344]
Today I noticed that the compiler was hanging while compiling. I killed it once then restarted vscode. it happened again soon after that and I look at the log.

VSHaxe was doing like 20-30 display query which was locking compilation. Because the server cache was not built, each request took ~4s to complete. I waited and eventually the compilation happened.

I suggest introducing a compiler query queue:
- when a query (display/compilation/etc.) is made, sent it to the compiler
- when the compiler is busy, queue the query until you get previous query result
- when a display query is added to the queue, discard any previous display query

**Comment by Gama11** [comment]
I don't think we should just randomly discard requests, there's already a mechanism in the LSP to cancel on-going requests. This should for instance happen when you hover over something and quickly move the cursor somewhere else again. So I'm actually wondering how you managed to queue up that many requests, that should be investigated in more detail.

What me could maybe do is give compilation requests priority over display requests.

**Comment by ncannasse** [comment]
What about writing code with lots of . and ( while the compiler is busy ?

**Comment by nadako** [comment]
They should be cancelled before they go into the compiler.

**Comment by ncannasse** [comment]
I confirm that there is an issue when typing code while cache is not build. After typing for some time I see that the compiler (and vshaxe) is busy executing many queue display queries.

**Comment by Gama11** [comment]
Fyi, you can visualize the request queue in the Haxe methods view.

```json
"haxe.enableServerView": true
```

![](https://i.imgur.com/BBh2MYa.png)

**Comment by ncannasse** [comment]
Oh I didn't knew this one :) will try to use it next time I have an issue

**Comment by ncannasse** [comment]
I tried it today, and I'm getting errors. They are in french but they say "the element with id >display/signatureHelp is already subcribed"

```
notificationsAlerts.ts:38 Error: L'élément avec l'id >display/signatureHelp est déjà inscrit
	at p.createAndRegisterTreeNode (c:\Users\Nico\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:466:509)
	at define.fetchChildrenNodes.a.asPromise.then.Promise.all.u.coalesce.map.a.asPromise.then.n (c:\Users\Nico\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:465:169)
```

Which is in line with what I'm experiencing : display requests get stacked and are not canceled.

**Comment by ncannasse** [comment]
I have to say that given the reproductibility and annoying level of the problem, I think it's been triggered by a recent change in either VSCode or VSHaxe.

**Comment by Gama11** [comment]
Are you working without a completion cache that often? I try to avoid that as much as I can.

**Comment by ncannasse** [comment]
Sadly I often don't have the choice... Switch projects and changing
libraries.

**Comment by Gama11** [comment]
>"the element with id >display/signatureHelp is already subcribed"

Hm, yeah, the tree view not even being able to handle our queue is already not a good sign... :D I've fixed that part at least, but it seems that there might indeed be something wrong with canceling requests.

**Comment by Gama11** [comment]
Argh, looks like cancelation tokens aren't being passed through at all anymore ever since I extracted json-rpc handling into a separate repo. :(

**Comment by nadako** [comment]
OMG :)

**Comment by Gama11** [comment]
`HaxeServer.hx` or anything related to it is better never touched again, given how much test coverage we have...
