### ISSUE TITLE
Auto-Import isn't inserting in the correct location

### ISSUE THREAD

**Issue by Jarrio** [vshaxe/vshaxe#347]
```haxe
package;

@:jsRequire('WebSocket')
extern class WebSocket {
	public function new(url:String):Void;
	public function on(event:SocketEvent, callback:Function):Void
}
```
![gif](https://user-images.githubusercontent.com/748557/58058537-428b9980-7b61-11e9-9dd5-18422d95db16.gif)

It appears like once something has been imported, all imports after are inserted as expected

**Comment by Gama11** [comment]
Note to myself: maybe I'm accidentally using `getPos()` instead of `getTreePos()`.
