### ISSUE TITLE
Add a "Remove unused variable" quick fix

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#35]
Now that unused variables are being reported, being able to remove them with a quick-fix like we have for imports would be nice.

**Comment by Simn** [comment]
Not so easy in cases like `var unused, notUnused`, but I'll take a look on the Haxe side.

**Comment by Gama11** [comment]
Also regarding the whole "init with sideeffects" thing.

**Comment by Simn** [comment]
This works now for the two straightforward cases:

```haxe
var x;
var y = e;
```

I'm not gonna bother thinking about the `var x, y` scenario because that gets quite stupid. There are cases like `var x = sideEffect(), usedY` where there's no obvious transformation.

**Comment by Gama11** [comment]
Fair enough. I don't think `var x, y` is used very often anyway. :)

**Comment by Gama11** [comment]
Shouldn't the whole line be removed with `var y = noSideEffect`?

![](http://i.imgur.com/JTbJ140.gif)

**Comment by Simn** [comment]
If there's nothing else on that line, sure. You're the only one who knows the secret technique of full line removal though.

**Comment by Gama11** [comment]
How so? @nadako changed the "remove unused import" to remove the full line, not me. :)

**Comment by nadako** [comment]
:) it was not about full lines, but about trailing newlines when there's nothing but whitespace left

**Comment by Gama11** [comment]
Actually, this seems like more of a Haxe problem, with it not reporting `DKRemovableCode` with a removable range sometimes (https://github.com/HaxeFoundation/haxe/issues/7294).
