### ISSUE TITLE
LSP textEdit missing range

### ISSUE THREAD

**Issue by Jumblemuddle** [vshaxe/vshaxe#350]
It seems the completion response from the LSP server isn't compliant with the spec.
[textEdit](https://microsoft.github.io/language-server-protocol/specification#textedit) is missing `range`.

See https://github.com/ul/kak-lsp/issues/204

**Comment by Jumblemuddle** [comment]
```
    {
      "label": "charAt",
      "kind": 2,
      "detail": "public function charAt(index:Int):String",
      "textEdit": {
        "newText": "charAt"
      },
      "documentation": null,
      "sortText": "0000000001",
      "data": {
        "origin": 0,
        "index": 0
      }
    }
```

**Comment by Jumblemuddle** [comment]
```
import Sys;

class Main {
  static public function main(): Void {
    "asdf".|
    trace("asdf");
    Sys.exit(1);
  }
}
```

**Comment by Gama11** [comment]
@klabz I guess this is the same issue you had to solve for Neovim compatibility?

**Comment by kLabz** [comment]
Yep, I have to use this (originally made by @jdonaldson):
https://github.com/kLabz/haxe-languageserver/commit/29ca6cfe0df77f48c5724013ecd3b04f3043840c

**Comment by Jumblemuddle** [comment]
That got me further at least, thanks!

**Comment by Jumblemuddle** [comment]
If anyone here could take a look at https://github.com/ul/kak-lsp/issues/206, that'd be great. I think I'm just running into some non-standard LSP features used by Haxe. Maybe some of you know of settings I could use to disable these features.

**Comment by Gama11** [comment]
That's not a non-standard feature. The `label` of a completion item can be different from the text that is inserted when you select it.
