### ISSUE TITLE
LSP Can't complete snippet by name

### ISSUE THREAD

**Issue by Jumblemuddle** [vshaxe/vshaxe#351]
There are several snippets that show up in completions, however once I start typing the name of one, only methods are completed.
This is using [Emacs LSP](https://github.com/emacs-lsp/lsp-mode), and it looks like the filtering it happening on the server side.
![scrot](https://user-images.githubusercontent.com/3629343/58751910-32ca5a00-846b-11e9-98e6-c467530c01fb.gif)

**Comment by Gama11** [comment]
There is no server-side filtering. This sounds like an issue with the Emacs LSP implementation.

**Comment by Jumblemuddle** [comment]
Alright, thanks :)
