### ISSUE TITLE
Auto Import failing, thinks class is already imported

### ISSUE THREAD

**Issue by basro** [vshaxe/vshaxe#355]
![image](https://user-images.githubusercontent.com/1387293/58973585-b26f6600-8796-11e9-9474-30f4dfe63df7.png)

For some reason autocomplete thinks anything under the "test" package is already imported so it fails to create the import line for Class B which is in a different package.

**Comment by basro** [comment]
I'm using Haxe 4.0.0 rc2

**Comment by Gama11** [comment]
This information comes directly from Haxe via the display protocol, so I'm moving the issue there: https://github.com/HaxeFoundation/haxe/issues/8436.

**Comment by Gama11** [comment]
Looks like it's already been fixed. :) https://github.com/HaxeFoundation/haxe/commit/2a5ec347f3c500937ad470784c871f7505f4ca27

**Comment by basro** [comment]
Great 👍
