### ISSUE TITLE
Multi line errors are reported twice

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#356]
When a line is too long for terminal, vshaxe can reassemble it so we get the full message. But the original (truncated) output is still displayed. Here's an example with a Warning:

![image](https://user-images.githubusercontent.com/1022912/59028403-d6e14600-885b-11e9-88b3-9681734fd030.png)

And the corresponding terminal output:

![image](https://user-images.githubusercontent.com/1022912/59028494-f6786e80-885b-11e9-8995-c136e08f2115.png)

**Comment by Gama11** [comment]
I think this is a duplicate of https://github.com/vshaxe/vshaxe/issues/137?

**Comment by ncannasse** [comment]
Not exactly. I think we used to have the regexp that matched the warning. Now there's two outputs in Problems for each cutout line: one with the full warning correctly merged and one with the first line only.

**Comment by Gama11** [comment]
Well, as far as I can tell, it's still the same underlying issue: problem matching depending on the terminal width. Maybe the symptoms changed a bit due to changes on VSCode's end, but nothing changed in vshaxe. I'll close the other issue then.

**Comment by ncannasse** [comment]
I think this is quite specific and more of a consequence of #137 than a problem in itself. Closing this one and reopening #137
