### ISSUE TITLE
Go to definition displays error when activated for call to trace()

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#358]
Hold down <kbd>Ctrl</kbd> and hover over a call to `trace()`.

The following appears in the Output log for Haxe.

```
[Error - 11:57:53 AM] Request textDocument/definition failed.
  Message: Unsupported method
  Code: -32603 
```

vshaxe 2.13.3
Haxe 4.0.0-rc.3

**Comment by joshtynjala** [comment]
Possibly related, hold down <kbd>Ctrl</kbd> and hover over a `var` or `function` keyword:

```
[Error - 12:05:53 PM] Request textDocument/definition failed.
  Message: (name : jsonrpc.NotificationMethod<Unknown<0>>, ?params : Null<Unknown<0>>) -> Void should be jsonrpc.NotificationMethod<jsonrpc.NoData> -> Void
  Code: -32603 
[Error - 12:05:53 PM] Request textDocument/hover failed.
  Message: (name : jsonrpc.NotificationMethod<Unknown<0>>, ?params : Null<Unknown<0>>) -> Void should be jsonrpc.NotificationMethod<jsonrpc.NoData> -> Void
  Code: -32603 
```

**Comment by joshtynjala** [comment]
Sometimes, I get this for `var` and `function` instead:

```
[Error - 12:08:22 PM] Request textDocument/definition failed.
  Message: Error: No completion point was found
  Code: -32603 
[Error - 12:08:22 PM] Request textDocument/hover failed.
  Message: Error: No completion point was found
  Code: -32603 
```

**Comment by Gama11** [comment]
I'm not sure there's any bug here / what you'd expect to happen instead. `var` and `function` are keywords, so they don't have a declaration.

`trace` not reporting a declaration may actually be by design if I recall correctly. While there is a declaration in `haxe.Log.trace`, that's just the default implementation that can be overriden dynamically. So if it always took you to that one, that might be a bit confusing.

**Comment by joshtynjala** [comment]
Certainly, I understand that language keywords, and other things like that, might not have any results from hover or definition requests.

However, users should not be seeing error messages when there's nothing wrong. It looks like the extension is broken in some way, even if it's providing otherwise correct results.

**Comment by Gama11** [comment]
Why, where do you show these messages?

The way it's set up in VSCode with the Haxe output channel, that's more of a debugging tool / log you normally don't look at anyway. And if you do for instance expect goto declaration to work on `trace`, something like "Unsupported method" being printed is nice so it doesn't just fail silently.

**Comment by joshtynjala** [comment]
The difference here is that the method being called **is** supported. The language server should be returning whatever the correct empty result is for the request, rather than throwing an error. If something actually went wrong, then by all means, have it fail with an error and display it exactly where it's being displayed.

**Comment by Gama11** [comment]
Hm, so the correct response would technically be `resolve(null)` then instead of `reject`? We're probably doing this wrong for quite a few requests then.

I don't think there's much we can do about it on the language server side either, it just passes on what Haxe returns. Haxe would send us an error both for "no result" cases like trace and actual exceptions, so we can't really differentiate it. The error originates here in the compiler: https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typerDisplay.ml#L470

**Comment by joshtynjala** [comment]
> Hm, so the correct response would technically be resolve(null) then instead of reject?

Yeah, that's probably what you need to do. The spec mentions what types are allowed as return values for each request. It looks like most requests can safely return a null value as a response.

That being said, when I originally implemented the ActionScript language server, I found that I had to return non-null values in some cases. However, that was a while back, and null may be handled better now. It's quite possible that my problems with null results was because the lsp4j library or an earlier version of VSCode that didn't follow the spec closely enough. Or maybe the spec was not as clear about null being allowed back then.

**Comment by Gama11** [comment]
This should largely be ok with latest Haxe dev now (though it's possible I overlooked some edge cases).

**Comment by joshtynjala** [comment]
@Gama11 Thank you! I'll let you know if I run into any edge cases.

**Comment by joshtynjala** [comment]
@Gama11 I confirm that the "unsupported method" errors are no longer present. I'm still seeing this one, though:

```
[Error - 12:08:22 PM] Request textDocument/definition failed.
  Message: Error: No completion point was found
  Code: -32603 
[Error - 12:08:22 PM] Request textDocument/hover failed.
  Message: Error: No completion point was found
  Code: -32603 
```

**Comment by Gama11** [comment]
Need some reproducible example for that.

**Comment by joshtynjala** [comment]
Okay, I'll get back to you with an example when I have a chance.

**Comment by joshtynjala** [comment]
@Gama11 Sorry for the delay getting back to you! Here's how I can reproduce very easily.

I created a file named `NewClass.hx` with this code:

```hx
class NewClass {
	public function new() {
		trace("hi");
	}
}
```

If I hover my mouse over `class`, `public`, or `function`, I see in the Haxe output console:

```
[Error - 12:03:31 PM] Request textDocument/hover failed.
  Message: Error: No completion point was found
  Code: -32603 
```

Actually, I can get it to happen over some of the brackets too.

If I hover over names like `NewClass`, `new`, or `trace`, I get a proper hover popup.

Same problem when I press the Ctrl key for textDocument/definition.

Using VSCode with vshaxe extension 2.13.4, Lime extension 1.3.1, Haxe 4.0.0-rc.3.

**Comment by Gama11** [comment]
Only Haxe versions newer than rc.3 have these changes.

**Comment by joshtynjala** [comment]
@Gama11 I'm not sure what you are referring to when you say "these changes". Are you saying that these error messages were fixed in Haxe after rc.3 was released?

**Comment by Gama11** [comment]
Yeah, see the commits referenced in this issue.

**Comment by joshtynjala** [comment]
Okay, I'll let you know if I still have problems when the next rc comes out. Sorry for the noise.
