### ISSUE TITLE
Folding markers for conditionals

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#36]
Currently there are no folding markers for `#if x ... #end`

**Comment by nadako** [comment]
I guess we have to wait for https://github.com/Microsoft/vscode/issues/3422

**Comment by Gama11** [comment]
This should be possible with the folding API added in 1.22.

**Comment by Gama11** [comment]
This is now finally supported with our custom folding range implementation. \o/

![](https://i.imgur.com/N7jWJJr.gif)
