### ISSUE TITLE
Language server: Populate package name in workspace symbols, if available

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#362]
The LSP `workspace/symbol` request returns an array of `SymbolInformation` objects:

https://microsoft.github.io/language-server-protocol/specification#workspace_symbol

`SymbolInformation` has an optional field named `containerName`. It would be nice if this field were used for the package name when a symbol is a class or interface.

The Java and AS3 language servers provide the package name like this, and it's handy.

**Comment by Gama11** [comment]
It looks like we already use that for the file path of the class, which arguably carries even more information than the package:

![](https://i.imgur.com/yGwvJs4.png)

**Comment by joshtynjala** [comment]
@Gama11 Are you sure that's not just the fallback that VSCode displays when the `containerName` is empty? I'm paused in the debugger, and the results that I'm seeing from the Haxe language server does not have the `containerName` field populated. The only fields that I'm seeing on these objects are `kind`, `location`, and `name`.

**Comment by Gama11** [comment]
Ah, that's possible.

**Comment by nadako** [comment]
Note that for "secondary" module types it would be nice to also show the module name, not just the package.

**Comment by Gama11** [comment]
With latest Haxe dev it now looks like this:

![](https://i.imgur.com/9CRJPzD.png)

The `-- <FileName>.hx` at the end seems a bit redundant, but that's not avoidable I think / added by VSCode.
