### ISSUE TITLE
HL Debugging using active configuration ?

### ISSUE THREAD

**Issue by melMass** [vshaxe/vshaxe#363]
I'm a bit lost on the configurations for VSHaxe.

I'm having multiple configuration files that I'm switching to.
But I can't find any information in either the HLDebugger repo or this repo's wiki.

Here is my launch.json file:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "HashLink (HL)",
			"request": "launch",
			"type": "hl",
			"cwd": "${workspaceRoot}",
			"hxml": "active configuration",
			"preLaunchTask": {
			 	"type" : "haxe",
			 	"args" : "active configuration"
			 }
		},
    ]
}
```

**Comment by Gama11** [comment]
I'm not sure what you're asking here.

**Comment by melMass** [comment]
Sorry If it was unclear. I'm trying to use a launch.json suited for multiconfiguration files and the HL Debugger.

Here is a sample of one of my hxml:
```bash
-cp src
-lib heaps
-lib hxmtb 
-lib hlsdl

-hl out/hl/Mel.hl
-D resourcesPath=res
-main Mel

-cmd hl out/hl/Mel.hl 

```

If I use `haxe-eval` : 
```json
"name": "HashLink (Eval)",
"request": "launch",
"type": "haxe-eval",
"cwd": "${workspaceRoot}",
"preLaunchTask": {
	"type" : "haxe",
	"args" : "active configuration"
	}
```
It runs the program twice, debugging starting on the second instance.

So I tried to adapt that config to the HL Debugger instead, using the configuration in my first post, which I know is wrong because HL excepts a specific `hxml`. I'm not sure how to use the active configuration.

Hope its more clear.

Thanks

**Comment by Gama11** [comment]
>but it runs twice, debugging starting on the second instance.

Yeah, you'd have to remove that `-cmd` from the HXML.

>I'm not sure how to use the active configuration.

Can't you just use the HXML's file name? Do you have multiple different HXML files for HL?

**Comment by melMass** [comment]
Yes I have tried removing the cmd, then it just don't run at all.

The idea is to actually use the active configuration one. 

We use monorepo for our dev libraries and CLI tools so we do have many hxml for HL

**Comment by Gama11** [comment]
It's not necessarily meant to "run" with `haxe-eval`, that's for debugging macros at compile time.

There's no way to specify `hxml` as "active configuration" with the HL debugger. There are plans to make the `hxml` property obsolete anyway: https://github.com/vshaxe/hashlink-debugger/issues/4

**Comment by melMass** [comment]
Well reading vshaxe/hashlink-debugger#4 and #221 It seems like exactly it. As they are pretty old any news about it.

Thanks for your time

**Comment by Gama11** [comment]
Nope, not really any news about it. I guess this can be closed in favor of those issues then.
