### ISSUE TITLE
Can't get getter value

### ISSUE THREAD

**Issue by RogerPaladin** [vshaxe/vshaxe#365]
In project i use openfl + starling framework. When i debug there is no value in getter property
![6408946b](https://user-images.githubusercontent.com/847782/62321221-d4414c80-b4aa-11e9-8699-ec08582bdfb0.png)

**Comment by Simn** [comment]
Please provide a self-contained example that doesn't depend on external libraries.

**Comment by Gama11** [comment]
Also, is this about hover during debugging? Then this is the wrong repo for the issue report.

**Comment by RogerPaladin** [comment]
> Also, is this about hover during debugging? Then this is the wrong repo for the issue report.

Yes, this is hover over debug. 

> 
> 
> Please provide a self-contained example that doesn't depend on external libraries.

```
package;

class Main
{
    public function new() 
    {

    }
    public static function main()
    {
        var testClass: TestClass = new TestClass();
        testClass.x = 20;

        trace(testClass.x);
    }
}
```

```
package;

class TestClass
{
    private var _x: Int = 0;

    public var x(get, set):Int;

    public function new()
    {

    }

    function get_x() {
        return this._x;
    }

    function set_x(x) {
        return this._x = x;
    }
}
```
testClass.x - could not be evaluated

**Comment by Gama11** [comment]
>Yes, this is hover over debug.

Which target / debugger?

**Comment by RogerPaladin** [comment]
> 
> 
> Which target / debugger?

Haxe Interpreter / haxe-eval

**Comment by Gama11** [comment]
That would make this a Haxe issue: https://github.com/HaxeFoundation/haxe/issues/8599
