### ISSUE TITLE
Can't find Haxe exec in PATH using VSC Flatpak

### ISSUE THREAD

**Issue by DanMan** [vshaxe/vshaxe#367]
I'm using the Flatpak version of [VSCode OSS](https://flathub.org/apps/details/com.visualstudio.code.oss) on Fedora 30 and your plugin doesn't seem to find the executable. It keeps complaining about it when I launch VSC. Haxe 3.4.7 has been installed from the Fedora repo and works fine from a system terminal.

I've tried configuring the `haxe.executable` setting, and even if I use the actual path `/usr/bin/haxe` it doesn't work. I'm posting this here because other extensions like the [Mercurial](https://github.com/KristjanTammekivi/vscode-hg) one do work with my system (`hg`) executable, for example. So any idea what's wrong?

P.S.: Typing `hg` in the VSC console works, typing `haxe` doesn't.

**Comment by Gama11** [comment]
>P.S.: Typing `hg` in the VSC console works, typing `haxe` doesn't.

Not sure what could cause that (maybe VSCode is started with the wrong environment?), but then it doesn't seem particularly surprising that the plugin wouldn't be able to find it either.

**Comment by DanMan** [comment]
Someone else with a similar problem: https://github.com/flathub/com.visualstudio.code/issues/44

It's weird that `hg` works. But it appears that the one I've installed is even more sandboxed: https://github.com/flathub/com.visualstudio.code.oss/blob/master/com.visualstudio.code.oss.json

A lot of stuff in there, so that might be it.

**Comment by DanMan** [comment]
That said, if we could define `flatpak-spawn --host haxe` as the executable, that could solve the problem. But it currently wants a path, so it doesn't work.

**Comment by Gama11** [comment]
You could probably create a `.sh` file that runs `flatpak-spawn --host haxe` and then specify the path to the `.sh` file as the haxe executable.

**Comment by DanMan** [comment]
Indeed! Progress! But now I get:

`Error parsing Haxe version "Haxe Compiler 3.4.7 - (C)2005-2017 Haxe Foundation\n Usage : haxe -main <class> [-swf|-js|-neko|-php|-cpp|-cppia|-as3|-cs|-java|-python|-hl|-lua] <output> [options]\n Options :"`…

**Comment by Gama11** [comment]
Sounds like the script is not passing on arguments like `-version` to Haxe.

**Comment by DanMan** [comment]
Doh… right. `flatpak-spawn --host haxe $*` did the trick. Now it's busy with "Haxe: Building Cache…". Is it normal for that to take a long time?

**Comment by Gama11** [comment]
No, that should be fairly quick. Maybe there's something in the output channel: https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

**Comment by DanMan** [comment]
I get this with verbose display server logging:

> Error parsing diagnostics response: SyntaxError: Unexpected token I in JSON at position 0
> Processing Arguments [--display,{"jsonrpc":"2.0","id":2,"method":"initialize","params":{"supportsResolve":true,"exclude":["zpp_nape"]}}]
> Error: Invalid format: {"jsonrpc":"2.0","id":2,"method":"initialize","params":{"supportsResolve":true,"exclude":["zpp_nape"]}}

Btw. thanks for the help.

**Comment by DanMan** [comment]
It seems like the caching went through once the code didn't have errors anymore. It now seems to basically work.
