### ISSUE TITLE
Display config in status bar only shows after the first opened .hx file

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#37]
How to reproduce:

- open a vscode workspace without any tabs open
- open a .hx file - no status bar UI shows up yet
- open a second .hx file - now the UI is here, and it stays even when switching to the other file

The UI should be visible right away for the first .hx file that is opened.

**Comment by Gama11** [comment]
Note: looks like the second file that's opened doesn't actually have to be a .hx file, the tab switch seems to be what makes it work.

**Comment by Gama11** [comment]
The global diagnostics check also doesn't seem to work before the UI is shown.

**Comment by nadako** [comment]
can't reproduce that...

**Comment by Gama11** [comment]
Hm, really? So the status bar item shows up _right away_ for you? Here's how it looks like for me, keep an eye on the status bar:

![](http://i.imgur.com/5YrQ7QN.gif)

**Comment by nadako** [comment]
weird... and no issues in the dev console?

**Comment by Gama11** [comment]
Not that I can see... @Simn, you have this issue as well, right?

**Comment by Simn** [comment]
I just tried again and I can indeed reproduce it.

**Comment by nadako** [comment]
Reproduces. I guess i was high or something and did it wrong.
