### ISSUE TITLE
Lime and project.xml: Dependencies refusing to update

### ISSUE THREAD

**Issue by olichose123** [vshaxe/vshaxe#372]
Everytime I add an haxelib to my project.xml, I have to close the workspace and add a new folder for the refresh to the dependencies to work correctly. Refreshing manually does not work, and vscode of course shows problems where the specific lib code is used, but the compilation works correctly, indicating that it might be a vshaxe problem, not a haxe problem. Anybody has seen something similar?

<?xml version="1.0" encoding="utf-8"?>
<project>
	
	<meta title="Game" package="dev.test.game" version="0.0.1" company="me" />
	<app main="dev.test.game.Main" path="export" file="game" />
	
	<source path="src" />
	<source path="../framework/src" />
	
	<haxelib name="openfl"/>
	<haxelib name="hxmath"/>
	<haxelib name="hscript"/>
	<haxelib name="yaml"/>
	<haxelib name="seedyrng"/>
	<haxelib name="Pathfinder"/>
	
	<assets path="assets"/>
	
</project>

In this specific case, every lib added did not update correctly without closing the workspace and re-adding the code folder back into vscode. Simply closing vscode had no effect, nor did the refresh button on the dependencies tab.

**Comment by Gama11** [comment]
This is something the lime extension would need to handle. See https://github.com/openfl/lime-vscode-extension/issues/12.
