### ISSUE TITLE
"is" showing at first place

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#374]
![image](https://user-images.githubusercontent.com/1022912/63956450-b73a7200-ca86-11e9-9bcb-50bf6ac9e403.png)

`Std.is` completion should be last, and if vscode does not allow it, we should be able to disable these shortcuts.

**Comment by Gama11** [comment]
There already is a setting:

```json
"haxe.postfixCompletion": {
	"level": "filtered"
}
```

I don't think it's really avoidable in this case that `is` shows first, it's an exact match for the filter string.

**Comment by ncannasse** [comment]
I am the only one annoyed by that and should it not be disabled by default?

Le jeu. 29 août 2019 à 18:13, Jens Fischer <notifications@github.com> a
écrit :

**Comment by Gama11** [comment]
Can't really recall any complaints. It's not like it stays at the top, after typing just one more character it#s sorted to the bottom again.
