### ISSUE TITLE
Code gets messed up from time to time when formatting

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#376]
I wish I had a consistently reproducible example to explain the issue, but it seems pretty random.

I have enabled `editor.formatOnSave` in my settings, which, so far works for most of the cases, that's nice, but it happens regularly that the code is messed up.

For instance, I just typed this in my haxe file:

```haxe
var something = 2;
```

Then after saving it could become something like:

```haxe
var msoingthe = 2;
```

Doing CTRL+Z to "cancel" the mess-up and saving again reproduces the same glitch.
I usually have to rewrite the line, or copy and paste a big portion of code to make it work fine again.

Can't say if this is an issue with vshaxe directly or haxe formatter library, but I didn't have any problem running formatter from command line so far.

**Comment by Gama11** [comment]
For what it's worth, this is sort of a known issue, but as you said very hard to reproduce and thus really hard to debug.

Currently the best guess is that the language server must somehow get to a state where the document looks different in its internal cache than it does on disk. The language server applies the file change events "incrementally" to update its document cache.

**Comment by Gama11** [comment]
I don't think it's specific to `formatOnSave` btw, should happen during a regular "Format Document" as well.

**Comment by melMass** [comment]
I spend the last 2hours thinking I was crazy !! 
Good to know it's a known issue, is the issue a bit more precise now ?

**Comment by jeremyfa** [comment]
I had to disable automatic formatting on save at the moment because it was really happening to often. It seems that copying/pasting code and saving a lot in between makes the issue reproduce pretty often, if that can help?

**Comment by AlexHaxe** [comment]
I've seen that issue a handful of times, but never in a reproducible way. 

Current workaround: undo format, run command `File: Save without Formatting`, close file and open again.

**Comment by Gama11** [comment]
Should be fixed in 2.19.3 thanks to @jakub-w. :)
