### ISSUE TITLE
Haxe 4.0.0-rc.4 link is targeting Haxe 4.0.0-rc.2

### ISSUE THREAD

**Issue by Adolio** [vshaxe/vshaxe#377]
Hello,

A minor issue in the extension page in VSCode:

![Screen Shot 09-10-19 at 01 03 PM](https://user-images.githubusercontent.com/1126990/64608695-897cf380-d3cb-11e9-9adf-b7a7ec1daa59.PNG)

Best,
Aurélien

**Comment by Gama11** [comment]
Thanks!
