### ISSUE TITLE
Code generation is executed on auto-complete if hxml contains --next

### ISSUE THREAD

**Issue by haxiomic** [vshaxe/vshaxe#378]
- I have some .hxml files that use hxpp and contain multiple targets separated with `--next`
- When I try to use autocomplete hxcpp starts compiling and generating output and autocomplete fails
- Autocomplete works when I remove the `--each` and `--next` flags

Maybe the solution is only pick the first batch for autocomplete and ignore the rest

(using haxe-rc4)

For example
**android.hxml**
```hxml
Main

-cpp bin/android

--class-path src
--library hxcpp:4.0.52

# Compile multiple architectures
--each
-D HXCPP_X86_64
--next
-D HXCPP_X86
--next
-D HXCPP_ARM64
--next
-D HXCPP_ARMV7
```

**Comment by Gama11** [comment]
Is this related to https://github.com/HaxeFoundation/haxe/commit/82bd2c8afce872db026d5bb6fc19b1449ec24296 by chance?

Either way, `--next` isn't really supported for code completion and vshaxe doesn't do anything with it (it just passes the hxml file path onto Haxe).

**Comment by haxiomic** [comment]
Ooo nice find @Gama11, that suggests is a known issue then – I tried RC2 and things are a little better; it still generates code but _only when building the completion cache_ and from then onwards autocomplete works.

When testing haxe at the latest commit (https://github.com/HaxeFoundation/haxe/commit/de61358efb411ad199b54c58fb8468f5b514becd) autocomplete fails, so seems like there's a regression here

Do you have the option to transfer this to the haxe repo? (Otherwise I'll close this and open a new one there)

**Comment by haxiomic** [comment]
I tried the commit before the one you mentioned and the behavior is the same – so I don't think that was the breaking commit

**Comment by Gama11** [comment]
No, issue transfer only works within the same organization.
