### ISSUE TITLE
Open problems view after global diagnostics runs

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#38]
I'm not sure if VSCode exposes the API necessary for that yet, wasn't able to find any problems-view-related APIs...

**Comment by Gama11** [comment]
Opened a feature request here: https://github.com/Microsoft/vscode/issues/11399

**Comment by nadako** [comment]
I can't find any API for this.

**Comment by Gama11** [comment]
That's why I opened the feature request on vscode. :)
