### ISSUE TITLE
`formatOnPaste` is not working fine

### ISSUE THREAD

**Issue by terurou** [vshaxe/vshaxe#382]
I pasted a single line text into doc comment.

![capture](https://user-images.githubusercontent.com/592887/64931958-bf602300-d876-11e9-9ed8-c520ec89c468.gif)

* Haxe 4.0.0-rc.5
* vs code 1.38.1
* vshaxe 2.16.3
* Windows 10 1903

settings.json

```json
{
    "haxe.configurations": [
        ["completion.hxml"]
    ],
    "[haxe]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true
    }
}
```

**Comment by Gama11** [comment]
cc @AlexHaxe

**Comment by Gama11** [comment]
Looks like multiline strings have pretty much the same issue.
