### ISSUE TITLE
it's seem not support this -lib yield?

### ISSUE THREAD

**Issue by sonygod** [vshaxe/vshaxe#384]
it's seem not support this -lib yield?

![image](https://user-images.githubusercontent.com/748320/65017470-6ddc9480-d959-11e9-981a-1eaf5db9e2e3.png)

**Comment by Simn** [comment]
I don't know what this is but it's certainly not a vshaxe issue.

**Comment by Gama11** [comment]
That screenshot looks like the code is faded out, perhaps caused by some macro code generation in that library? If anything that would be a Haxe issue though since the diagnostics for fading out code come from there.
