### ISSUE TITLE
tink_core lib  will  make vshaxe not work when have keyword using

### ISSUE THREAD

**Issue by sonygod** [vshaxe/vshaxe#386]
https://haxetink.github.io/tink_core/#/types/annex

     package;

	using tink.CoreApi;
	using Person;

	class TestAnnex {
		public static function main() {
			var johnDoe = new Person("John Doe");
			johnDoe.about.get(ObservationProtocol); // gives us the same ...
			johnDoe.about.get(ObservationProtocol); // ... protocol every time
			johnDoe.on("died", function(_) trace("oh no!"));
			johnDoe.fire(new openfl.events.Event("died")); // traces "oh no!"
			
		}
	}

--------------------------------

        import openfl.events.EventDispatcher;

    using tink.CoreApi;

    class Dispatcher extends openfl.events.EventDispatcher {
        public function new<A>(target:A)
            super();
    }

    class PersonEvents {
        static public function on(target:Person, event:String, handler:Dynamic)
            target.about.get(Dispatcher).addEventListener(event, handler);

        static public function fire(target:Person, event:openfl.events.Event)
            target.about.get(Dispatcher).dispatchEvent(event);
    }

    class Person {
        public var name(default, null):String;
        public var about(default, null):Annex<Person>;

        public function new(name) {
            this.name = name;
            this.about = new Annex(this);
        }
    }

    class ObservationProtocol {
        public function new(person:Person) {}
    }

------------

when type 
   
   using Person;

all editor not work.

**Comment by sonygod** [comment]
oh, when restart vshaxe,it's fixed.

**Comment by sonygod** [comment]
it's still disabled when editing.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/66619185-92512700-ec0e-11e9-815d-28aec479a62e.png)

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/70768391-dcd25980-1d9f-11ea-9211-a1014169bc21.png)

**Comment by Gama11** [comment]
I'm unable to reproduce the problem you describe in your original post with Haxe 4.0.5, completion features work fine even with `using Person`:

![](https://i.imgur.com/iReFBOP.png)

I have no idea what the two most recent comments are about or how they're related to the original issue.
