### ISSUE TITLE
Change extension author to Haxe Foundation 

### ISSUE THREAD

**Issue by markknol** [vshaxe/vshaxe#39]
Now its on name of nadako.

**Comment by nadako** [comment]
I don't know what to do with this. i'm not against it, but IIUC the only way to do this is to publish the extension under the different publisher name and deprecate the old one, losing download count and creating confusion. TBH I had no idea this little experiment will gain so much traction...

**Comment by markknol** [comment]
Maybe ask the vscode guys?

**Comment by nadako** [comment]
I think I looked into some discussion on vscode repo before and they said it's not really possible, because that would change the identifier of an extension, so e.g. vscode won't know how to upgrade. I guess we could wait for this mechanism to be implemented.

**Comment by nadako** [comment]
I guess there's nothing to do here, so I'm closing this...
