### ISSUE TITLE
Vague message "using out of date haxe version"

### ISSUE THREAD

**Issue by XANOZOID** [vshaxe/vshaxe#390]
It says "you're using an out of date haxe version", but I wasn't. Well, it's a slight technicality. It would be more helpful if the extension labeled where it's getting the Haxe executable from, because there's more than one place VSHaxe may be checking. Whether it's the exact path or what VSHaxe is grabbing the path from in this project, anything extra helps.

In my case it was this:
[x] I looked to make sure my environment was using Haxe 4 latest
[x] As a reinforcement, I also set the "haxe.executable", vscode setting, to my Haxe4 path 
[x] Still an error. I tried to locate if there are any other Haxe executables on my computer (only RC5 existed but not globally)

It ended up being that my project was a Kha project, and I haven't updated my Kha version in a while.

# Solution
Have the popup, regarding Haxe version, show information about where it's identifying the version difference. Either by displaying a path to the exe, or showing which setting it's using.

**Comment by Gama11** [comment]
Kha is actually abusing the vshaxe API to override the Haxe executable. Normally `haxe.executable` should be "in control".

We could still print the path though.

**Comment by XANOZOID** [comment]
I would offer to add this fix myself, but my time is super limited. If this stays open until late December I guess I could xD
