### ISSUE TITLE
Go to definition doesn't work in some cases

### ISSUE THREAD

**Issue by djaonourside** [vshaxe/vshaxe#392]
Haxe 4.0.1, vshaxe 2.16.5

After updating haxe and vshaxe go to defintion feature does not work in classes that implement IConnectedComponent interface that processed by macro(haxe-redux lib). As you can see on the pic, cursor just jumps in the begining of the class.
![go_to_def](https://user-images.githubusercontent.com/12369638/68336202-fe7c5900-00ee-11ea-8e2b-eec26844476e.gif)

**Comment by Gama11** [comment]
Unfortunately, this isn't very useful without an isolated example.

If a macro is involved here,chances are that this is the macro's fault for not setting proper positions.

**Comment by djaonourside** [comment]
I've updated to the latest haxe-redux, haxe-react and it works now. Thank you)
