### ISSUE TITLE
Run HL without debugging

### ISSUE THREAD

**Issue by melMass** [vshaxe/vshaxe#397]
Hi,

Since [#28](https://github.com/vshaxe/hashlink-debugger/issues/28) is yet to be fixed, how can I simply run my Heaps app (HL) without debugging from VSCode ?

Thanks

**Comment by Gama11** [comment]
Just add `--cmd hl <file>` to your HXML? :)

**Comment by melMass** [comment]
Yep it's already there and works on the CLI, I want to hit F5 from VS but the pop-up about debugging on OSX shows up and blocks execution. I don't need debugging for now

**Comment by Simn** [comment]
If you don't want to debug you shouldn't press the debug key. Maybe ctrl shift B is what you're looking for?

**Comment by melMass** [comment]
@Simn Thanks, maybe! 
It tried that, it shows a popup **compile and run** but does nothing when I press enter. I do have the `--cmd` in my hxml and running `haxe hl.hxml` from the cli does compile and run automaticaly

**Comment by Gama11** [comment]
I'm not aware of anything in the VSCode UI that would be labeled "compile and run", other than maybe the name of a task? What do you mean by "it does nothing", doesn't run or doesn't compile either?

Ctrl+Shift+B (or Terminal -> Run Build Task...) should either directly run the default build task, or if none is configured as the default build task, give you a list like this:

![](https://i.imgur.com/k6zYA9s.png)

I suggest playing around with a project that is known to be configured correctly, such as https://github.com/Gama11/HaxeRepro.

**Comment by rcstuber** [comment]
There is the "Start without Debugging" option in VSCode, I believe this is what @melMass was referring to. I believe the debugger extension has to explicitly support this. Any chance we can get this while waiting for the OSX debugger support?
See: https://code.visualstudio.com/docs/editor/debugging#_run-mode

**Comment by Gama11** [comment]
That would be something for the hashlink-debugger extension, vshaxe has no control over that: https://github.com/vshaxe/hashlink-debugger
