### ISSUE TITLE
"Extract constant" should not be available for object literal field names

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#405]
This is not a valid transformation, it changes the field name from `field` to `FIELD` and the generated constant is an unused variable.

```haxe
class Main {
	static function main() {
		var object = {
			"field": "value"
		}
	}
}
```

->

```haxe
class Main {
	public static inline var FIELD:String = "field";

	static function main() {
		var object = {
			FIELD: "value"
		}
	}
}

```

**Comment by AlexHaxe** [comment]
fixed in https://github.com/vshaxe/haxe-language-server/commit/1603c0208b1ec5b1280db8940534f8cf255f6333
