### ISSUE TITLE
Compilation status on status bar

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#408]
Thanks for this great extension and your hard work!
Is it possible to add the compilation status in the bottom status bar, or if the build failed, show a notification with the error details?
I disabled the auto-open Terminal tab on build feature, but now I can't be sure that the compilation succeeded.

**Comment by Gama11** [comment]
You can make VSCode open the problems panel automatically with `revealProblems`:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "haxe",
			"args": "active configuration",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"presentation": {
				"revealProblems": "onProblem"
			}
		}
	]
}
```

**Comment by mikicho** [comment]
Great, exactly what I searched for! <3
