### ISSUE TITLE
Incompatibility with Vim plugin on latest version

### ISSUE THREAD

**Issue by TomFors** [vshaxe/vshaxe#410]
When upgrading the Haxe VSCode extension v2.17.0 I noticed that I was unable to navigate using vim movement commands using the [Vim extension](https://github.com/VSCodeVim/Vim.git) v1.12.4. Instead of moving, all keystrokes were inserted at the current position as if the Vim extension was not getting the inputs. Hitting escape did not fix the issue. The VIM mode selection was still running and was showing `-- NORMAL --`. Downgrading the Haxe extension to v2.16.5 fixes the problem for me.

I am running VSCode 1.41.1 on Windows 10 64-bit.

Here's the user settings.json I'm using:
```
{
    "breadcrumbs.enabled": true,
    "haxe.enableCodeLens": false,
    "vim.ignorecase": true,
    "vim.smartcase": true,
    "window.zoomLevel": 0,
    "workbench.iconTheme": "material-icon-theme",
    "files.exclude": {
        "**/*.hxproj": true
    },
    "vim.handleKeys": {
        "<C-a>": false,
        "<C-c>": false,
        "<C-n>": false,
        "<C-w>": false,
        "<C-v>": false,
        "<C-o>": false,
        "<C-k>": false,
        "<C-y>": false,
        "<C-x>": false,
        "<C-t>": false
    },
    "haxe.buildCompletionCache": true,
    "editor.insertSpaces": false,
    "editor.trimAutoWhitespace": false,
    "haxe.enableExtendedIndentation": true
}
```

**Comment by Gama11** [comment]
>"haxe.enableExtendedIndentation": true

There's your issue. To implement this feature, we have to override the same "type" command that the Vim extension uses under the hood. As far as I know there's no way to avoid this conflict... https://github.com/Microsoft/vscode/issues/13441

Note that `"haxe.enableExtendedIndentation"` is opt-in for this and other reasons (potential performance overhead as documented in the wiki).

**Comment by Gama11** [comment]
I've added a note about the incompatibility with the Vim extension to https://github.com/vshaxe/vshaxe/wiki/Auto-Indentation.

**Comment by TomFors** [comment]
Thank you! That second option solved the problems I was having!

**Comment by moltzaum** [comment]
@Gama11 I am running into a similar incompatibility with vim as described in this issue, but I did not set "haxe.enableExtendedIndentation" to true. Downgrading worked for me and I think I'll use the older version for now. If you have any additional insights I'd appreciate it.

**Comment by Gama11** [comment]
Are you sure about that? Flixel generates a settings.json where it's true by default for instance.

**Comment by tmunro** [comment]
Awesome, that’s much clearer and hopefully will help some folks in the future. Thanks so much!

**Comment by moltzaum** [comment]
@Gama11 
> Are you sure about that? Flixel generates a settings.json where it's true by default for instance.

I'm not sure where that file would be. The only settings files are below, the bottom one never was set to "true", and I've set it to false explicitly as well.

`/usr/local/lib/haxe/lib/flixel-tools/1,4,4/settings.json`
```
{"AuthorName":"","IDEA_Path":"/Applications/Cardea-IU-130.1619.app/Contents/MacOS/idea","DefaultEditor":"Visual Studio Code","IDEA_Flixel_Engine_Library":"Flixel Engine","IDEA_Flixel_Addons_Library":"Flixel Addons","IDEAutoOpen":true,"IDEA_flexSdkName":"flex_4.6"}
```

`~/Library/Application Support/Code/User/settings.json`
```
{
    "haxe.codeGeneration": {},
    "extensions.autoUpdate": false,
    "editor.trimAutoWhitespace": false,
    "haxe.enableExtendedIndentation": false,
}
```

**Comment by moltzaum** [comment]
@tmunro 

What was the workspace setting?

**Comment by Gama11** [comment]
@moltzaum `.vscode/settings.json` in your workspace / project?

**Comment by moltzaum** [comment]
@Gama11 Yep, it was there. Thanks!
