### ISSUE TITLE
Formatter config

### ISSUE THREAD

**Issue by daimeng** [vshaxe/vshaxe#413]
How do I override formatter defaults? (specifically the maxLineLength of 160)

**Comment by AlexHaxe** [comment]
formatter uses `hxformat.json` for configuration. Place your `hxformat.json` file somewhere along or above files in question (e.g. workspace root) and it will apply.

See https://github.com/HaxeCheckstyle/haxe-formatter/blob/master/resources/default-hxformat.json for a full list of formatter's default values (you only need to override values you disagree with).

**Comment by daimeng** [comment]
Thank you!

**Comment by Gama11** [comment]
See also https://github.com/vshaxe/vshaxe/wiki/Formatting.
