### ISSUE TITLE
Auto-import invalid syntax

### ISSUE THREAD

**Issue by haxiomic** [vshaxe/vshaxe#414]
When using the auto-import feature, the import statement can sometimes end up in the wrong place, creating invalid syntax (see gifs)

Minimal example
![import-bug-minimal](https://user-images.githubusercontent.com/3742992/73680284-e39c8f00-46b3-11ea-9e09-4e1278f3b716.gif)

More complex example
![import-bug](https://user-images.githubusercontent.com/3742992/73679742-e77be180-46b2-11ea-9ab9-0afcb5eaf5ba.gif)

I haven't looked into it yet but I guess it's just some regex that needs tightening up.

Example code
```haxe
package;

@:keep // comment seems to affect this bug
class Main {
    static function main() {
        
    }
}
```

`package;` is required to trigger the bug

**Comment by Gama11** [comment]
>I guess it's just some regex that needs tightening up

Luckily the code for this is not regex-based. :)
