### ISSUE TITLE
How to specify source path?

### ISSUE THREAD

**Issue by CrazyFlasher** [vshaxe/vshaxe#415]

**Comment by Gama11** [comment]
https://haxe.org/manual/compiler-usage-hxml.html

**Comment by CrazyFlasher** [comment]
I mean for autocompletion in vscode

**Comment by Gama11** [comment]
I mean for autocompletion in VSCode too.

**Comment by CrazyFlasher** [comment]
HXML is generated by OpenFL

**Comment by Gama11** [comment]
In that case you don't have to configure anything, just install the Lime extension.

https://github.com/vshaxe/vshaxe/wiki/Framework-Notes

**Comment by CrazyFlasher** [comment]
Installed Lime extension. Dependencies are dimmed and auto-complete doesn't work.

![2020-02-04 11_58_09-Window](https://user-images.githubusercontent.com/1607138/73734125-d0d29a80-4745-11ea-8bcd-c8fcd9b6f0e3.png)

**Comment by Gama11** [comment]
https://github.com/vshaxe/vshaxe/wiki/Troubleshooting
