### ISSUE TITLE
Autocomplete `-java-lib` externs

### ISSUE THREAD

**Issue by Jumblemuddle** [vshaxe/vshaxe#416]
I have `-java-lib library.jar` in my `build.hxml`, however VSCode isn't completing the generated externs from this JAR. It builds fine, but it would be very nice to have autocomplete for the Java namespaces in the library.

**Comment by Gama11** [comment]
Works fine for me with JUnit and Haxe 4.0.5:

![](https://i.imgur.com/qB3wTVk.png)

You'll have to provide a reproducible sample. Please reopen this issue on the Haxe repo in that case though, since completion results are provided by directly the compiler.
