### ISSUE TITLE
Haxe vscode display server can not work with local library

### ISSUE THREAD

**Issue by IljaK** [vshaxe/vshaxe#417]
If specify `haxelib dev <lib> <path>` compiler works fine, but haxe.displayServer can not display/navigate to specifyed foler. It only show .dev file with path to library. Sow the navigation to classes does not work.

**Comment by Gama11** [comment]
Can you provide more information to reproduce the problem? Your description seems a bit vague.

**Comment by CrazyFlasher** [comment]
I guess he cannot configure auto-complete for dev library. How to add it to source path instead?
Currently only non-dev lib can be adde to auto-complete

**Comment by Gama11** [comment]
@CrazyFlasher That makes no sense though, there isn't really any difference between dev and non-dev libs when it comes to their usage.

**Comment by CrazyFlasher** [comment]
Well, I am not using vscode, though my teammate doesnt have autocomplete to dev path of specific lib if he forces to use local path.
I attach zip with small project example soon. Thanks for patience

**Comment by IljaK** [comment]
I'm talking about using local git repository for specific library. For example you can install haxe library 2 ways: from git and from haxe lib repository. Both ways are working fine in vscode. But for git repository library there is another option. If I already have git project for my custom library locally which I'm working on, there is no option in vscode to include path directly. "haxelib" itself has command to set usage local sources for compilation `haxelib dev <lib> <path>`, but vscode shows that sources are missing in project.
![2020-02-17 10_18_48-Window](https://user-images.githubusercontent.com/5029372/74636065-ee552a80-516f-11ea-8910-f84978cc30a8.png)

**Comment by IljaK** [comment]
Update:
Things started to work after project build. Tired with 2 different projects which extends local library. None of them could load sources properly, but after build problem disappear. Moreover I could not reproduce this error after all things started to work even by deleting export folder and some vscode cache folders. Might be someone has explanation?

**Comment by Gama11** [comment]
`lime display` behaves differently when there's an `export` directory for the selected target, but yeah, if that was it, deleting it should've reproduced it..

**Comment by Gama11** [comment]
Let us know if you find a way to reproduce it. I'll close here for now since there's not much that can be done without repro steps.
