### ISSUE TITLE
Code completion does not work for fields of the parent class when using @:structInit metadata.

### ISSUE THREAD

**Issue by RedHeadEatBread** [vshaxe/vshaxe#418]
![structInit](https://user-images.githubusercontent.com/50680881/74585523-78758580-4fee-11ea-9aa4-cdbbfa1597de.png)

If I understand correctly, the problem is in the extension, since the compiler requires both fields.

**Comment by Gama11** [comment]
Code completion is provided by the compiler, so it can't really be a vshaxe issue.

Also, please don't just include a screenshot of the code, but also the actual code for easy copy + paste. :)

**Comment by RedHeadEatBread** [comment]
I get it. Issue moved https://github.com/HaxeFoundation/haxe/issues/9145
