### ISSUE TITLE
Peek definition not working

### ISSUE THREAD

**Issue by hasen6** [vshaxe/vshaxe#419]
Peek definition works fine for me with Java with the Java language support extension but the Haxe language extension is not the same. According to the list of functions it has Peek definition but holding command and hovering shows nothing and manually selecting Peek Definition returns the error 'no definition found for'.

I tried disabling all extensions except Haxe language support (and of course restarting vscode) but to no avail. There don't seem to be any hover hints and possibly most listed features are not there.

Of course I am testing with .hx files and I have Haxe 4.0.5 installed for OS X.

**Comment by Gama11** [comment]
It's hard to help without more info. Please refer to this page for general troubleshooting steps:

https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

To make sure it's not related to your project setup, you could try to clone + open [this repo](https://github.com/Gama11/HaxeRepro), which is known to have a working setup - or use the "Haxe: Initialize Project" command.

**Comment by hasen6** [comment]
It does seem to work with the initialised base project, it's not working with the https://github.com/deepnight/gameBase gamebase which I was looking at. With that I get this error:

"Unable to build cache - completion features may be slower than expected. Try fixing the error(s) and restarting the language server."

Not sure why that is.

**Comment by Gama11** [comment]
Well, there should be an error after that output?

**Comment by hasen6** [comment]
I guess it's referring to these errors:

/usr/local/lib/haxe/lib/deepnightLibs/0,0,31/src/dn/heaps/HParticle.hx:11: characters 8-25 : Type not found : hxd.impl.AllocPos
src/Main.hx:4: lines 4-94 : Defined in this class
/usr/local/lib/haxe/lib/castle/1,6,1/cdb/Lang.hx:200: characters 62-75 : Warning : This typedef is deprecated in favor of haxe.xml.Access

The gamebase is only a few months old though.

**Comment by Gama11** [comment]
Either way, these errors are not specific to completion (you would get the same ones when trying to compile the project) or related to vshaxe. This belongs on the gamebase repo (or you could get some help on the [#heaps Discord channel](https://discordapp.com/invite/sWCGm33) since it's likely just a setup issue ).
