### ISSUE TITLE
Uncaught exception Cannot call null

### ISSUE THREAD

**Issue by sonygod** [vshaxe/vshaxe#420]
(unknown) : Uncaught exception Cannot call null
(unknown) : Called from here

every time when got one error, I have to refresh which switches another  .hxml to refresh.

how to fixed?

**Comment by Gama11** [comment]
Please provide a way to reproduce the problem, otherwise there's not much we can do to help.

**Comment by nadako** [comment]
I get this sometimes and I think it is related to some macro/eval context breaking, but also could not easily reproduce it.

**Comment by Simn** [comment]
Happened to me too but I couldn't figure out what's going wrong yet.

**Comment by sonygod** [comment]
maybe haxelib error.

when I link this lib 

-lib [numerix](https://lib.haxe.org/p/Numerix/)

it's happen very frequently！

**Comment by ibilon** [comment]
Had this too, but after updating to latest haxe nightly (https://github.com/HaxeFoundation/haxe/commit/310eae9e603db05608864f50a5471c45eafe094a) I can't seem to reproduce anymore.
With some luck something was fixed in those new commits.

**Comment by sonygod** [comment]
@ibilon  still had .
![image](https://user-images.githubusercontent.com/748320/75132161-eb7aac80-5710-11ea-8cb8-9c602eafc7ee.png)

**Comment by sonygod** [comment]
I find a way to reproduce it

clone heaps https://github.com/HeapsIO/heaps

wait a long time to buildCache ..

![image](https://user-images.githubusercontent.com/748320/76814198-19956d00-6835-11ea-9ed9-b9d789bec1b6.png)

@Gama11 @Simn

**Comment by sonygod** [comment]
fixed by https://github.com/HaxeFoundation/haxe/commit/717c4061d0db9e2160d36decd4753d1e755736f1

**Comment by Gama11** [comment]
I think https://github.com/HaxeFoundation/haxe/commit/6ef48a121a0423eedca64c00a188700a510792c7 is the relevant commit actually, but yes it should be fixed.
