### ISSUE TITLE
Bad completion after case X:

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#426]
```haxe
enum WsType {
	Connected;
}

class Main {
	static function main() {
		final type = Connected;
		trace('${type}'); // no problem with '$type'
		switch (type) {
			case Connected:
		}
	}
}
```
![image](https://user-images.githubusercontent.com/8753432/78689722-536f0600-78ff-11ea-8f16-6284e78da58e.png)

**Comment by Gama11** [comment]
Moved to https://github.com/HaxeFoundation/haxe/issues/9311 since it's a Haxe issue.
