### ISSUE TITLE
Is it possible to debug flash apps with fdb?

### ISSUE THREAD

**Issue by Deirel** [vshaxe/vshaxe#43]
Hi,
I know there's hxcpp debugger for VS Code, but how can I debug apps for flash target?

**Comment by nadako** [comment]
I know @nulld is [working on it](https://github.com/nulld/vscode_fdb_adapter), but I have no idea if it's usable yet.

**Comment by nadako** [comment]
There's a [repo](https://github.com/vshaxe/vshaxe-debugadapter) with the fdb adapter ready for testing now. We may or may not merge it into vshaxe at some point, but it's still too early to discuss it as it's in its very early days. You could try it and report issues there.
