### ISSUE TITLE
Failed to create token tree, top-level autocompletion stops working

### ISSUE THREAD

**Issue by dmitryhryppa** [vshaxe/vshaxe#430]
Hi,

For some reason, top-level autocompletion stops working for one of my projects. Also, some code snippets are not working anymore too (for `new` and `main` keywords).

I did not change anything in project codebase before it broke, and It was working fine a few days ago. Maybe it is related to 1.44.1 update?
But, some of my other projects keep working fine so I'm not sure how to reproduce that issue :(

I tried to disable all macros, but it did not help. 

Here is how the problem looks like:
![autocomplete_](https://user-images.githubusercontent.com/4466595/79517100-de65a400-8055-11ea-9854-993d08b975dc.gif)

And here is what I've got in the output window:
```
(node:3984) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'position' of null
    at Function.createImportsEdit (c:\Users\dmitryhryppa\.vscode\extensions\nadako.vshaxe-2.19.3\server\bin\server.js:1:347885)
    at Lt.createTypeCompletionItem (c:\Users\dmitryhryppa\.vscode\extensions\nadako.vshaxe-2.19.3\server\bin\server.js:1:313881)
    at Lt.createCompletionItem (c:\Users\dmitryhryppa\.vscode\extensions\nadako.vshaxe-2.19.3\server\bin\server.js:1:309919)
    at v (c:\Users\dmitryhryppa\.vscode\extensions\nadako.vshaxe-2.19.3\server\bin\server.js:1:308211)
    at c:\Users\dmitryhryppa\.vscode\extensions\nadako.vshaxe-2.19.3\server\bin\server.js:1:308571

[Error - 2:21:59 AM] Request textDocument/documentSymbol failed.
  Message: Unable to build token tree
  Code: -32603 
failed to create token tree: TypeError: Cannot read property 'addChild' of null
```

Haxe 4.0.5, hxml target is Cpp

**Comment by Gama11** [comment]
@AlexHaxe Any idea? Looks like `addChild()` is probably a tokentree call. https://github.com/HaxeCheckstyle/tokentree/search?q=addChild&unscoped_q=addChild

**Comment by AlexHaxe** [comment]
yes, there must be some code / syntax constellation, where tokentree runs into a null pointer situation.However there is not much to go on, I would need the full source of a file where it occurs in order to investigate the why.

Can you reliably reproduce tokentree error in that file? If yes, strip it down to a bare minimum, aka remove all code secrets you are not prepared to share and raise an issue in tokentree repo (https://github.com/HaxeCheckstyle/tokentree/issues/new). Of interest are also your conditional compilation sections (not necessarily actual conditions, rather their layout / structure).

**Comment by dmitryhryppa** [comment]
Aha! I found it.  Mixing `private` and `final` keywords with `class` will produce an error:
```haxe
package;
private final class Test {
	public function new() {
	}
}
```
But `private class` and `final class` will work fine. 

As @AlexHaxe asked, I've created an issue in the `tokentree` repo: https://github.com/HaxeCheckstyle/tokentree/issues/183

Feel free to close the current issue if needed :) 
Thank you!

**Comment by Gama11** [comment]
Let's leave it open for now until we have updated vshaxe to a tokentree version where it's fixed. :)
