### ISSUE TITLE
[java] Unable to build cache

### ISSUE THREAD

**Issue by rhacking** [vshaxe/vshaxe#431]
I'm trying to use Processing (Java library). The following file (`src/Test.hx`):
```haxe
import processing.core.PApplet;

class Test {
    static public function main():Void {
    }
}
```

and the following `build.hxml`:
```hxml
-cp src
-main Test
-java-lib lib/core.jar
--java bin
-dce no
```
(where `lib/core.jar` is the jar file shipped with Processing in the subfolder `core/library`)
Results in the language server giving the following error: 
```
Unable to build cache - completion features may be slower than expected. Try fixing the error(s) and restarting the language server.
```

When clicking the `Show error` button I see the error `Invalid number of type parameters for java.util.Set`. However, when compiling the code (using `haxe .\build.hxml`), I get no error. The error only occurs when I'm importing `processing.core.PApplet`, and, when doing so, the linting seems to fail, though intellisense and code navigation still seem to work. 

I'm using vshaxe 2.19.4, tried Haxe 4.0.5 and 4.1.0-rc.1+4450dfbb6, javac 1.8.0_252 and I tried the latest hxjava version as well as the latest git master branch hxjava.

**Comment by Gama11** [comment]
This is an issue with Haxe, not vshaxe. Moved to https://github.com/HaxeFoundation/haxe/issues/9438.
