### ISSUE TITLE
Add -D display when building completion cache?

### ISSUE THREAD

**Issue by basro** [vshaxe/vshaxe#432]
When haxe.buildCompletionCache is enabled vshaxe will run a build with --no-output.

Since this is intended for building completion cache wouldn't it be better to add -D display as well?

It is common for macros to have a special fast lane for display mode.

Additionally this would be helpful for macros that act on the generated output file, for example uglifyjs or the lib I'm making jsasync. Since there's no way to distinguish the initial completion cache build from a regular build both libraries will try to modify the output file (causing completion cache to fail if the file doesn't exist, or creating / modifying files when the user doesn't expect it to)

**Comment by Gama11** [comment]
Defining `display` here wouldn't be correct. It's not only intended for completion, but also compilation through the server (which is enabled by default).

If you need to check for this, you can do something like this:

https://github.com/vshaxe/haxe-test-adapter/blob/8f82774b558339226e4fa5906d7b85e2250beb6d/test-adapter/_testadapter/Macro.hx#L63

(which admittedly seems hacky, and long-term we probably need something better)

**Comment by basro** [comment]
Thanks a lot for the tip on detecting `--no-output`, I'll be using it.

I see now that the `display` define is special in that it is being ignored by the compiler when deciding which cache to use to build a project. So adding `display` would actually break the output of the same project when built with the server without `display`.

What if `-D vshaxe-completion-cache` was also added? That way compiled cache would not be shared with normal builds so it wouldn't be a problem of build correctness.

**Comment by Gama11** [comment]
But the cache _should_ be shared to improve build times.

**Comment by basro** [comment]
I see, thanks for your answers.
