### ISSUE TITLE
haxe.executable ${workspaceFolder}

### ISSUE THREAD

**Issue by peteshand** [vshaxe/vshaxe#433]
This may already be achievable somehow, but haven't seen any documentation about it.

Is it possible to use something similar to vscode's build in ${workspaceFolder} or ${workspaceFolder:workspaces} when defining settings within haxe.executable
eg:
```
"haxe.executable": {
	"env": {
		"HAXELIB_PATH": "${workspaceFolder:project}/some/path/within/project",
	}
},...
```

This is possible for other vscode settings, eg: 
```
"terminal.integrated.env.osx": {
	"HAXELIB_PATH": "${workspaceFolder:project}/some/path/within/project",
}
```

I realize that in some cases using a relative path will do the job, however in some cases it's helpful to be able to set the absolute path.

**Comment by Gama11** [comment]
Well, we don't have multi-root support yet (https://github.com/vshaxe/vshaxe/issues/170), so I don't really see the use case for this (for now).

**Comment by peteshand** [comment]
ok, well take the muti-root support out of the question.
eg:
```
"haxe.executable": {
	"env": {
		"HAXELIB_PATH": "${workspaceFolder}/some/path/within/project",
	}
}
```
Keep in mind that "HAXELIB_PATH" is just being used as an example there.
Currently supported or not? (guessing not by last response)

**Comment by Gama11** [comment]
There is a dedicated `haxelib.executable` setting.

**Comment by peteshand** [comment]
same question thought, does it support ${workspaceFolder}?

**Comment by Gama11** [comment]
I don't really get why it would have to, if you can use a relative path?

**Comment by peteshand** [comment]
hmmm, so you're saying there was no need for Microsoft adding ${workspaceFolder}?

**Comment by Gama11** [comment]
I guess? ¯\_(ツ)_/¯

**Comment by peteshand** [comment]
haha. yeah I'm pretty sure it'll be useful in some edge cases, a good example seems to be when using Lime. Unless absolute paths are used it seems to fall over. I'm sure there'll be other instances.

All good that it's not implemented, I might have a dig into at some stage when I find some time.

Thanks.
