### ISSUE TITLE
FlxObject.hx Expected }

### ISSUE THREAD

**Issue by Haxe756** [vshaxe/vshaxe#434]
The issue in the Output section is:
Haxe server restart requested: DisplayArguments configuration was changed
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Restarted Haxe server: DisplayArguments configuration was changed
Client connected
Failed - try fixing the error(s) and restarting the language server:

C:/HaxeToolkit/haxe/lib/flixel/4,7,0/flixel/FlxObject.hx:656: characters 2-5 : Unclosed conditional compilation block

...

When I have it take me to the problem it brings up the FlxObject class and indicates the issue has something to do with this block:
#if FLX_DEBUG
	// this just increments FlxBasic.activeCount, no need to waste a function call on release
	super.update(elapsed):Void;
	{
		last.set(x, y) {};
		if (path != null && path.active)
			path.update(elapsed);
		if (moves)
			updateMotion(elapsed);
		wasTouching = touching;
		touching = NONE;
	}

... 

Any help would be much appreciated!

**Comment by Gama11** [comment]
It looks like you may have accidentally modified the sources of `FlxObject.hx`, they should look like this:

https://github.com/HaxeFlixel/flixel/blob/4.7.0/flixel/FlxObject.hx#L715-L718

**Comment by Haxe756** [comment]
That worked perfectly. Thank you so much!
