### ISSUE TITLE
Can't Start New Project

### ISSUE THREAD

**Issue by powerfuldeveloper** [vshaxe/vshaxe#435]
Using windows 10, Installed Haxe using installer

- [x] Restarted Windows
- [x] Restarted VSCode

### The Error
```
Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6000
Failed - try fixing the error(s) and restarting the language server:

Unix.Unix_error(21, "open_proc", "haxelib path heaps")
```

**Comment by Gama11** [comment]
This seems similar to https://github.com/HaxeFoundation/haxe/issues/6835. Can you try that COMSPEC solution from there?

**Comment by powerfuldeveloper** [comment]
@Gama11 yes it worked
