### ISSUE TITLE
getter, setter snippet ??

### ISSUE THREAD

**Issue by hopewise** [vshaxe/vshaxe#437]
Is there any snippet for generating a var with getter, setter ?? that would be super handy

**Comment by Gama11** [comment]
Yes.

![image](https://user-images.githubusercontent.com/2620907/82882802-de54a000-9f41-11ea-896c-7aed71bad906.png)

**Comment by hopewise** [comment]
Thanks, is there a list of complete snippets? as I could not find this on https://github.com/vshaxe/vshaxe/wiki/Snippets

**Comment by Gama11** [comment]
Yes, in the source code. ;)

https://github.com/vshaxe/haxe-language-server/blob/master/src/haxeLanguageServer/features/completion/SnippetCompletion.hx
