### ISSUE TITLE
Emojies kill autocompletion

### ISSUE THREAD

**Issue by MatthijsKamstra** [vshaxe/vshaxe#438]
I'm running into something weird: if I use emojis in my code, the haxe autocompletion stops working.

Made a screengrab

![haxe](https://user-images.githubusercontent.com/907219/82988939-351db080-9ffa-11ea-962d-f7808e2f5121.gif)

```haxe
class Test {
	public function new() {
		trace('Test');

		var div = document.createDivElement();

		var e = '🆙';

		var div2 = document.createBaseElement()
	}

	static public function main() {
		var app = new Test();
	}
}

```
Some other stats:
- VScode Version: 1.45.1
- OSX: 10.15.4
- haxe -version :: 4.1.1

**Comment by Gama11** [comment]
Possibly related to https://github.com/vshaxe/vshaxe/issues/343.

**Comment by nadako** [comment]
Yeah I think it's the same issue. We have to look into it again and figure out the differences between haxe/lsp/vscode/etc. regarding whether surrogate pair counts as a single char or not.
