### ISSUE TITLE
Progress indicator for global diagnostics runs

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#44]
It would be really nice if there was some sort of progress bar or something that indicates the plugin is still working in the background... As is, you're never sure if there was some error running diagnostics, or if it's just taking a while (and it does take a bit with larg-ish projects like Flixel).

There's this blue progess slider thing that sometimes appears (during completion requests mostly) right under the tabs, maybe we can use that somehow via the API?

**Comment by nadako** [comment]
I think there's no API for that at the moment, however a progress reporting feature was discussed for the language server protocol thingy which means it'll probably be added to both vscode and the protocol sometime in future (see https://github.com/Microsoft/language-server-protocol/issues/54 and https://github.com/Microsoft/language-server-protocol/issues/70).

I'll close this for now as it's not an actionable issue.
