### ISSUE TITLE
Package insertion vs. slow compiler

### ISSUE THREAD

**Issue by Simn** [vshaxe/vshaxe#440]
Sometimes when creating a new file, package insertion is delayed because the compiler is still putting on his makeup or something. In cases like that we should just reject the package insertion if the file has been edited by the time it arrives. Muh user experience is suffering from this.

**Comment by nadako** [comment]
I actually kinda like that the package is still inserted above the stuff i started typing in.

**Comment by Gama11** [comment]
Same.. can we just make the compiler faster / multi-threaded? :3

**Comment by Simn** [comment]
I'm pretty sure that this violates some UX commandments, but it doesn't bother me enough to discuss this further if you guys are ok with it.

**Comment by Gama11** [comment]
The `package` statement randomly appearing in some cases and not others surely violates some UX commandments too. It should just work consistently..
