### ISSUE TITLE
Asset, AssetHelper, and HxProject Errors

### ISSUE THREAD

**Issue by Haxe756** [vshaxe/vshaxe#441]
Hello - I've followed this step by step tutorial but when I go to build it gives me the following output:

Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6000
Failed - try fixing the error(s) and restarting the language server:

C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/Asset.hx:29: characters 16-20 : Type not found : Path
C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/Asset.hx:42: characters 26-37 : Class<StringTools> has no field getFlatName
C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/Asset.hx:43: characters 12-16 : Type not found : Path
C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/Asset.hx:48: characters 20-24 : Type not found : Path
C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/HXProject.hx:11: characters 8-22 : You cannot access the sys package while targeting flash (for sys.FileSystem)
C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/AssetHelper.hx:11: characters 8-28 :     referenced here
C:/HaxeToolkit/haxe/lib/lime/7,7,0/src/lime/tools/Asset.hx:51: characters 8-19 :     referenced here

...

Any help would be much appreciated. All I did was add an animation and it gave me 7 Problems.

Thanks

**Comment by Gama11** [comment]
This is a question about OpenFL, not vshaxe, so I can't really help you. I suggest you use the OpenFL forums or Discord instead. Make sure to include more infos there, such as what you mean by "this" tutorial.

**Comment by Haxe756** [comment]
Hi Jens - I have never used OpenFL before. This was an error I encountered
in Visual Studio code using Haxe Flixel.

Regarding the tutorial, it is this one (part 3 of the series):
https://youtu.be/7Js6zmJCjC8

Thanks
