### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by Haxe756** [vshaxe/vshaxe#446]
Hello - I've been following the tutorial for a planet defense game - https://www.youtube.com/watch?v=6YemVrJnlS8 

I've made it to episode 3 where I've added my player onto the planet. I've also created a pixel animation panel. However, when I go to add the animation of my player walking and idling, it doesn't run any animation and instead just shows the first frame listed in the array.

Ex) My Idle animation is supposed to bop up and down but it just remains steady at the first panel. And my Walking animation just stays steady at the first panel as well. If I change the first panel in the array (to the player lifting his foot up to begin the step) it will just hold on that panel. Essentially, there is no animation being done. They're all still images that move around my planet. I've attached the panel of my pixel animations for reference. The panels are 16x16

![Player](https://user-images.githubusercontent.com/65465119/85914385-bab39c80-b802-11ea-9a09-5408ecbe941f.png)

Thanks

**Comment by Gama11** [comment]
This has nothing to do with Visual Studio Code Haxe integration, this is a framework-specific question... Please use the HaxeFlixel forums or Discord channel.
