### ISSUE TITLE
Language server update broke nvim compatibility

### ISSUE THREAD

**Issue by BeaudanBrown** [vshaxe/vshaxe#447]
Using neovim with coc pointing at the haxe-language-server server.js from vshaxe version 2.20.3 works very well, but since the update to 2.21.0 the updated server.js fails to register any capabilities besides textDocumentSync.

Not sure which specific changes are are fault yet but can provide any information
Can reproduce by installing neovim plugins [vaxe](https://github.com/jdonaldson/vaxe) (for haxe filetype) and [coc](https://github.com/neoclide/coc.nvim), then using the suggested coc config from the haxe-language-server to point coc to either the latest vshaxe server.js or by pulling haxe-language-server, building from source and pointing to that.

Running `:CocCommand workspace.showOutput` shows the language server response to the initialize request which is missing capabilities

**Comment by Gama11** [comment]
We're now using dynamic registration if possible, which is a separate request. https://github.com/vshaxe/haxe-language-server/commit/5caf2e78d9482132646baaef944661085f491fa5#diff-82a5927f6d6142c08da6ed3d62ff1ba4

However, I'm checking whether dynamic registration is supported in the client capabilities specifically to avoid compatibility issues, so it coc seems to support dynamic registration in general. Maybe the document selectors don't work? [Here](https://github.com/neoclide/coc.nvim/issues/502#issuecomment-471319098) it sounds like you need to configure the language ID somehow, so that it knows that `*.hx` means `haxe` (also `*.hxml` and `hxml` if you want HXML completion).

**Comment by BeaudanBrown** [comment]
I believe that the language ID is being configured correctly unless I am misunderstanding
Here is the initialisation request and response if that helps
https://pastebin.com/ATEEHFLp

**Comment by Gama11** [comment]
Where / how are you configuring the language ID?

**Comment by BeaudanBrown** [comment]
```
    "languageserver": {
        "haxe": {
            "command": "node",
            "args": ["/home/harold/.vscode-oss/extensions/nadako.vshaxe-2.20.3/bin/server.js"],
            "filetypes": ["haxe"],
            "trace.server": "verbose",
            "initializationOptions": {
                "displayArguments": ["build.hxml"]
            },
            "settings": {
                "haxe.executable": "haxe"
            }
        }
    },
```
This is the coc configuration, with this from the docs
`Dictionary of Language Servers, key is the ID of corresponding server,	and value is configuration of languageserver.`
And the filetypes are correctly being detected through the vaxe plugin which causes the server to be started when a .hx file is opened

**Comment by Gama11** [comment]
I don't think "language server ID" is the same thing as "language ID".

**Comment by BeaudanBrown** [comment]
I see, does this look incorrect?
```
[Trace - 6:15:43 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/<USER>/work/nebula-haxe/nebula/src/Main.hx",
        "languageId": "haxe",
        "version": 1,
        "text": <REDACTED>
    }
}
```
Trying to find where I should be configuring this

**Comment by Gama11** [comment]
Yes, the language id for .hx files is `haxe`.

**Comment by vantreeseba** [comment]
I have this issue as well.

The only thing not working correctly insofar as I can tell is the completion within *.hx files.
Strangely, the completion is working just fine in HXML files, so I'm not entirely sure why.

The other capabilities exposed are registered correctly, (goto def, refs etc) and are working fine.

**Comment by Gama11** [comment]
Looks like this was a coc bug (thanks @vantreeseba for reporting) that is now fixed: https://github.com/neoclide/coc.nvim/issues/2138#issuecomment-654072244
