### ISSUE TITLE
Rename symbol wierd behaviour

### ISSUE THREAD

**Issue by kiroukou** [vshaxe/vshaxe#448]
See video for detailed behaviour : 
https://slack-files.com/TFQ2HEP8R-F016CF632GK-fab56fb779

System: 
Haxe 4.0.3 & Haxe 4.1.2

VsCode with 
Haxe Extension Pack 1.3.0

Any idea of what is creating that behaviour? in addition to that, the symbol inside the blocks aren't renammed the same way.
thanks

**Comment by Gama11** [comment]
No, I've never seen that, but that's pretty funny. 😄 Any idea how to reproduce that / does that happen consistently?

**Comment by kiroukou** [comment]
It happens for 3 of our devs, different machines. 
Really no idea when it appeared, but from what they told me, that feature wasn't hardly working before as well. Just, less funny.

**Comment by Gama11** [comment]
In any case, not much to be done if it can't be reproduced - seems to work fine on my end.

**Comment by kiroukou** [comment]
hum...
if you can't reproduce, let me check differently then.  I'll disable other extensions and share with you the haxe configuration we use in case that could be related.

**Comment by kiroukou** [comment]
Ok so I tried on an other project, disabling most of the other extensions.

Here is the behaviour in video : 
https://streamable.com/3zlwb9

what you can see here : 
- first type, renaming didn't work at all
- redo the renaming, it does work in the variable for not on the references
- IT DOES MODIFY  some variable which are not related !

**Comment by Gama11** [comment]
I don't think there's any settings which would be relevant here...

**Comment by kiroukou** [comment]
ahah. Well, that still could be interessting for me to see someone else settings.

Otherwise, do you have something in mind that could explain that behaviour ? (which is consistent here for several people)

**Comment by Gama11** [comment]
Nope, no idea. :smile: Does that happen even in a hello world project?

**Comment by kiroukou** [comment]
not better: https://streamable.com/ax944k

Are you sure it does work for you ? ^^ 
but yeah, is that a visual studio code feature integration into the extension or is that something specific the completion server can supply (in this case, how can I debug that) ?

**Comment by Gama11** [comment]
![0uIu4oWXxK](https://user-images.githubusercontent.com/2620907/86261920-7daf2780-bbbf-11ea-8a98-7d69151fd13d.gif)

The Haxe server is not involved here actually.

**Comment by kiroukou** [comment]
wow. Alright then.
Need to make an haxe version upgrade I guess... I cant see anything else.

**Comment by Gama11** [comment]
You're using latest vshaxe? You said Haxe Extension Pack 1.3.0,  but the version of that is pretty irrelevant.

**Comment by kiroukou** [comment]
Seriously?
Never though to check that, being sûre it was juste a bundle to the latest
version of the libs...i'll check that tomorrow....

Le mer. 1 juil. 2020 à 17:43, Jens Fischer <notifications@github.com> a
écrit :

**Comment by ee-ij** [comment]
Hi!
I am running into this issue with Haxe 4.1.2, vshaxe 2.21.0. I have disabled all other extensions to avoid any interference.

Here's a self-contained example: [Hello.zip](https://github.com/vshaxe/vshaxe/files/4862703/Hello.zip)

```Haxe
class Hello {
    function new() {}

    function foo() {
        for (i in 0...10) {
            trace(i);
        }
    }

    static function main() {
        new Hello().foo();
    }
}
```

After placing the caret on the first "foo" (function declaration) and pressing F2 to rename the symbol, it seems all letters from the original symbol must occur in the new name for anything to happen. And even then, the renaming acts strangely. Here are some examples of what happens for me:
- Renaming `foo` to `bar` fails with "Rename failed to apply edits".
- Renaming `foo` to `fo` fails with "Rename failed to apply edits".
- Renaming `foo` to `foobar`: Getting `foobarbarbar` instead. The function call in main doesn't get renamed.
- Renaming `foo` to `f_o_o`: Getting `f___o___o` instead. The function call in main is still unchanged.

Similarly, renaming `i` in the function  body fails if the new name does not contains an `i`. E.g. renaming `i` to `hi`  "works" but yields `hhhi`, and `i` within the loop body isn't renamed.

Please let me know if there's anything I can do to help troubleshoot this further. Thank you!

**Comment by Gama11** [comment]
@ee-ij There's no support for renaming fields (#188). You should see this message when trying to rename `foo`:

![image](https://user-images.githubusercontent.com/2620907/86398524-07d1bb80-bca6-11ea-9d23-cf885c14f083.png)

I can't reproduce the problems with renaming `i` either.

![HMxR90DolF](https://user-images.githubusercontent.com/2620907/86398831-8595c700-bca6-11ea-8eb2-de7dfdeac087.gif)

**Comment by kiroukou** [comment]
Can you share the exact version of the plugin you use?
.vscode folder and its json as well?

It must have an explanation Somewhere.

Le jeu. 2 juil. 2020 à 20:56, Jens Fischer <notifications@github.com> a
écrit :

**Comment by Gama11** [comment]
I used @ee-ij's self-contained example project there with vshaxe 2.21.0. ¯\\_(ツ)_/¯

**Comment by kiroukou** [comment]
Would you mind to share thhe list of your extensions and versions so we can try to reproduice your environnement?

Are you on Windows ?
Thx

**Comment by AlexHaxe** [comment]
I just tried it on Linux and I see `Rename failed to apply edits` as well.
When using preview I get:
![refactor_foo](https://user-images.githubusercontent.com/7204032/86451377-22924780-bd1b-11ea-81a5-040b935869c6.png)
and 
![refactor_i](https://user-images.githubusercontent.com/7204032/86451390-24f4a180-bd1b-11ea-8ce8-023ec8d78346.png)
So apparently there are three edits all for the same location. If I deselect two and apply, then it works for just that one occurence, it doesn't change other places.

Developer console shows an error and a stacktrace:
```
notificationsAlerts.ts:40 Rename failed to apply edits
    onDidChangeNotification @ notificationsAlerts.ts:40
    (anonymous) @ notificationsAlerts.ts:26
    fire @ event.ts:587
    addNotification @ notifications.ts:207
    error @ notificationService.ts:59
    (anonymous) @ rename.ts:238
    Promise.catch (async)
    (anonymous) @ rename.ts:237
    processTicksAndRejections @ internal/process/task_queues.js:85
    Promise.then (async)
    run @ rename.ts:217
    async function (async)
    run @ rename.ts:173
    run @ rename.ts:306
    runEditorCommand @ editorExtensions.ts:259
    (anonymous) @ editorExtensions.ts:191
    invokeFunction @ instantiationService.ts:61
    invokeWithinContext @ codeEditorWidget.ts:360
    runCommand @ editorExtensions.ts:184
    runCommand @ rename.ts:300
    handler @ editorExtensions.ts:101
    invokeFunction @ instantiationService.ts:61
    _tryExecuteCommand @ commandService.ts:84
    (anonymous) @ commandService.ts:73
    Promise.then (async)
    executeCommand @ commandService.ts:73
    _doDispatch @ abstractKeybindingService.ts:200
    _dispatch @ abstractKeybindingService.ts:159
    (anonymous) @ keybindingService.ts:251
log.ts:197   ERR Error: Overlapping ranges are not allowed!
    at c.applyEdits (pieceTreeTextBuffer.ts:297)
    at e._doApplyEdits (textModel.ts:1376)
    at e.applyEdits (textModel.ts:1366)
    at pushEditOperation (editStack.ts:402)
    at e._pushEditOperations (textModel.ts:1314)
    at e.pushEditOperations (textModel.ts:1223)
    at executeEdits (cursor.ts:563)
    at viewModelImpl.ts:926
    at y._withViewEventsCollector (viewModelImpl.ts:1004)
    at y._executeCursorEdit (viewModelImpl.ts:923)
    at y.executeEdits (viewModelImpl.ts:926)
    at executeEdits (codeEditorWidget.ts:1131)
    at D.apply (bulkEditService.ts:117)
    at e.apply (bulkEditService.ts:228)
    at e._performTextEdits (bulkEditService.ts:379)
    at async e.perform (bulkEditService.ts:323)
```

**Comment by kiroukou** [comment]
Thanks @AlexHaxe for the test and confirmation of the issue.
If there's an overlap, that would explain the first video I shared.

What sounds strange, is the fact @Gama11 cannot reproduce it.  We did some test on a fresh VM, standalone project, windows and linux, and latest official haxe and plugin + vscode editor, and we have the error easily reproductible.

**Comment by Gama11** [comment]
I think I know what it is - I have auto-save enabled...

**Comment by Gama11** [comment]
Looks like this only reproduces with vshaxe compiled in release mode (rather than debug which I was using before) for some reason... 🤦‍♂️

**Comment by Gama11** [comment]
Seems that minification with uglify-es breaks something.,
