### ISSUE TITLE
[hxml autocomplete] incorrect completion for library with dash

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#450]
`-lib why-tim|` then TAB becomes `-lib why-why-timezone`

but expected `-lib why-timezone`

![Jul-02-2020 20-07-55](https://user-images.githubusercontent.com/1103788/86357080-e4a40d80-bc9f-11ea-87de-ecd3580a672a.gif)

**Comment by Gama11** [comment]
Hm,, yeah, I think I know why that happens...
