### ISSUE TITLE
Feature request: create function action

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#451]
```haxe
function main() {
  final x = 5;
  if (fooBar(x)) {} // <- Quick Fix > Create function 'fooBar'
}
// can generate:
function fooBar(x:Int):Bool {
  <cursor>
}
```
Calls to known classes/objects (like `Foo.bar()`) can generate function at the end of that scope. [Dart extension](https://github.com/Dart-Code/Dart-Code) can be checked as example of this feature.

**Comment by nadako** [comment]
That would be lovely indeed. Not just functions but any fields tho.

**Comment by nadako** [comment]
This requires a bit of thougt, because e.g. `Foo.bar` could have two generation options: static method or module-level function.

**Comment by Gama11** [comment]
Duplicate of https://github.com/vshaxe/vshaxe/issues/232.
