### ISSUE TITLE
hxml library completion: wrong lib name used if dot included

### ISSUE THREAD

**Issue by haxiomic** [vshaxe/vshaxe#452]
haxelib has this quirky behavior around library names that include dots: dots are replaced with commas for the libraries folder name.

For example, if you install a library like Console<b>.</b>hx, it goes into a folder "Console<b>,</b>hx"

When referencing the library for the compiler, you need to use original name: `--library Console.hx`

When autocompleting library names, vshaxe uses the folder "Console<b>,</b>hx" name rather than the correct name with the dot so compilation fails

**Comment by haxiomic** [comment]
I will look into fixing this when I get a moment

**Comment by Gama11** [comment]
🤦
