### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by winterwolf** [vshaxe/vshaxe#455]
1. Open empty folder in Code.
2. Press F1, run "Haxe Init Project".
3. Press Ctrl+Shit+B and get the error:

```
Error: The haxe task detection didn't contribute a task for the following configuration:
{
    "type": "haxe",
    "args": "active configuration",
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
The task will be ignored.
```
4. Uninstall everything.

I also get similar (and much more!) errors from HaxeFlixel tutorials. It's really not cool when you just copy-paste helloworld from website and get bunch of different unknown errors, which you have to report on different dead forums... This language sucks! 😤

**Comment by Gama11** [comment]
I can't reproduce that.

**Comment by winterwolf** [comment]
@Gama11 Before creating a project, I installed everything that is possible from this tutorial: https://haxeflixel.com/documentation/install-haxeflixel. I use x64 bit Manjaro 20.1 Mikah. Code version is 1.48.0, Haxe is 4.1.3.

**Comment by winterwolf** [comment]
I just removed all VSCode configs and this is solved half of my issues. Sorry for disturbing.
