### ISSUE TITLE
No compiler errors update after bad build

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#456]
```haxe
class Main {
	static function main() {
		new Array();
	}
}
```
- Change to `new Arra();`
- Build (hxml is `--main Main --interp`)
- Change back to `new Array();` and save file
- "Type not found" error remains

**Comment by Gama11** [comment]
Yes, errors from tasks / problem matchers update on build, diagnostics from the display API update on save. That's a known limitation.

See https://github.com/vshaxe/vshaxe/issues/132 for more details.
