### ISSUE TITLE
Allow specifying enableCompilationServer per build configurations.

### ISSUE THREAD

**Issue by back2dos** [vshaxe/vshaxe#458]
I have a project where the compilation server works super great on one part, but not so much on another. To have the best of both worlds, I'm fumbling with settings.json a lot, but really I wish I could specify that per each config in `haxe.configurations`.

**Comment by Gama11** [comment]
Could you just use a manually defined build task for that other part? If it's not generated by vshaxe it won't have the `--connect`.

**Comment by back2dos** [comment]
I typically have things set up to always build the current configuration, because it's nice to just use one key stroke. If the choice is between having to select a task every time I hit build and editing settings.json every time I switch configuration, I think I'll stick to the latter ^^

**Comment by Gama11** [comment]
You can still have one key stroke, just a different one (you can give tasks direct shortcuts, or make one of them the "default test task" and use the shortcut for that).

**Comment by back2dos** [comment]
Yeah, that doesn't really scale with the number of configurations. And even for projects with just a handful of different configurations one has to remember the shortcut required to build the currently selected one. Anyway, I get the feeling I'm asking for something pretty tricky here, so I guess I'll just stick to my current "workflow" ;)

**Comment by Gama11** [comment]
Not necessarily tricky, it just seems extremely specific. I'm always a bit wary of adding features that are likely only useful to one person (Maybe there's other people that have this use case too though? Not sure.).

Perhaps this at least adds some incentive for trying to figure out what the problem with the compilation server is. 😬
