### ISSUE TITLE
Publishing to OpenVSX?

### ISSUE THREAD

**Issue by YevhenKap** [vshaxe/vshaxe#459]
Hello, everyone :) Are there plans to publishing an extension to [OpenVSX Registry](https://open-vsx.org/)?

**Comment by Gama11** [comment]
No, I think it's too niche for now to justify the effort of publishing all the extensions to two places separately. If I understand correctly, https://github.com/open-vsx/publish-extensions/pull/133 would take care of this anyway / automate it.

**Comment by GitMensch** [comment]
Hi @Gama11! OpenVSX already has its own publishing process, based on `vsce`.

The ideal version is to publish the extension(s) yourself with a single command, `npx ovsx publish` (no need to install any dependency), I'd say that's not so much effort.

The OpenVSX Registry is also the default extension provider for eclipse theia (which is used in gitpod, for example) and for vscodium so the niche is quite big already.
