### ISSUE TITLE
Running global diagnostics right away takes two attempts

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#46]
When using global diagnostics as an "acivation event" (use it as the first Haxe command after opening the VSCode window, before the extension has started up, see 0c558bb), it takes two attempts to work.

The first time, there's an empty response:

```
Haxe language server started
Processing Arguments [-version]
> 3.3.0 (git build development @ a847ec8)
Cached 0 modules
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
```

Only the second time, there are proper "parsed" messages and a completion response.

**Comment by nadako** [comment]
I can't reproduce it. Maybe I accidentally fixed this with https://github.com/vshaxe/haxe-languageserver/commit/3dcdcb0fc5e776bb9751d58928928d5867c0719a. Could you confirm?

**Comment by Gama11** [comment]
Hm... not sure if it was that commit, but it now works for me too! 👍
