### ISSUE TITLE
Inherited function documentation

### ISSUE THREAD

**Issue by justin-espedal** [vshaxe/vshaxe#460]
Functions should inherit documentation from superclasses/interfaces. This inherited documentation should be visible in the tooltip-like window when the function is hovered over, both at call sites and at the function declaration.

Here's how javadoc specifies where it copies inherited documentation from, for reference: [javadoc comment inheritance](https://docs.oracle.com/en/java/javase/15/docs/specs/javadoc/doc-comment-spec.html#comment-inheritance).

**Comment by Gama11** [comment]
Haxe 4.2 will have support for `@:inheritDoc` metadata, see https://github.com/HaxeFoundation/haxe/pull/9817.

**Comment by justin-espedal** [comment]
Will inheritDoc be implicit on all inherited functions? If so, sounds good to me. If not, I think this issue still has value in being left open.

**Comment by Gama11** [comment]
Not that I'm aware. Either way, that would be a Haxe, not a vshaxe issue - completion results, including doc comments, come directly from the compiler.

**Comment by justin-espedal** [comment]
Ah, I see. I was originally dissuaded from posting on the Haxe repo by [this comment](https://github.com/HaxeFoundation/haxe/issues/6270#issuecomment-303054900). I guess opinions change in three years.
