### ISSUE TITLE
Folding behaves incorrectly when inline markup literal contains a class attribute

### ISSUE THREAD

**Issue by elisee** [vshaxe/vshaxe#462]
Hi! Thanks for the nice VSCode extension.

The following code which contains an [inline markup literal](https://github.com/HaxeFoundation/haxe-evolution/pull/26):

```haxe
class First {
	static SRC = <test class="a"></test>

	function myfunc() {
	}
}

class Second {
}
```

currently folds down to

```haxe
class First { ⋯
}
``` 

eating the function definition and second class.

If the `class` XML attribute is replaced with a different string, then it works properly, but the `class` attribute is a pretty common keyword in any DOM-like inline markup.

**Comment by Gama11** [comment]
Inline markup in general isn't really supported in vshaxe, since the future of the feature is a bit unclear. https://github.com/HaxeFoundation/haxe-evolution/issues/60

**Comment by AlexHaxe** [comment]
vshaxe 2.25.0 should work with inline markup
