### ISSUE TITLE
Extern class with over 30k functions breaks intellisense

### ISSUE THREAD

**Issue by pawel-miczka** [vshaxe/vshaxe#463]
I have project where I want to create extern class with over 30k functions inside (or more) and I noticed that those declarations breaks intellisense. I don't get any hints when I want to use any of those declared functions. It looks like this:

![image](https://user-images.githubusercontent.com/5631954/96777358-8afc5600-13ea-11eb-9f36-52607efea439.png)

even when I know which function is inside I don't get any hint when I'm using this function:

![image](https://user-images.githubusercontent.com/5631954/96777474-aa937e80-13ea-11eb-889e-a5cd1a2841c1.png)

Only restarting Haxe language server helps. Code compiles without any problem btw.
Here is how it looks after language server restart:

![image](https://user-images.githubusercontent.com/5631954/96777714-f514fb00-13ea-11eb-9fa5-bc04731582fb.png)

**Comment by Gama11** [comment]
This issue is missing the source code to reproduce the problem and an error message (there might be something in the Haxe output channel: https://github.com/vshaxe/vshaxe/wiki/Troubleshooting).

**Comment by pawel-miczka** [comment]
Ye I'm kinda stupid. I forgot about ; at the end of every defined function so Haxe couldn't build cache :D .. 
Today I sat and wrote those functions once again and it works.

**Comment by pawel-miczka** [comment]
Seems like I found another bug. Here's mine extern class definition: https://github.com/pawel-miczka/mtasa-types/blob/master/src/mtasa/server/Functions.hx

if I want to use it as import 
```hx
import mtasa.server.Functions.*;
```

I get an error in output:
```
Error during server/invalidate Failure("Buffer.add: cannot grow buffer")
```

**Comment by Gama11** [comment]
That's from the Haxe compiler, not vshaxe.

**Comment by pawel-miczka** [comment]
I think I found problem. I am using HXML file and I have 2 separate folders: server and client. Inside HXML file I have:

```
--library mtasa-types

--class-path src
--dce full
-D lua-vanilla
-D lua-ver 5.1

--each

--main server.Main
--lua dist/server.lua

--next

--main client.Main
--lua dist/client.lua
```

and then inside server folder I have import.hx containing import mentioned before and it doesn't work but when I remove --next client element it works. So HXML file then looks like this:
```
--library mtasa-types

--class-path src
--dce full
-D lua-vanilla
-D lua-ver 5.1

--main server.Main
--lua dist/server.lua
```
but I really need those 2 separate builds

**Comment by pawel-miczka** [comment]
Don't understand why but when I switched client with server (in --each and --next closure) it started working ..

**Comment by Gama11** [comment]
Either way, that's not a vshaxe problem.
