### ISSUE TITLE
macro can't debug .

### ISSUE THREAD

**Issue by sonygod** [vshaxe/vshaxe#465]
Main.hx

	@:build(MyMacro.build())
	class Main {
		
	}

//----------------------+

    import haxe.macro.Context;
    import haxe.macro.Expr;

    class MyMacro {
        public static function build() {
            var fields = Context.getBuildFields();//can't jump breakpoint here.

            var c = macro class X {
                public static function main() {
                    trace("cc");
                }
            };
            fields.push(c.fields[0]);

            return fields;
        }
    }

//---build.hxml
     -cp src
    -D analyzer-optimize
    -main Main
    --interp

**Comment by Gama11** [comment]
What Haxe version are you using? For me it seems to work fine with 4.1.4,  but hangs with a nightly.

**Comment by sonygod** [comment]
haxe nightly version +1

**Comment by RealyUniqueName** [comment]
Works for me. But I'm using the release version of vshaxe.
