### ISSUE TITLE
Multiple "targets" in same .hxml file

### ISSUE THREAD

**Issue by filt3rek** [vshaxe/vshaxe#466]
Hej !

I have a .hxml file like that : 

```haxe
-lib ftk
--macro ftk.macro.Compiler.deleteRegexFiles( "www", "(app)([\\.0-9]*)(\\.min)*\\.js" )

--next

common.hxml

--macro ftk.macro.Compiler.setOutputFilenameByVersion()
--macro ftk.macro.Compiler.alignCSSVersion( "www", "(app)([\\.0-9]*)(\\.min)*\\.css" )
#--macro ftk.macro.Compiler.runTerserAfterCompilation()

Client

-js www/app.js
```
The first part is to cleanup some files and then after `--next` it's my real compilation target.
Doing that, in VSCode, my js parts (`#if js`) are grey/blurred. I suppose because the plugin take in account the first target found. But here there isn't really a target because there is no compilation output.

Maybe something could be done that the plugin doesn't take in account the part in the hxml  where there is no compilation please ?

Regards,
Michal

**Comment by Gama11** [comment]
> Maybe something could be done that the plugin [...]

No, this is all handled by the compiler.

**Comment by filt3rek** [comment]
Hej !

Is there a way to deactivate this feature please ? I mean that vshaxe does'nt fade the target that is not used please ?
I haven't found anywhere in options I don't know how call this feature...

**Comment by Gama11** [comment]
There's a `"editor.showUnused"` setting, though that affects more than just conditional compilation.

**Comment by filt3rek** [comment]
Hej Jens,

Thanks for your quick answer, I'll try that.

By the way, do you know how this is handled by the compiler please ? I wanted to write a haxe github issue to explain that and maybe someone could do that if there is no output target in a hxml file with several --next so it doesn't take it in account and so I could have many targets inside juste one hxml and vshaxe wouldn't fade the code parts as mentionned in this issue please ?

I don't know how to explain that, what is linked to, and If I write "Hi guys, there is an issue that do that if there is no output target specified in .hxml file, so vshaxe will fade the target code”, the guys will close the issue before ending reading." :rofl:

Thanks for your help !

**Comment by Gama11** [comment]
It's not really about the fading, you also won't get completion etc in those blocks. Hiding the fading just obscures that.

**Comment by filt3rek** [comment]
Thanks Jens,

I submitted this issue, I hope it's clear enough : https://github.com/HaxeFoundation/haxe/issues/9979

**Comment by AlexHaxe** [comment]
when working with multi-target projects (e.g. JS + PHP), I usually use one build.hxml and multiple display*.hxml files, one for each target. in vscode I use build.hxml as compilation target, and select one of the display files as my completion / languageserver file (via select box in status bar). 
that way you can select which target you currently work on, while still compiling everything through one compilation call.

it was mentioned by @RealyUniqueName in your post https://community.haxe.org/t/delete-www-directory-before-compilation/2730/8, but I guess it wasn't made clear, that you can use two different .hxml files at the same time.

**Comment by filt3rek** [comment]
Hej Alex,

Thanks for your answer.

I do the same, I have as many hxml files as targets and I have also a "common.hxml" that is used inside client.hxml and server.hxml and all that works fine.

But recently I added a "task" in my client.hxml file that is at the begining of the hxml that do some tasks like cleaning the directory and so on, and this is not really a target because there isn't any output. The output is in the --next part that is the js part.

i know I could have it in separate file but the goal was in fact to have it automation and not switch between my task and the client hxml, so running the client hxml it does it by itself. And that's here the problem because there is no output and in vshaxe my main js part is faded.

I don't know if it's clear... More I read back myself and more I want to murder someone lol

Best,
Michal

**Comment by AlexHaxe** [comment]
you only have to switch when you move targets, e.g. from JS to PHP or back.
let's assume you have `compileClient.hxml`:
```hxml
common.hxml
Client
-js www/app.js
```
and `build.hxml` (both shortened versions of your code):
```hxml
yourcleanup.hxml
--next
compileClient.hxml
```
then `build.hxml` is your VSCode "Default build task" and `compileClient.hxml` is your active Haxe configuration. that way you get your cleanup when compiling and you get JS code support and active JS code sections in editor.

when you move to work on server part you select `compileServer.hxml` as your Haxe configuration and change your default build task to `buildServer.hxml` (or keep it at `build.hxml` if that also builds server code).

switching between two targets is not automatic because at some point you have to tell VSCode and languageserver that you are now going to work on server portion of your codebase.
if you constantly switch between both sides that can be a bit tricky, because you only get completion and other services for one target not for both.

**Comment by filt3rek** [comment]
Hmmm between js and php it's ok it's 2 separate hxml files and all works fine for that.

But now, If I understand well, you mean I can have one hxml file for compiling and another one for completion ? And still have on the bottom left the possibility to switch between php and js compilation ?

**Comment by filt3rek** [comment]
Or maybe I've misunderstood and you suggest me to have 2 js files one with my cleanup for compilation and one the same but just without the cleanup part for completion. So I switch to the completion one for writing my code and to the compilation for compilation, right ?

**Comment by AlexHaxe** [comment]
yes, you will have to switch both manually when moving from e.g. JS to PHP. if you only work on your JS client you don't have to switch at all (unless there is more than one client.js, but even then you could get away with just one .hxml file for completion and one for compiling all .js files).

**Comment by filt3rek** [comment]
Ok, so no I haven't understood well.
I know I have to switch manually form php to js, it's normal.
But how can I have just one js hxml kind of splitted into 2 (one for completion without the cleaning part and another for compilation with the cleaning part) ? That is what I can't understand in your proposal.

**Comment by AlexHaxe** [comment]
build.hxml (for build task):
```hxml
-lib ftk
--macro ftk.macro.Compiler.deleteRegexFiles( "www", "(app)([\\.0-9]*)(\\.min)*\\.js" )

--next

--macro ftk.macro.Compiler.setOutputFilenameByVersion()
--macro ftk.macro.Compiler.alignCSSVersion( "www", "(app)([\\.0-9]*)(\\.min)*\\.css" )
#--macro ftk.macro.Compiler.runTerserAfterCompilation()

client.hxml
```

client.hxml (for completion):
```hxml
common.hxml

Client

-js www/app.js
```

**Comment by filt3rek** [comment]
Ok so I have also to switch manually between build.hxml and client.hxml right ?
Or maybe there is something I missed about "build task"... I'm sure it's that...

**Comment by AlexHaxe** [comment]
`build.hxml` is what you set in menu "Terminal -> Configure Default Build Task…" (or if you don't use default build task: what you select everytime you press Ctrl+Shift+B or whatever key your build command is bound to), `client.hxml` is what you set in your status bar bottom leftish in that hxml selector thingy. 
as long as you work on client.js you don't have to switch anything, that combination can and will stay as it is for as long as you need.

you only switch when you work on something different inside your project. if JS is all you do in your project, than you set it up once and whenever you reopen your project everything should be as you left it.
