### ISSUE TITLE
"Initialize VS Code project..." generates invalid json with only one hxml

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#47]
If there's only one build.hxml, the command generates this:

``` js
{
    // These are configurations used for haxe completion.
    //
    // Each configuration is an array of arguments that will be passed to the Haxe completion server,
    // they should only contain arguments and/or hxml files that are needed for completion,
    // such as -cp, -lib, target output settings and defines.
    "haxe.displayConfigurations": [
        ["build.hxml"], // if a hxml file is safe to use, we can just pass it as argument
        // you can add more than one configuration and switch between them
        //["build-cpp.hxml"]
    ]
}
```

Notice the trailing comma after `["build.hxml"]`. This leads to a "Value expected" error when viewing the file in VSCode.

If there are two `.hxml` files, the generated json is valid:

``` js
{
    // These are configurations used for haxe completion.
    //
    // Each configuration is an array of arguments that will be passed to the Haxe completion server,
    // they should only contain arguments and/or hxml files that are needed for completion,
    // such as -cp, -lib, target output settings and defines.
    "haxe.displayConfigurations": [
        ["build.hxml"], // if a hxml file is safe to use, we can just pass it as argument
        // you can add more than one configuration and switch between them
        ["build.1.hxml"]
    ]
}
```

**Comment by Simn** [comment]
I think that happens only if the file name is exactly `build.hxml`.

**Comment by Gama11** [comment]
I don't think so, I just tried with `test.hxml`, same thing.

**Comment by nadako** [comment]
But it's a valid JSON for vscode...

**Comment by nadako** [comment]
But yeah, maybe we should be smarter than that and use that cjson library to generate a proper commented json.

**Comment by Gama11** [comment]
It is? For me it displays this error:

![](http://i.imgur.com/aUmXHvf.png)

**Comment by nadako** [comment]
Yeah, but it still works :) Anyway, I kind of want vscode to provide API for working with these JSONs. There's a [parser library](https://github.com/Microsoft/node-jsonc-parser), but it doesn't handle writing and doing that ourselves doesn't sound right to me...
