### ISSUE TITLE
incomplete completion - not found why yet

### ISSUE THREAD

**Issue by nulld** [vshaxe/vshaxe#471]
![image](https://user-images.githubusercontent.com/2820168/101386061-b02b2200-38cd-11eb-966c-26f76482f6b9.png)

**Comment by nulld** [comment]
Tried to reproduce this in minimal sample, but it's become worse. Do not know why I'm so unlucky :)
![image](https://user-images.githubusercontent.com/2820168/101404780-29d00980-38e8-11eb-9ec1-99ae099ad42f.png)
hope this helps somehow: [issue471.zip](https://github.com/vshaxe/vshaxe/files/5655248/issue471.zip)

**Comment by nadako** [comment]
The second example doesn't work because `getCtx` is not static and you are trying to access it from a static method. Maybe it should still provide completion in this case? What do you think @Simn @Gama11?

Regarding the first one - needs more info :)

**Comment by nulld** [comment]
>  is not static and you are trying to access it from a static method
Ok, got it. 

> Regarding the first one - needs more info
Will try to pick up sample for first problem tomorrow. It happens quite often on our big project, but not found consistent pattern yet.

**Comment by nulld** [comment]
Changed method to static in sample attached above and voila!
![image](https://user-images.githubusercontent.com/2820168/101469685-1d829580-3956-11eb-8b59-b300d951042e.png)
(as you see on screen only one field from `TAutoGenContext` shown)

**Comment by nulld** [comment]
I'm very sorry, seem that completion I shrinked completion window somehow, LOL.
![image](https://user-images.githubusercontent.com/2820168/101483204-e10c6500-3968-11eb-8bfc-c55b1ab663fc.png)
