### ISSUE TITLE
Support for types in function comments (coloring & code clarity)

### ISSUE THREAD

**Issue by Kyliathy** [vshaxe/vshaxe#472]
Here's a cosmetic quality of life improvement I propose.

Currently, if I write `@param name Some comment`, the `name` will be color-coded. 

If I write `@param {String} name Some comment`, I lose the coloring for `name` and also the `{type}` is not colored. 

Would be nice if vshaxe would be aware of how types are handled in function comments, as this could improve code readability and navigation. Currently, if I use proper type comments in the same format I use in TypeScript (which is my inspiration for this feature request), the argument name is bundled with the description:

![image](https://user-images.githubusercontent.com/20860173/101470145-79b7cc00-38fa-11eb-9a15-7591255af8e8.png)

**Comment by nadako** [comment]
Why do you want to specify types in the comments like that when you have typehints in the language? It's redundant and prone to be outdated.

**Comment by Kyliathy** [comment]
Hi @nadako and thank you for such a lightning answer :).

The main reason is generation of documentation. 

(not to ask you "Why does TypeScript do it?". Also, in an ideal world, refactoring would also change the types in the curly brackets, as this is technically possible. I think some IDEs even handle that, but baby steps :)

**Comment by Gama11** [comment]
I agree with nadako, you shouldn't do this in Haxe. Dox can do this fine without having redundant information in the sources.

**Comment by Kyliathy** [comment]
That's was fast. Fast like shutting down the computer by keeping the button pressed :D LOL.

**Comment by nadako** [comment]
> in an ideal world, refactoring would also change the types in the curly brackets

I think this is a made up problem (or rather, dragged from dynamically typed JS for no reason) and in ideal world we wouldn't have redundancy :)
