### ISSUE TITLE
Usage with other editors implementing LSP

### ISSUE THREAD

**Issue by KOLANICH** [vshaxe/vshaxe#477]
Hi. It'd be nice to use it with other editors implementing LSP. Such as Kate and Qt Creator. Of course, without NPM and Node.js, it should be transpiled into a C++ source and then compiled into a native binary for that.

**Comment by Gama11** [comment]
The language server uses native node.js APIs right now, and that's not likely to change until the new asys APIs make it into the Haxe standard library. Regardless, I don't see the problem with using a Node version of it.
