### ISSUE TITLE
Metadata completion is canceled on ":"

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#48]
As long as you don't type the `:`, meta completion works:

![](http://i.imgur.com/052ZCoA.gif)

However, `:` seems to cancel completion for some reason / closes the completion list:

![](http://i.imgur.com/sqTjXv9.gif)

**Comment by Simn** [comment]
Is this something we can fix or are we gonna need MS support?

**Comment by Gama11** [comment]
No idea, need to find out why it happens in the first place..

**Comment by Gama11** [comment]
Opened an issue on the vscode repo: https://github.com/Microsoft/vscode/issues/12772

**Comment by Gama11** [comment]
Ok, got an answer. This works:

```haxe
var defaultWordPattern = "(-?\\d*\\.\\d\\w*)|([^\\`\\~\\!\\@\\#\\%\\^\\&\\*\\(\\)\\-\\=\\+\\[\\{\\]\\}\\\\\\|\\;\\:\\'\\\"\\,\\.\\<\\>\\/\\?\\s]+)";
var wordPattern = defaultWordPattern + "|(@:\\w*)"; // metadata
languages.setLanguageConfiguration("haxe", {wordPattern: new js.RegExp(wordPattern)});
```

...except that completion is still canceled on `:` because we have that as a trigger character (type hints) - not sure if we can do anything about that. :/

To me, the `triggerCharacters` docs suggest that there might be a way to trigger completion manually (as they explicitly say "automatically"):

>The characters that trigger completion automatically.

**Comment by Simn** [comment]
Does it also cancel if we `reject` in `onCompletion`?

**Comment by Gama11** [comment]
Looks like it. Also, even if that worked, it'd seem a bit hacky, since you have to reject it with some error message which is then printed to the output.

**Comment by Gama11** [comment]
The flickering when the completion list is closed and reopened is frankly a bit annoying, but I guess we can (have to?) live with that.
