### ISSUE TITLE
Autocomplete for module level statics can show the wrong documentation

### ISSUE THREAD

**Issue by haxiomic** [vshaxe/vshaxe#480]
![Screen Recording 2021-03-09 at 21 46 53](https://user-images.githubusercontent.com/3742992/110542898-8a5a2700-8121-11eb-9e21-e656b5db194b.gif)

Repro 
[vscode-doc-bug.zip](https://github.com/vshaxe/vshaxe/files/6111632/vscode-doc-bug.zip)

**Comment by Gama11** [comment]
That would be a compiler issue.

**Comment by haxiomic** [comment]
Gotcha, will move to there!
