### ISSUE TITLE
Mis-diagnostic of unused import

### ISSUE THREAD

**Issue by ciscoheat** [vshaxe/vshaxe#485]
In the [SnakeDCI](https://github.com/ciscoheat/SnakeDCI) project, probably due to the heavy macro rewriting that occurs in the [DCI library](https://github.com/ciscoheat/haxedci), some fields in a class gets marked as unused import:

![2021-03-27 09_13_48-Movement hx - SnakeDCI - Visual Studio Code](https://user-images.githubusercontent.com/130450/112714844-c7be0300-8edc-11eb-9278-2fe80b069641.png)

([code location](https://github.com/ciscoheat/SnakeDCI/blob/master/src/contexts/Movement.hx#L93))

The field `HEAD` is used throughout the class, but it's rewritten as `MovementHEAD`, which could cause some confusion. Fixing that could be a deeper issue, but should the diagnostics even occur for class fields, when the error message says "unused import/using"? 

Or if there is a valid use case for it, is there a way to at least change the color back to normal of this "unused" large part of the code?

**Comment by Gama11** [comment]
Diagnostics come from the compiler.

**Comment by ciscoheat** [comment]
Will post there instead.
