### ISSUE TITLE
"haxelib.executable" config node not working (anymore?)

### ISSUE THREAD

**Issue by tpr-evilempire** [vshaxe/vshaxe#486]
my settings.json has the following setup : 
```
{
 "haxelib.executable":  ".haxe\\haxelib.exe",
    "haxe.executable": {
        "windows": {
            "path": ".haxe\\haxe.exe",
            }
        },
...
}
```

But I'm having the following error : 

> Using --server-connect
> Haxe connected!
> Listening on port 6001
> Failed - try fixing the error(s) and restarting the language server:
> 
> Error: 'haxelib' is not recognized as an internal or external command,

I remember to have it working few months ago. 
Can anyone here help me to make local haxelib great again please?

Thanks !

**Comment by Gama11** [comment]
@dpomier Could this be related to your changes?

**Comment by tpr-evilempire** [comment]
This is tested with an haxe 4.0.2 version if that does help.

**Comment by tpr-evilempire** [comment]
Version 2.21.4  seems to works correctly FYI

**Comment by dpomier** [comment]
Sorry for the late reply. I could not reproduce it just with the same `settings.json`. @tpr-evilempire would you be able to make a reproductive sample? Are you using a completion provider (e.g. VSCode plugin for Lime or Kha)?

**Comment by tpr-evilempire** [comment]
At the moment I don't have the time but I'll try.
For the completion, nothing very specific.  Hashlink debugger is what we
need in addition to the vscode plugin, that's all. I'm using completion
server delivered by haxe as well of course.


<https://evilempirestudio.com/>

Thomas PFEIFFER

CTO @EvilEmpire

Mail: ***@***.***


Le lun. 12 avr. 2021 à 12:07, Dimitri Pomier ***@***.***> a
écrit :

**Comment by dpomier** [comment]
After some more testing, I've somehow managed to get a Lix environment where the completion server fails to resolve libraries starting from vshaxe/haxe-language-server@41dbb4b159cdaacbd5dab8909d7bb9d021d3b7fb (fc8383789cac944ac5949e8b2fc8b23e45ca4538). However, I don't know if this is somewhat related to your case.

**Comment by tpr-evilempire** [comment]
Sorry for the delay, didn't forget, but time is missing at the moment. I'll do some more testing soon...
