### ISSUE TITLE
Hover hints broken for some files.

### ISSUE THREAD

**Issue by ghost** [vshaxe/vshaxe#492]
It seems the [hover hints](https://github.com/vshaxe/vshaxe/wiki/Hover-Hints) feature inexplicably does not work in some `.hx` files. 

You will see the feature broken on `PlayState.hx` below:

https://user-images.githubusercontent.com/46636455/117823740-a746cf80-b222-11eb-94e4-6732705f2be3.mp4

Since the last two files are part of the same repository, it's not a repository-specific problem. Nor is the problem specific to override functions (I tried it on another function in `PlayState.hx`). I tried reinstalling the extension, no dice. Here are my other extensions, although all of them are disabled:
![2021-05-11 06_26_18-● PlayState hx - repos - Visual Studio Code](https://user-images.githubusercontent.com/46636455/117823013-e163a180-b221-11eb-8455-05c96ff8f0c1.png)

I hope this is a simple oversight on my part with a simple fix, because the feature has been invaluable for me poring through this codebase from scratch with zero Haxe experience.

**Comment by Gama11** [comment]
Check the output channel for errors.

https://github.com/vshaxe/vshaxe/wiki/Troubleshooting

**Comment by timmybusiness** [comment]
> 
> 
> Check the output channel for errors.
> 
> https://github.com/vshaxe/vshaxe/wiki/Troubleshooting
Thank you so much, @Gama11. Indeed there is an error whenever the hover does not appear, and an apropos one at that.
```[Error - 6:58:23 AM] Request textDocument/hover failed.
  Message: Type not found : Paths
  Code: -32603 ```

Somewhat vexingly, I can create another function in the problematic file and, after loading for about four seconds, it identifies the type correctly. Variables in the problematic function, while loading the same amount, trigger that error after `Loading...` disappears.
![2021-05-11 06_58_41-● PlayState hx - repos - Visual Studio Code](https://user-images.githubusercontent.com/46636455/117828556-c3e50680-b226-11eb-8e68-0ffe4c422f38.png)

**Comment by timmybusiness** [comment]
I had moved on, then unwittingly closed the workspace and created a new one; and hover hints works once more. No clue why it broke in the first place, but this solution satisfies me enough to mark the issue as closed.
