### ISSUE TITLE
compile error in lix projects

### ISSUE THREAD

**Issue by tjrhodes** [vshaxe/vshaxe#494]
Hi,

I've been trying to get to the bottom of this error:

```
Executing task: haxe --connect 6000 compile.hxml

The terminal process failed to launch: Path to shell executable "haxe" is not a file of a symlink.
```
When trying to compile with the haxe extension in vscode, in a terminal I can run...

`haxe --connect 6000 compile.hxml`

...with no problem. 'lix compile.hxml' also works. When I run 'which haxe' it gives me the path to the folder inside .nvm which seems right:

`/home/tom/.nvm/versions/node/v15.14.0/bin/haxe`

When I go to that folder the symlink is there and points to

`../lib/node_modules/lix/bin/haxeshim.js`

which looks good to me.

Everything I can find about similar errors looks to be to do with $PATH, but echo $path gives me

`/home/tom/.nvm/versions/node/v15.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

aaaand 'node -v' gives me 15.14.0. So that matches up too. Is the vscode haxe extension not running it's command from the same path?!

Thanks for any insight into this, it's not the first time I've had it happen and this is a relatively fresh install of pop os where I've installed everything as per the instructions.

Cheers, Tom.

**Comment by Gama11** [comment]
Do you have the lix vscode extension installed?

**Comment by tjrhodes** [comment]
Yep I do.

**Comment by tjrhodes** [comment]
Thanks Gama11, I had been making a folder, running lix scope create and then dragging that folder into vscode, ctrl+p then 'lix' and initialize project using the extension fixed it.
