### ISSUE TITLE
Suggested Expressions

### ISSUE THREAD

**Issue by User7711** [vshaxe/vshaxe#497]
Hello!

I love working with haxe in VScode and it's probably the best options for haxe. But on every statement it always wants to suggest some basic expressions.

![suggestions](https://user-images.githubusercontent.com/34722701/123382792-a7145080-d592-11eb-984a-fe6f9c1102b8.png)

I was wondering if there is an options to turn this off?

**Comment by AlexHaxe** [comment]
those are [postfix completion](https://github.com/vshaxe/vshaxe/wiki/Postfix-Completion) options. 
turn them off with:
```json
 "haxe.postfixCompletion": {
 	"level": "off"
 }
```

**Comment by User7711** [comment]
Works! Thanks a lot mate!
