### ISSUE TITLE
Cannot build language-server from source

### ISSUE THREAD

**Issue by sebthom** [vshaxe/vshaxe#500]
I tried to follow the steps at https://github.com/vshaxe/haxe-language-server#building-from-source

But all I am getting is:

```
D:\haxe-language-server> npx lix run vshaxe-build -t language-server
Neko seems to be missing. Attempting download ...
-> Done!
done
Version 4.2.0 configured in D:\haxe-language-server/.haxerc does not exist. Attempting download ...
Looking up Haxe version "4.2.0" online
  Resolved to official release 4.2.0. Downloading ...
Downloading Haxe: official release 4.2.0
-> Done!
  ... download complete!
Failed to get content of C:\Users\John/haxelib.json
Failed to invoke `haxelib run-dir vshaxe-build C:\Users\John Doe\AppData\Roaming/haxe/haxe_libraries/vshaxe-build/0.0.1/github/39ab9c6315ae76080e5399391c8fa561daec6d55 -t language-server` 
  because Error: Command failed: haxelib run-dir vshaxe-build C:\Users\John Doe\AppData\Roaming/haxe/haxe_libraries/vshaxe-build/0.0.1/github/39ab9c6315ae76080e5399391c8fa561daec6d55 -t language-server
```

What to do?

**Comment by Gama11** [comment]
Not sure why it would be looking for a haxelib.json in your home directory. Most likely an issue with lix?

**Comment by sebthom** [comment]
@Gama11 It was a whitespace issue in the path. I created a PR.

Now I can start the server on the command line, but how can I pass a config file to it?

**Comment by Gama11** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeConfiguration

https://github.com/vshaxe/haxe-language-server/blob/master/src/haxeLanguageServer/Configuration.hx
