### ISSUE TITLE
haxe-language-server: Unhandled method textDocument/completion

### ISSUE THREAD

**Issue by sebthom** [vshaxe/vshaxe#501]
I am trying to integrate haxe-language-server with another IDE (Eclipse).

For some client requests I however get errors from the server:
```json
{"jsonrpc":"2.0","id":"6","error":
  {"code":-32601,"message":"Unhandled method textDocument/completion"}
}
{"jsonrpc":"2.0","id":"4","error":
  {"code":-32601,"message":"Unhandled method textDocument/hover"}
}
```

Are those methods not implemented yet or did I not configure the haxe-language-server right?

**Comment by Gama11** [comment]
You're most likely running into https://github.com/vshaxe/vshaxe/issues/359 - basically, the Haxe language server only starts the Haxe server process after the first `onDidChangeConfiguration` event.

**Comment by sebthom** [comment]
That solved it, thanks!
