### ISSUE TITLE
Why are there so many repeated tips

### ISSUE THREAD

**Issue by ocd-lab** [vshaxe/vshaxe#504]
![image](https://user-images.githubusercontent.com/79586594/132123063-9609085f-8a37-48e3-8753-9c6b88001d91.png)

**Comment by Gama11** [comment]
Not sure, VSCode bug? I don't see how vshaxe could be to blame.

**Comment by ocd-lab** [comment]
Yep I'm not sure too,Every time  when I run the cmd "hl xxxx.hxml" ,the tip add a one.

**Comment by ocd-lab** [comment]
Here we are all the extensions I installed about haxe
![image](https://user-images.githubusercontent.com/79586594/132134270-73dc4d64-0597-4eda-a7aa-9f3c760c344d.png)

**Comment by Gama11** [comment]
@ocd-lab Did you manage to find a solution?
