### ISSUE TITLE
Null safety errors highligting

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#509]
```haxe
@:nullSafety(StrictThreaded)
class Main {
	static function main() {
		var a = 1;
		// a = null;
	}
}
```
If you build project, uncomment `// a = null;` and build project again, there is no "red lines", only compilation error in console. Reload window with uncommented line, build and you will see error in editor.

**Comment by RblSb** [comment]
Magically fixed at some moment

**Comment by GHanehoj** [comment]
I cannot reproduce this fix. Using haxe 4.2.5 and the latest vshaxe (2.23.3), the example above is not marked with a red error when the line is uncommented.

I spoke with RblSb, and they can not get it to work either. Can we reopen this issue?

**Comment by RblSb** [comment]
I cannot reproduce the problem, but ok

**Comment by GHanehoj** [comment]
Oh ok my bad. Could you send your version numbers and possibly settings.json file?

**Comment by RblSb** [comment]
Hm, are you sure you not to forgot to build project to get null safety errors? This issue is not about "no null-safety errors on haxe file save", but about "no null-safety errors on haxe build command", first one is here btw:
https://github.com/HaxeFoundation/haxe/issues/7933

**Comment by GHanehoj** [comment]
I see, my bad. I am indeed talking about the former issue, didn't realise there was a mismatch. Sorry, and thanks for the link!
