### ISSUE TITLE
Syntax highlight broken when skipping curly braces

### ISSUE THREAD

**Issue by gene-pavlovsky** [vshaxe/vshaxe#527]
This code breaks syntax higlighting:
`performerId.bind(function (v) trace('performerId=${v}'));`

The following code doesn't:
`performerId.bind(function (v) { trace('performerId=${v}'); });`

Result:
![Screenshot 2022-05-25 at 11 53 26](https://user-images.githubusercontent.com/2841193/170235246-5d8df9e3-870d-4294-95cf-db26df9f0e85.png)

**Comment by kLabz** [comment]
Btw it also breaks on github; I don't remember exactly what lib is handling that but might be worth fixing there too.

```haxe
performerId.bind(function (v) { trace('performerId=${v}'); });

performerId.bind(function (v) trace('performerId=${v}'));
performerId.bind(function (v) trace('performerId=${v}'));
```

**Comment by Gama11** [comment]
https://github.com/vshaxe/haxe-TmLanguage/issues/19
