### ISSUE TITLE
Error messages not visible when hovering

### ISSUE THREAD

**Issue by lucidfext** [vshaxe/vshaxe#53]
I don't know why, but sometimes when I hover my mouse to a red underlined codes,
I got no error message at all. It just shows me the type info.
But with obvious error like using undefined variable in that line, it underlines again to that word and shows me the error message.
When I try same code at try.haxe.org, it actually shows me right error message.

What would be the problem?

+I think this occurs when the error is related to generics

**Comment by Gama11** [comment]
There were some issues with clearing old error messages which I think @nadako fixed. If that's the same issue, this is probably already fixed on the dev branch.

If you want to try with that, there are some instructions for setting up vshaxe from source here: https://github.com/vshaxe/vshaxe#hacking

You'd also need a nightly build of Haxe.

Other than that, the next vshaxe is waiting on a Haxe release right now I think, so you'd have to wait until then.

**Comment by lucidfext** [comment]
Thank you for the information. Can you tell me when the next Haxe release will be?

**Comment by Gama11** [comment]
I don't know, soon-ish hopefully? I don't think there's a set release date.

**Comment by Gama11** [comment]
vshaxe 1.0.0 has been out for a while now, so this is probably fixed. Feel free to reopen if you're still experiencing that issue though.
