### ISSUE TITLE
Markup literals break breadcrumbs

### ISSUE THREAD

**Issue by Speedphoenix** [vshaxe/vshaxe#538]
When editing code that uses markup literals (like [domkit](https://github.com/HeapsIO/domkit) on the Heaps game engine), the breadcrumbs are not nested properly.  
For example here the caret is not inside classes `A` or `B` but they still show up in the breadcrumbs
![image](https://user-images.githubusercontent.com/22801009/184843266-7138888b-8bb7-4cec-88b0-b37213cf2ae6.png)

For files with a large amount of classes with markup literals, the breadcrumbs become completely unusable, requiring a lot of scrolling to reach the bottom of the nesting

**Comment by AlexHaxe** [comment]
currently there is no support for XML literals in haxeparser or tokentree libs. and I believe that is where breadcrumb info comes from. 
it's also the reason why there is no formatting support for files containing such inline markup.

**Comment by AlexHaxe** [comment]
fixed by faaa3a9bdc1e60a67a98a8a860830d1e63f72092
