### ISSUE TITLE
Does not work..

### ISSUE THREAD

**Issue by hopewise** [vshaxe/vshaxe#54]
I have just installed it, I am on openFL project, but it seems that the extension is not working, no completion, no goto definition.. 

Any idea what to check?

**Comment by Gama11** [comment]
Did you select a .hxml file for completion? https://github.com/vshaxe/vshaxe#framework-notes

Are you using Haxe 3.3.0-rc1 or higher?

**Comment by hopewise** [comment]
I didn't select .hxml file for completion, actually my project has no .hxml file
Yes, I am using haxe 3.3.0-rc1

**Comment by Gama11** [comment]
That's why I linked to the framework notes, it describes how you can get Lime to generate one.

Alternatively, you can also use one of the .hxml files Lime generates on build, for instance `Export/flash/haxe/debug.hxml`.

**Comment by hopewise** [comment]
So, once I have .hxml file, completion, and goto definition will just work?

**Comment by Gama11** [comment]
Once you add it to `haxe.displayConfigurations`, yes: https://github.com/vshaxe/vshaxe#configuration

**Comment by hopewise** [comment]
Thanks, I also found this useful link to edit the `settings.json` that I didn't know about: https://code.visualstudio.com/docs/customization/userandworkspace

**Comment by Gama11** [comment]
Have you managed to get completion to work? Can this be closed?

**Comment by hopewise** [comment]
I have updated the settings.json that is at the user level, and I've took a `debug.hxml` from `Export/flash/haxe/debug.hxml` but I've noticed that the autocomplete will list every thing, not restricted to the class members it self.. I am not sure as I didn't have the time, I will check again..

**Comment by trsh** [comment]
Same for me.

**Comment by kevinresol** [comment]
Basically you don't need to edit settings.json manually.

Just follow the framework notes, i.e. generate the hxml with the command `haxelib run lime display linux > completion.hxml`. Then Cmd+Shift+P on code and type `init haxe`. Then things should work already.

It worked on my project.

**Comment by Gama11** [comment]
Closing this, since it was probably just a configuration issue.

#18 should make setup with OpenFL a bit less painful in the future.
