### ISSUE TITLE
Don't work links of compiler error in terminal.

### ISSUE THREAD

**Issue by gyfak** [vshaxe/vshaxe#541]
1)Run task to build haxe code with error;
2)Get Task has error - "--- .hx:262: characters 76-115 : Void should be Float" for example;
3)Click + Ctrl on link in terminal "--- .hx:262"
4)It will be open a file "--- .hx", but on 1 line, not 262

**Comment by AlexHaxe** [comment]
is `--- .hx` an actual filename or just your way of anonymising?
can you provide a full / reproducible example of your issue?

**Comment by gyfak** [comment]
src/SlotGarage.hx:262: characters 34-73 : Void should be Float
it can be any file with error. links didn't work.

**Comment by AlexHaxe** [comment]
I assume it's fixed since vscode issue was closed ages ago.
