### ISSUE TITLE
Syntax highlighting flickering all the time in .hx files, prompt to save whenever I close unedited hx file.

### ISSUE THREAD

**Issue by increpare** [vshaxe/vshaxe#551]
Type: <b>Bug</b>

Load a .hx file
Hit save once
Notice at the top of the file that the syntax highlighting is flickering every frame on and off. [ This should not happen ]
Try to close the .hx file
Note the confirmation warning that the file has been modified, even though I've not changed anything (and, to my knowledge, that nothing has been changed).

-----

I've spent a couple of hours looking into this, turning on/off various extensions, fiddling with settings.  It doesn't happen in all haxe projects I have, and I haven't managed to narrow it down to a single reproducable test case yet.  Also the minimap goes mental during the flickering, if it's turned on.

I've also noticed that the flickering just happens at the top of the file.  This sounds like maybe some highlighting process is being restarted before it's made it all the way down the file?

I've tried out older versions of the haxe extension and there's a problem there as well.  I tried uninstalling the "lime"/"haxe expansion pack" extensions and it didn't make a difference.  I tried upgrading haxe from 4.2.4 to 4.2.5 and there's no difference.  Syntax highlighting seems to be working without problems in projects in other languages. 

I'm sorry I don't have a decent test case, but I hope the report is useful.

Extension version: 2.25.0
VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|64.00GB (4.17GB free)|
|Process Argv|--crash-reporter-id af05855a-1d21-452f-83bb-fd0fc0af12d1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
iaj6b796:30602301

```

</details>

**Comment by increpare** [comment]
YES this worked around the bug.  It was ... well, I'll spare you the length story of the emotional arc of my day, 😅 Thanks so much for the quick reply!  I'll close it because it's a VS code bug rather than in vshaxe.

**Comment by AlexHaxe** [comment]
please update to vscode version 1.73.1
