### ISSUE TITLE
Error: No completion point was found

### ISSUE THREAD

**Issue by ClintFlames** [vshaxe/vshaxe#552]
Error appears when file begins with one line comment.
Main.hx
```haxe
//
class Main {
	static function main() {
		trace("Test!");
	}
}
```

build.hxml
```hxml
--dce full
--debug

--main Main
--hl bin/main.hl
```

**Comment by AlexHaxe** [comment]
sorry, can't reproduce. there must be a hidden step, that I don't see. 
please provide more information: e.g. OS, Haxe version, vshaxe version, vscode version, steps to reproduce.

**Comment by ClintFlames** [comment]
OS: Manjaro Linux
Haxe version: 4.2.5
vshaxe version: 2.25.0
Code OSS version: 1.72.1
Steps to reproduce:
1) Create and open folder in vscode
2) Add `build.hxml` with content:
```hxml
--main Main
--hl build/main.hl
```
3) Add `Main.hx` with content:
```hx
//
class Main {
	static function main() {
		
	}
}
```

P.S: every extension except Haxe and HashLink Debugger was turned off.

**Comment by AlexHaxe** [comment]
vscode 1.73.1, Haxe 4.2.5, Ubuntu 20.04, vshaxe 2.25.0. still can't reproduce:
![Screenshot_20221110_114348](https://user-images.githubusercontent.com/7204032/201070576-7891d98f-b44b-4cb0-8055-910b78fc0d7c.png)

**Comment by ClintFlames** [comment]
Somehow it fixed, forget to close issue
