### ISSUE TITLE
Strange import blinking after file save. Possible organize imports bug. 

### ISSUE THREAD

**Issue by djaonline** [vshaxe/vshaxe#553]
Hello! I can see import blinking and can't close file after file saving. My stuff:
linux
haxe 4.0.5, 4.2.5
vscode 1.73
vshaxe 2.25.0
settings.json: 
```
"editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
```
![vshaxe-org-imports-bug](https://user-images.githubusercontent.com/109904910/200662909-6412ac33-c80c-4130-8c65-c574846f27d0.gif)

**Comment by AlexHaxe** [comment]
see https://github.com/vshaxe/vshaxe/issues/551

**Comment by AlexHaxe** [comment]
please update to vscode version 1.73.1
