### ISSUE TITLE
Disable inlay hints in extension config by default

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#555]
I have feeling that there is many same questions every month about how to disable it. This feature is digged in settings and can be annoying to find and disable for new people.
If there is no much "inlay hints enabled by default" in other language extensions, lets probably hide or disable it for new users too. Overriding to "off" in extension config for Haxe language should be ok.

**Comment by Gama11** [comment]
Right, I didn't even remember that [configurationDefaults](https://github.com/vshaxe/vshaxe/blob/master/package.json#L822) is a thing... That's probably a good idea.
