### ISSUE TITLE
Auto-complete is only showing metadeta in single quote statements

### ISSUE THREAD

**Issue by Jarrio** [vshaxe/vshaxe#56]
On the newest vshaxe when using single quotes it presents only metadeta for class methods

Code to reproduce:
`var test = new class();`
`trace('var: ${test.}');`

[Gif demonstration](https://puu.sh/rWATk/3aca635b31.gif)

**Comment by Gama11** [comment]
Reported to Haxe: https://github.com/HaxeFoundation/haxe/issues/5775
