### ISSUE TITLE
[haxe-language-server] [rename] error: could not find identifier to rename

### ISSUE THREAD

**Issue by sebthom** [vshaxe/vshaxe#569]
When trying to rename any variables (using the latest version from the github repo) the following error is displayed:
```
[rename] error: could not find identifier to rename
```

This is the communication between LSP Client and the haxe-language-server:
```js
CLIENT >> {"jsonrpc":"2.0","id":"2","method":"textDocument/prepareRename","params":{"textDocument":{"uri":"file:///D:/test/src/Game.hx"},"position":{"line":21,"character":14}}}
SERVER >> {"jsonrpc":"2.0","id":"2","result":{"range":{"start":{"line":21,"character":10},"end":{"line":21,"character":17}},"placeholder":"playerB"}}
CLIENT >> {"jsonrpc":"2.0","id":"12","method":"textDocument/rename","params":{"newName":"playerC","textDocument":{"uri":"file:///D:/test/src/Game.hx"},"position":{"line":21,"character":14}}
SERVER >> {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[rename] error: could not find identifier to rename"}}
```

This is an example from the paper/scissors game found on the haxe.org front page where I try to rename the playerB variable.

**Comment by AlexHaxe** [comment]
works just fine, what's your setup?
![20230306_refactor_playerB](https://user-images.githubusercontent.com/7204032/223199279-eb934634-5559-4335-b3ed-c2e2b06a7459.gif)

**Comment by sebthom** [comment]
I am using the language server with another editor. https://github.com/haxe4e/haxe4e/

**Comment by sebthom** [comment]
I cannot even find the error message `could not find identifier to rename` I get back from the language server in the language-server source code. So I am a bit puzzled.

**Comment by AlexHaxe** [comment]
https://github.com/HaxeCheckstyle/haxe-rename/blob/3ee9704e455f2ab0ddae03097a872243b9995bd8/src/refactor/PrintHelper.hx#L53

have you checked known issues of rename function on https://github.com/vshaxe/vshaxe/wiki/Rename-Symbol?

**Comment by sebthom** [comment]
The file is in the src folder and the file is saved to disk. Is the code responding to `textDocument/prepareRename` different to `textDocument/rename` in determining the identifier to rename?

**Comment by AlexHaxe** [comment]
there is only one additional `NotFound` between `canRename` and `rename` API calls and that is a check if `toName` equals  identifier name. other than that `canRename` looks at the same identifiers as `rename`.

however there is a cache involved where files and identifiers are kept in memory to avoid constant reparsing of all files. size or modification time should trigger an invalidation of things cached from that file.

**Comment by AlexHaxe** [comment]
regarding 1. that explains why `rename` runs into a `NotFound` when `canRename` doesn't

in general `canRename` only needs to determine if a position is a valid identifier for a rename operation. so it only needs to look at current file.
I agree that maybe `onPrepareRename` should be made to only allow files from `renameSourceFolders`, so it could deny rename operations for files outside of these, because it's unlikely they succeed.

**Comment by sebthom** [comment]
I fixed the issue in  vshaxe/haxe-language-server#86 The problem is that the method `refactor.discover.TraverseSources.traverseSources(srcFolders, usageContext);` used in **onRename** expects that the current workdir is the same as `context.workspacePath` which is another assumption that is not guaranteed. so it always returns an empty list of files ultimately resulting in `could not find identifier to rename`
