### ISSUE TITLE
Need a way to debug memory usage

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#57]
I am still experiencing the issue described in https://github.com/HaxeFoundation/haxe/issues/5735
According to [nicolas's comment](https://github.com/HaxeFoundation/haxe/issues/5735#issuecomment-251655938) one should be able to debug memory usage with `haxe --connect 6000 --display memory`. But since the completion server uses stdio I think there is a need to issue the command through the language server.

**Comment by Gama11** [comment]
Works for me with the following setup:

Add this to your project's `.hxml`:

```
--connect 4000
--display memory
```

Add this to the workspace settings:

```json
"haxe.displayPort": 4000
```

After compiling the project, you should see some debug output in the Haxe output channel:

![](http://i.imgur.com/FLARXkh.png)
