### ISSUE TITLE
Rename Symbol always return "could not find identifier to rename"

### ISSUE THREAD

**Issue by alfredbaudisch** [vshaxe/vshaxe#578]
## Version
- Haxe 4.2.5
- Windows 10
- VS Code 1.77.0
- Extension: both 2.27.0 from the Marketplace and then built from master

## Issue
Trying to rename symbol always return "could not find identifier to rename".

https://user-images.githubusercontent.com/248383/230090440-b8aeffe9-9771-442c-b0cb-e8bcb2fe9467.mp4

```
Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6000
Done.
[rename] error: could not find identifier to rename
[Error - 3:08:35 PM] Request textDocument/rename failed.
  Message: could not find identifier to rename
  Code: -32603 
[rename] error: could not find identifier to rename
[Error - 3:09:32 PM] Request textDocument/rename failed.
  Message: could not find identifier to rename
  Code: -32603 
```

## Reproduction
- Clone https://github.com/heapsio/hide
- Install all dependencies
- Restart Haxe Language Server
- The issue happens

**Comment by alfredbaudisch** [comment]
> Is this folder is in `haxe.renameSourceFolders` for you? https://github.com/vshaxe/vshaxe/wiki/Rename-Symbol

I apologize, I missed that one from the docs, especially because the project I cloned has a different folder naming convention.

**Comment by RblSb** [comment]
You are not the first. @AlexHaxe is there a way to add info about `renameSourceFolders` to this notification?
