### ISSUE TITLE
Code actions have bad offsets with Unicode in file

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#583]
```haxe
// абвгде
...
final x = 0
final y = 0;
```
Semicolon autofix will generate `fi;nal y` or like that, depends on indentation

**Comment by kLabz** [comment]
https://github.com/vshaxe/haxe-language-server/pull/76 could maybe be applied there

**Comment by RblSb** [comment]
Seems like problem with most actions is:
`token.getPos()` returns offsets in utf8 (1 byte for `abc` chars, 2 bytes for `абв` chars)
and then `document.rangeAt(pos.min, pos.max)` iterates with `charAt` like arg offsets are utf16
So there should be some way to convert utf8 byte offsets to utf16 first, before making range from it.

**Comment by kLabz** [comment]
Linked PR deals exactly with this on various commands (but not all that need it, apparently)

**Comment by RblSb** [comment]
Lets rename `byteOffsetToCharacterOffset` to `utf16OffsetToCharacterOffset` and make separate `utf8OffsetToCharacterOffset`?
It would be better to make int offsets as encoding-based abstracts, but this change can be too big.
