### ISSUE TITLE
[REQUEST] using `using` for... using

### ISSUE THREAD

**Issue by lewislepton** [vshaxe/vshaxe#59]
`using` does work. it just does not work in an autocomplete sense. would be cool ;)

<img width="184" alt="screen shot 2016-11-18 at 19 57 19" src="https://cloud.githubusercontent.com/assets/11299322/20446531/ff8e236e-add1-11e6-9b7f-f64d88b7a249.png">

**Comment by lewislepton** [comment]
was from this post i made

https://github.com/KTXSoftware/KodeStudio/issues/28

**Comment by Gama11** [comment]
See https://github.com/HaxeFoundation/haxe/issues/5766.
