### ISSUE TITLE
Server recording disabled: could not remove previous files.

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#590]
Init project with settings.json:
```json
{
	"haxe.serverRecording": {
		"enabled": true,
		"path": ".haxelsp/recording/",
		"watch": [],
		"exclude": [],
		"excludeUntracked": false
	}
}
```
[rec.zip](https://github.com/vshaxe/vshaxe/files/11618104/rec.zip)

**Comment by kLabz** [comment]
I can't repro :thinking:
Are you sure nothing is missing here?

**Comment by RblSb** [comment]
start fails here
https://github.com/vshaxe/haxe-language-server/blob/3e8a0cb513554c383bf664a0f7f520b589fe08d3/src/haxeLanguageServer/server/ServerRecording.hx#L247

and then fallbacks to catchError for some reason (??)

**Comment by RblSb** [comment]
If i comment out `ret = getSvnState`, then it works. I don't have `svn` command installed

**Comment by kLabz** [comment]
Ah, right, missing commands :facepalm:
