### ISSUE TITLE
Display constructor signature when hovering over class name in new expression

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#596]
```haxe
var x = new ExampleClass();
```

If I hover over `ExampleClass` when it appears after the `new` keyword, I'd like to be able to see the constructor function signature (in particular, the list of parameters), similar to when I hover over a method.

**Comment by Simn** [comment]
We discussed this long ago and decided that this was a good compromise: You get the class information on the class name and the constructor information on the `new`. I see no reason to change this.

**Comment by joshtynjala** [comment]
> the constructor information on the `new`

I wasn't aware of this. Thanks for pointing it out!
