### ISSUE TITLE
"Workspace must be empty to set up a Haxe project"

### ISSUE THREAD

**Issue by ousado** [vshaxe/vshaxe#6]
When trying to "Haxe: Initialize VS Code project"  with some existing files, but no hxml file at the root, I get the above error message. I think that could be misunderstood as refusing to initialize unless the whole workspace was empty, which wouldn't be the nicest requirement of course :)

**Comment by nadako** [comment]
I adjusted the error message, but returning to this, I'm now thinking if we should add all hxml files to `haxe.displayConfigurations` instead of selecting one? What do you guys think?

**Comment by ousado** [comment]
Since they can be selected from the menu, I think that'd be a good idea.
