### ISSUE TITLE
Type not found : FileSystem

### ISSUE THREAD

**Issue by luacoder279** [vshaxe/vshaxe#608]
im making a game and it features a mods feature but the i keep getting this when im compiling
Type not found : FileSystem

**Comment by AlexHaxe** [comment]
does that issue occur outside of VSCode?
if yes you need to fix your code (refer to Haxe manual, API documentation, HaxeFlixel tutorials and/or seek help in FNF or Haxe discords).
if no please describe your setup and provide detailed steps to reproduce your issue.

**Comment by luacoder279** [comment]
i fixed it i need to add #if sys #end but if I try to compile as HTML5 it says that I need to add a } but if I do it will make a function become an error

**Comment by AlexHaxe** [comment]
which means you don't have an issue with vshaxe.

for your coding issues I think you can find better help here [Haxe discord](https://discordapp.com/invite/0uEuWH3spjck73Lo). or for FNF specific questions: [FNF discord](https://discord.gg/fridaynightmoddin)
