### ISSUE TITLE
Compilation in progress feedback

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#614]
When upgrading to Haxe development, I no longer get "Building..." during compilation in VSCode
That's quite disturbing :-)
![image](https://github.com/vshaxe/vshaxe/assets/1022912/c89b2d0b-8a06-449d-8604-a5814687f76c)

**Comment by ncannasse** [comment]
When you Shift+Ctrl+B to compile

**Comment by ncannasse** [comment]
Ty if you can fix this, it's very hard now to tell if the build is ongoing or not

**Comment by kLabz** [comment]
> When upgrading to Haxe development

But this implies it still works with earlier Haxe versions?
Will try to repro tonight

**Comment by kLabz** [comment]
Adding `startProgress("Building");` before [that line](https://github.com/vshaxe/haxe-language-server/blob/master/src/haxeLanguageServer/server/HaxeServer.hx#L304) seems to do the trick; not sure what changed / what was doing that before.

**Comment by ncannasse** [comment]
I confirm btw that this is related to Haxe version, as if I switch between our Shiro branch (somewhere around ~4.2.5) and development the Building... disappear. Would be be great to have it fixed and pushed to a vshaxe release as we're planning to upgrade Haxe at Shiro very soon.

**Comment by kLabz** [comment]
Ok I know what's going on: vscode only shows the indicator if a task has problem matchers, and vshaxe doesn't use those with Haxe >= 4.3.

**Comment by Simn** [comment]
Keeping this open as a reminder to look into it again at some point, because the current solution doesn't seem quite right.

**Comment by ncannasse** [comment]
When can we expect a VSHaxe release @Simn @kLabz ? :)

**Comment by Simn** [comment]
I don't think I have the required access for making releases. IIRC the right person to ping here is @AlexHaxe.

**Comment by AlexHaxe** [comment]
Github actions will automatically release a new version when you tag a version number to a commit.

there is a chance our marketplace token expired, so we might need nadako to update it and then rerun the failed Publish task.

**Comment by ncannasse** [comment]
Up :) @nadako

**Comment by nadako** [comment]
Hm, I'm pretty sure I was renewing the token recently, can you guys try?

**Comment by Simn** [comment]
Oh I somehow thought Alex said it wasn't working. I just made a tag, let's see!

**Comment by Simn** [comment]
Well, looks like that wasn't it...

```
[publish](https://github.com/vshaxe/vshaxe/actions/runs/7253264612/job/19759499365#step:4:151)
Error: nadako.vshaxe v2.30.0 already exists.
    at _publish (/home/runner/work/_actions/HaaLeo/publish-vscode-extension/v1/dist/index.js:3630:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async publish (/home/runner/work/_actions/HaaLeo/publish-vscode-extension/v1/dist/index.js:3568:13)
```

**Comment by AlexHaxe** [comment]
sorry, was out sick the last days.

for a new version `version` field in package(-lock).json needs to match and potentially submodule(s) need to be updated and maybe patch notes. then it should work (my read from the rejection message is that the token should still be valid)

**Comment by Simn** [comment]
Alright, that did it. Thank you for the instructions!

**Comment by LeoVgr** [comment]
I still got this issue with the default `tasks.json` on vshaxe 2.31. Looks like the `problemMatcher` entry is the problem here because when deleted, the "Building ..." reappear.

I don't know if this is linked to this problem, but the `haxe-fake` problem matcher isn't recognized too :
`Unrecognized problem matcher. Is the extension that contributes this problem matcher installed?`

Without the `tasks.json` file, the building feedback shows up.
