### ISSUE TITLE
Hover Hints and Code Generation not working

### ISSUE THREAD

**Issue by objShaggy** [vshaxe/vshaxe#623]
Suddenly features like Hover hints and code generation have stopped working, they used to work completely fine but now they're not doing anything at all.

**Comment by AlexHaxe** [comment]
what were you doing when it stopped working? have you tried to retract your steps?

also refer to https://github.com/vshaxe/vshaxe/wiki/Troubleshooting for instructions on how to figure out what causes your issues.

**Comment by objShaggy** [comment]
They have started to work again, only problems now being is that the completion cache wont build and that it's telling me there's issues with my code even tho there aren't.

**Comment by AlexHaxe** [comment]
Please provide detailed steps showing how to reproduce your problem.
