### ISSUE TITLE
IntelliSense not working when I put `import js.Browser;` in Haxe code

### ISSUE THREAD

**Issue by lulunac27a** [vshaxe/vshaxe#624]
When I put `import js.Browser;` in Haxe code, the IntelliSense is not working because it's not showing the completions: `Error: You cannot access the js package while targeting cross (for js.Browser)`. How can I fix that problem?
My build.hxml code is: 
```
-cp src
-D analyzer-optimize
-main Main
--interp
--js src/app.js
```

**Comment by lulunac27a** [comment]
The JavaScript generated code works when I remove the `--interp` in build.hxml, but I still can't show the IntelliSense code completion, even when I close and reopen Visual Studio Code and still gets the same error: `Error: You cannot access the js package while targeting cross (for js.Browser)`

**Comment by kLabz** [comment]
It seems like your build.hxml is not selected in vscode, because 
- that's not the error you should get with both --interp and --js which are incompatible
- vshaxe says you're targeting cross but build.hxml is targeting js

**Comment by lulunac27a** [comment]
It works when `/build.hxml` is in the parent directory, so `/project/build.hxml` doesn't works
