### ISSUE TITLE
The auto-import option only appears when within a method

### ISSUE THREAD

**Issue by Jarrio** [vshaxe/vshaxe#63]
When typing out a class property you do not get the option for auto-import:

### Outside Method
![outsidemethod gif](https://cloud.githubusercontent.com/assets/748557/20775033/e85015bc-b750-11e6-98f2-efedddfbf871.gif)

### Within Method
![withinmethod](https://cloud.githubusercontent.com/assets/748557/20775032/e84a2148-b750-11e6-8dc3-1352804e910b.gif)

**Comment by nadako** [comment]
@Gama11 I'll leave this to you :)

**Comment by Gama11** [comment]
I think this one is for @Simn. This needs to be implemented / supported on the Haxe side, which I have no idea how to do.

**Comment by Simn** [comment]
Someone give me some sample code.

**Comment by Gama11** [comment]
You just need a variable at class level:

```haxe
class Main {
    static var testCase:TestCase;

    static function main() {}
}
```

^Diagnostics should suggest an import for `haxe.unit.TestCase` there.

**Comment by Gama11** [comment]
Moved to https://github.com/HaxeFoundation/haxe/issues/5950.
