### ISSUE TITLE
[Windows] haxe.cmd (i.e. Haxe from npm) doesn't work anymore

### ISSUE THREAD

**Issue by back2dos** [vshaxe/vshaxe#635]
Npm installs "executables" as `.cmd` and node had a breaking change in `spawnSync` relating to those https://github.com/nodejs/node/issues/52681

Presumably some/most occurrences of `spawnSync` would have to have `shell: true` added: https://github.com/search?q=org%3Avshaxe%20spawnSync&type=code

This most easily reproduced by adding an empty `haxe.cmd` and pointing `haxe.executable` to it, which fails to start the server with `EINVAL`.

**Comment by AlexHaxe** [comment]
well, seems like I should've tested it myself instead of assuming from the error reports. at least I can reproduce it with latest vscode on a Windows machine.

I'll try adding the "shell" option to invocations of Haxe command to see if that fixes it on my test system.

**Comment by Aidan63** [comment]
Adding `shell: true` does seem to fix things. I built vshaxe locally with that change and everything seems to be working again with vscode. haxe, and lix.

**Comment by AlexHaxe** [comment]
yeah, I have a working version as well and plan to commit my changes and preprare a new release.

I was slightly distracted doing some security fixes to try-haxe and then I had to figure out why eval debugger didn't work. luckily that's all fixed.

**Comment by AlexHaxe** [comment]
vshaxe 2.32.1 should be out now. please download and test it on latest vscode to see if it works for you.

**Comment by Aidan63** [comment]
yep, works fine.

**Comment by back2dos** [comment]
Yup, works for me too. Thanks a lot ;)
