### ISSUE TITLE
[Windows] "Version check failed" when Haxe is installed in a folder whose path contains spaces

### ISSUE THREAD

**Issue by cedx** [vshaxe/vshaxe#639]
VSHaxe simply doesn't work when Haxe is installed in a folder whose path contains spaces.
It doesn't matter whether it's installed via the official installer or via `lix` (i.e. when the path to the global Node.js folder contains spaces).

The "Haxe version check failed" error is always triggered, and shows an incomplete path (i.e. it stops at the first space encountered).

![image](https://github.com/user-attachments/assets/f0441053-5f41-4992-8982-806c5fef3463)
(here, Haxe is installed into "C:\Program Files\Haxe")

Haxe 4.3.6
Visual Studio Code 1.92.2
VSHaxe 2.32.1

**Comment by AlexHaxe** [comment]
does that happen when you have `"haxe.executable": "auto"` in your `settings.json` or did you set it to a path with spaces in it?

**Comment by cedx** [comment]
This occurs when `haxe.executable` is undefined or set to `auto`.
It also occurs when an explicit path is provided.

**Comment by AlexHaxe** [comment]
on my test system setting it to `auto` works fine pulling `haxe.exe` from "C:\Program Files\Haxe" folder. if I explicitly set it to `"C:\\Program Files\\Haxe\\haxe.exe"` then I get the same error you are seeing.

with lix I don't see that error, since that path does not contain any spaces (luckily my user name is a single word). I would assume it's the same where it works with `auto` and breaks with an explicit path containing spaces.

if yours break even with `auto` then I can't reproduce that currently. so there might be some detail missing that makes your system break regardless.

**Comment by AlexHaxe** [comment]
I don't think there is much to debug here, it can't launch `haxe.exe` so probably the path needs some escaping.

can you try downgrading vscode to 1.91.x (and maybe also get 2.32.0 of vshaxe) and see if it works there?

**Comment by cedx** [comment]
Does this call use an absolute path for `haxeExecutable`?

```haxe
final result = ChildProcess.spawnSync(haxeExecutable, ["-version"], {cwd: folder.uri.fsPath, shell: true});
```

Cf. https://github.com/vshaxe/vshaxe/blob/master/src/vshaxe/configuration/HaxeExecutable.hx#L122

Because, this is not supported by Node.js (v22.7.0 on my system).

```js
import {spawnSync} from "node:child_process";
const {stderr} = spawnSync("C:\\Program Files\\Haxe\\haxe.exe", ["-version"], {shell: true});
console.log(stderr.toString());
// Error: 'C:\Program' n'est pas reconnu... (same message as the error raised by VSHaxe)
```

**Comment by cedx** [comment]
https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

"If the input to `spawn`/`spawnSync` is **sanitized**, users can now pass `{ shell: true }` as an option to prevent the occurrence of EINVALs errors."

So if we rewrite a little the previous Node.js sample:

```js
import {spawnSync} from "node:child_process";

const {stdout} = spawnSync('"C:\\Program Files\\Haxe\\haxe.exe"', ["-version"], {shell: true});
// Note the single quotes added around the path.

console.log(stdout.toString());
// 4.3.6
```

If I use a previous Node.js version (before the patch was applied, for example v20.12.1), without the `{shell: true}` option, the path does not need to be sanitized, but if I enable the option, the path **must** be quoted:

```js
spawnSync("C:\\Program Files\\Node.js\\haxe.cmd", ["-version"]);
// stdout: 4.3.6

spawnSync("C:\\Program Files\\Node.js\\haxe.cmd", ["-version"], {shell: true});
// stderr: 'C:\Program' n'est pas reconnu en tant que commande interne...

spawnSync('"C:\\Program Files\\Node.js\\haxe.cmd"', ["-version"], {shell: true});
// stdout: 4.3.6
```

So this issue is probably related to the Node patch and #637.

**Comment by cedx** [comment]
Based on the previous assertion, I've set the following options in VSCode, and now everything works as expected.

```json
"haxe.executable": "\"C:\\Program Files\\Node.js\\haxe.cmd\"",
"haxelib.executable": "\"C:\\Program Files\\Node.js\\haxelib.cmd\""
```
