### ISSUE TITLE
No diagnostic for files outside project folder

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#644]
Create `absoluteLibSrc/Lib.hx` with:
```haxe
class Lib {
	public static function main() {
		// Lib.foo;
	}
}
```
Then use go to definiton from `echo2` project to `absoluteLibSrc/Lib.hx`, uncomment `Lib.foo` and save. Hover and completion will work in Lib.hx opened like that, but no diagnostic after file save and code actions.

This problem true for `-cp ../absoluteLibSrc/` and for `-cp global/path/absoluteLibSrc/`, so it's problematic to open your dev library files from main project and edit both without problems.

[echo2.zip](https://github.com/user-attachments/files/16826234/echo2.zip)
[absoluteLibSrc.zip](https://github.com/user-attachments/files/16826233/absoluteLibSrc.zip)

**Comment by kLabz** [comment]
I'm not sure what can be done here. 

After a bit of investigation, `onDidOpenTextDocument` is not called for files outside the workspace, so we can't keep track of them and run diagnostics on it (and those files don't even make it to the path filter so it's not that either, though it might be a second step).

This looks to me like a global LSP problem (applies to other editors btw); maybe we can fix it at configuration level somehow :thinking:

**Comment by kLabz** [comment]
For nvim it seems it's due to https://github.com/neovim/nvim-lspconfig/issues/842

**Comment by RblSb** [comment]
Thanks! I'm wondering why "${workspaceRoot}" is set by default, is this to improve performance or solve any cases of unnecessary diagnostic errors?
