### ISSUE TITLE
Haxe/Heaps/HashLink project on second internal harddrive cause intellisense/autocomplete to stop working.

### ISSUE THREAD

**Issue by rhythmpattern** [vshaxe/vshaxe#645]
Haxe/Heaps/HashLink project on second internal harddrive causes intellisense/autocomplete to stop working.
1. No spaces in the project / folder names.
2. Permissions of drive look ok.
3. Moving the project into a subdirectory on the main hard drive, under Home . Fixes the problem.
4. The project is cloned from deepnightLibs GameBase  template on github.
5. Fedora 40 desktop, Visual Studio Code 1.92.2.
Hope this helps someone with a similar issue.
Thank you.

**Comment by AlexHaxe** [comment]
1. close all VSCode windows
2. create an empty folder on your secondary drive
3.  launch only one VSCode window 
4. use `File` -> `Open Folder…` to point it to that freshly created, empty folder. 
5. run `F1` -> `Haxe: Initialize Project`.
6. then wait until status bar no longer shows `Haxe: Building cache…`
7. go to `View` -> `Output` and select `Haxe` from dropdown list in its top right corner:
![OUTPUTHaxe](https://github.com/user-attachments/assets/5a23dbf6-fcd8-43e6-b293-b57bb51634ed)
8. there you should see something like:
![StartLSPHaxe](https://github.com/user-attachments/assets/a88bf0fe-c3fc-49ef-84e3-ae9366def856)
9. try completion / hover and see if that produces errors in output view.
10. return here with error messages (preferably in text form)
11. if no error messages figure out differences between your project and `Haxe: Initialize Project` sample.

**Comment by rhythmpattern** [comment]
Using the above steps.
1. Intellisense/autocomplete not working on either of two ext4 linux secondary internal SSD's I have.
2. Intellisense works in Home Drive using those steps and an external USB drive works also funnily enough.
3. No errors shown on secondary internal drivers in output window or: Toggled Developer Tools Console, which hasn't helped debugging so far anyway.

**Comment by AlexHaxe** [comment]
but you do see the `Haxe language server started` and `Done.` lines in OUTPUT view?

take a look at https://github.com/vshaxe/vshaxe/wiki/Troubleshooting to increase verbosity of output and enable Haxe server view in order to see if it does anything. you might even go as far as enabling server recording to see what messages go back and forth (if any).

other than that I'm out of ideas why it won't work on a different file system / mount point. 

although just out of curiosity can you add a typescript or a javascript file to your project and see if that has completion?

**Comment by rhythmpattern** [comment]
Hi, I created a .js file and Javascript autocomplete was working on the external drives. I guess haxe doesn't like them. Similar thing happens with Docker, I can't bind these external drives even after playing with the Permissions in /etc/fstab and chmoding the drives. Still haven't found the exact cause.

**Comment by rhythmpattern** [comment]
I found the fix for this issue, can close this.
1. If I open a new VSCode window and open the project folder from Open Folder, it will not recognize the intellisense.
However,
2. If I navigate to the folder and open a terminal at the location, then run "code ./". It will work.
3. The reason is this forces VSCode to ask if I trust the files and shows the trust options popup.
4. Seems VSCode doesn't show the "Do you trust this project" popup when opening from Folder inside VSCode which removes permission to intellisense.
Thanks for your help.
