### ISSUE TITLE
Error messages not showing in VS Code's output window when using -Ddebug

### ISSUE THREAD

**Issue by Jarrio** [vshaxe/vshaxe#65]
I have been compiling in vscode and switching to the terminal when my program crashes to get the error message and it seems I've isolated why there's been no error output!

Using the `tasks.json` precompiled code which parses the command `-Ddebug` to the individual platforms to initiate debug mode the error does not return in the vscode output window, however changing it to `-debug` does! I have only tested this for the cpp platform so if anyone else is having similar issues then this might fix it for you.

Just go to the platform you have set as the current `isBuildCommand` and change the `args` portion from 
`-Ddebug` to `-debug`

Edit:

I was just further experimenting with this and found that is not the only thing which needs to change. According to the vshaxe git page it mentions you will need to add `fileLocation` to the problem matcher in the `tasks.json` folder. Might I suggest that making this step part of some "setting up" guide as it is just mentioned way at the bottom of the git page so it is easily missed and is a pretty important step for general use of the extension?

It is still important to switch the debug argument over to actually get the error message to process

**Comment by Gama11** [comment]
Sounds like this was actually a flixel-templates issue, and has been resolved a while ago:

https://github.com/HaxeFlixel/flixel-templates/commit/406bea1d3da4fa229b48785e3765022b2354671c
