### ISSUE TITLE
LanguageClient should be instantiated one time only

### ISSUE THREAD

**Issue by fzzr-** [vshaxe/vshaxe#66]
LanguageClient should be [instantiated](https://github.com/vshaxe/vshaxe/blob/master/src/vshaxe/Main.hx#L85) one time only because of:
1. VSC have one terrible feature/bug I think - it doesn't want fully remove the `outputChannel`;
2. IMHO, no need to clean outputChannel when server restarts.

![vsc haxe issue mov opt](https://cloud.githubusercontent.com/assets/888526/20903575/e2ef18fc-bb4c-11e6-9a7d-598bfcbfa288.gif)

**Comment by Gama11** [comment]
#52

**Comment by fzzr-** [comment]
Oh sorry! It's a bug of VSC.

Anyway we _re_instantiating `LanguageClient` **only** to change [`initializationOptions`](https://github.com/vshaxe/vshaxe/blob/ae44668c450a423346e95de2be91a7d95753b4de/src/vshaxe/Main.hx#L81-L83). Isn't it?

**Comment by nadako** [comment]
LanguageClient is recreated every time we restart the server, that is right now - on configuration change and on user command. I don't think we can avoid that. As for the output channel, see #52
