### ISSUE TITLE
Link to error position not working

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#67]
Somehow it worked for a while some time ago. But it no longer works now.

When it was working, a compiler error like below:
```
src/api/Messages.hx:64: characters 38-39 : Missing ;
```

will have the position underlined and you can cmd+click it to jump to that location directly.

I am not sure if it is vshaxe or vscode's problem...

**Comment by nadako** [comment]
Just tested - that works for me through the Problems Panel (ctrl+shift+m)

**Comment by kevinresol** [comment]
Hm... I don't mean the problems panel, but in the output panel directly.

**Comment by nadako** [comment]
I think that was never supported by VS Code. Are you confusing it with Sublime Text?

**Comment by kevinresol** [comment]
No, I am sure I used that for some time.
The position is underlined and when you hover the mouse over it, it will tell "cmd+click" to go to position.

**Comment by kevinresol** [comment]
But funny enough is that I seems unable to find any trace of that functionality over the web... 😕

**Comment by Simn** [comment]
I think that "just works" for absolute paths.

**Comment by kevinresol** [comment]
> I think that "just works" for absolute paths.

I can't verify that. But if it is so, can vshaxe (or the compiler?) emit the full path?

**Comment by Gama11** [comment]
The compiler sometimes emits absolute, and sometimes relative paths. This also causes issues for the output panel, because the problemMatcher can only be set to accept either one or the other, see #23...

**Comment by kevinresol** [comment]
![screenshot 2016-12-22 21 28 02](https://cloud.githubusercontent.com/assets/1103788/21427135/b870909e-c88d-11e6-9cdc-5cbefa840a50.png)

I wished to reopen this with my (finally) found evidence.
