### ISSUE TITLE
renaming package confuses Haxe server

### ISSUE THREAD

**Issue by MatthijsKamstra** [vshaxe/vshaxe#69]
I started with a empty project.

Steps to reproduce:

1. create folder `util` (no "s")
2. create `Test.hx` in folder `util` 
```haxe
package util;
class Test{
	public function new() {
		trace('Test');	
	}
}
```
3. add to `Main.hx` : ` new util.Test();`
4. build
5. rename `util` to `utils`
6. build and obvious error: `src/Main.hx:9: characters 12-21 : Type not found : util.Test`
7. change package in `Test.hx` and `Main.hx`.
8. Build : that works, but Error still is there

<img width="506" alt="screen shot 2016-12-11 at 12 04 29" src="https://cloud.githubusercontent.com/assets/907219/21079699/0796bbdc-bf9a-11e6-9db4-3c00b9f349cd.png">

only way to fix that: restart language Server or VSCode

**Comment by Gama11** [comment]
I can't reproduce that - the error goes away as soon as diagnostics are refreshed (happens when typing something + saving the file or switching tabs).
