### ISSUE TITLE
errors : cannot read property "concat" of undefined and handler not a function

### ISSUE THREAD

**Issue by Triangle345** [vshaxe/vshaxe#70]
Getting two errors on VSCode win10.  I'm not sure if this is the root cause of the plugin not being able to auto complete?

Haxe language server started
Initializing completion cache...
[Warn  - 9:20:59 PM] Exception while processing notification workspace/didChangeConfiguration: TypeError: Cannot read property 'concat' of undefined

Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 1664
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 1335
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3792
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3725
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3870
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from events.js line 96
Called from events.js line 188
[Warn  - 9:20:59 PM] Request textDocument/codeLens failed.
  Message: Exception while handling request textDocument/codeLens: TypeError: handler is not a function

Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3759
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3723
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3870
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from events.js line 96
Called from events.js line 188
Called from _stream_readable.js line 176
Called from Readable.push (_stream_readable.js line 134)
Called from net.js line 543
  Code: -32603 
[Warn  - 9:20:59 PM] Exception while handling request textDocument/codeLens: TypeError: handler is not a function

Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3759
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3723
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3870
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from events.js line 96
Called from events.js line 188
Called from _stream_readable.js line 176
Called from Readable.push (_stream_readable.js line 134)
Called from net.js line 543
[Warn  - 9:21:00 PM] Exception while handling request textDocument/hover: TypeError: handler is not a function

Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3759
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3723
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3870
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from events.js line 96
Called from events.js line 188
Called from _stream_readable.js line 176
Called from Readable.push (_stream_readable.js line 134)
Called from net.js line 543
[Warn  - 9:21:00 PM] Request textDocument/hover failed.
  Message: Exception while handling request textDocument/hover: TypeError: handler is not a function

Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3759
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3723
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3870
Called from C:\Users\me\.vscode\extensions\nadako.vshaxe-1.0.1\bin\server.js line 3968
Called from events.js line 96
Called from events.js line 188
Called from _stream_readable.js line 176
Called from Readable.push (_stream_readable.js line 134)
Called from net.js line 543
  Code: -32603

**Comment by Triangle345** [comment]
Looks like doing a haxe init inside my currently existing project folder fixes the issue.  Should probably mention somewhere that it is required to init the project this way, even though it may already exist

**Comment by Gama11** [comment]
Seems to be the same error as https://github.com/vshaxe/haxe-languageserver/issues/20.

Not sure what you mean by `haxe init`? That's not a valid Haxe command.
