### ISSUE TITLE
Is there a way to use vscode for a pure neko project?

### ISSUE THREAD

**Issue by Jarrio** [vshaxe/vshaxe#71]
I've attached a default neko project generated from HaxeDevelop, I was wondering how to set it up in vscode because there doesn't seem to be a way to generate a compilation.hxml file which references the various sources. I would appreciate any help, thanks! 
 
[New Neko Project.zip](https://github.com/vshaxe/vshaxe/files/661808/New.Neko.Project.zip)

**Comment by Gama11** [comment]
Use a .hxml file for building that looks something like this:

```
-cp src
-main Main
-neko bin/run.n
```

To run it:

```
neko bin/run.n
```

**Comment by Jarrio** [comment]
Is there a way to configure a task for it? I'm attempting it with a snippet of the regular tasks.json. I'm assuming the `-debug` flag should be added to the compilation.hxml file. The following task is what I have messed around with but it is returning the errors:
`Failed to launch external program neko bin/run.n .`
`spawn neko bin/run.n ENOENT`

The task at the moment:

`{
    "version": "0.1.0",
    "command": "neko bin/run.n",
    "tasks": [        
        {
            "taskName": "neko",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": ["-debug"],
            "problemMatcher": {               
                "owner": "haxe",
                "pattern": {
                    "regexp": "^(.+):(\\d+): (?:lines \\d+-(\\d+)|character(?:s (\\d+)-| )(\\d+)) : (?:(Warning) : )?(.*)$",
                    "file": 1,
                    "line": 2,
                    "endLine": 3,
                    "column": 4,
                    "endColumn": 5,
                    "severity": 6,
                    "message": 7
                },
                "fileLocation": ["relative", "${workspaceRoot}/build.hxml"]
            }
        }
    ]
}`

**Comment by Gama11** [comment]
`"command"` is just `"neko"`, `bin/run.n` should be one of the `"args"`:

```
"args": ["bin/run.n", "-debug"]
```

Alternatively, you could also add `-cmd neko bin/run.n` to your hxml file and call `"haxe build.hxml"` from your `tasks.json` to compile _and_ run the application.

**Comment by Jarrio** [comment]
Thanks, that's the perfect solution! For anyone looking for the same setup, I've attached a blank project. 

[New Neko Project.zip](https://github.com/vshaxe/vshaxe/files/662008/New.Neko.Project.zip)
