### ISSUE TITLE
Auto-import adds import statement in wrong place

### ISSUE THREAD

**Issue by wiggin77** [vshaxe/vshaxe#72]
The import statement always ends up at top of file, should be after package statement.

![vscode-haxe-auto-import](https://cloud.githubusercontent.com/assets/5024605/21506168/fe3cf228-cc3b-11e6-95ba-013265ed2304.gif)

**Comment by Gama11** [comment]
Not "always"... this happens because of the comment before `package` it looks like.

**Comment by wiggin77** [comment]
Good point, "not always".  It does work correctly without the file header comment.  Thanks.
