### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#76]
Seems that this happens if the identifier starts with "var"

<img width="192" alt="screen shot 2017-01-19 at 11 40 57 am" src="https://cloud.githubusercontent.com/assets/1103788/22092905/4b8b68ea-de3c-11e6-9961-6ba7871b9450.png">

**Comment by Gama11** [comment]
I think I already fixed this yesterday in d331639cd9b2c0476ec3c4ae873ded90c39eba42 (not yet released).
