### ISSUE TITLE
Sample project with all configs correct for autocomplete

### ISSUE THREAD

**Issue by Meai1** [vshaxe/vshaxe#77]
Can you provide such a sample project? I tried setting it up, but as a newcomer to haxe who just wants to learn the language if it helps me get good typings with javascript, I have a particularly hard time trying to set something up. 
I did initialize a project with the built-in action and I have the update to date haxe installation but then how do I use type definitions? Does Haxe use Typescript definitions? How do I make my own and interoperate with javascript?
Does vshaxe support compile on save, or some kind of watch compiler?

**Comment by Gama11** [comment]
>Does Haxe use Typescript definitions?

No. Haxe uses "externs", you can find Haxe externs for a lot of libs on haxelib and / or GitHub. This are the NodeJS externs for instance: https://github.com/HaxeFoundation/hxnodejs

>How do I make my own and interoperate with javascript?

See https://haxe.org/manual/target-javascript-external-libraries.html.

>Does vshaxe support compile on save, or some kind of watch compiler?

No.

_____________

Note: the issue tracker is mostly for bug reports / feature requests. Try asking on the Haxe mailing list instead in the future: https://groups.google.com/forum/#!forum/haxelang

**Comment by Gama11** [comment]
Oh, and regarding the first question:

>Can you provide such a sample project?

There's an example project here: https://github.com/vshaxe/vshaxe/tree/master/scaffold
