### ISSUE TITLE
Use the server when building

### ISSUE THREAD

**Issue by back2dos** [vshaxe/vshaxe#79]
Is there a way to build through the server?

You can build this one with `--times` to observe the problem:

```haxe
class Main {
    #if !macro
    static function main() {
        wait();
    }
    #end
    macro static function wait() {
        Sys.sleep(5.0);
        return macro trace('hello');
    }
}
```

For me, this results in something like:

```
name     | time(s) |   % |   # | info
--------------------------------
analyzer |   0.009 |   0 | 750 | 
filters  |   0.012 |   0 |   1 | 
generate |   0.002 |   0 |   1 | 
  js     |   0.002 |   0 |   1 | 
macro    |   5.055 |  98 |   5 | 
other    |   0.001 |   0 |   1 | 
parsing  |   0.040 |   1 | 123 | 
typing   |   0.047 |   1 |   1 | 
--------------------------------
total    |   5.167 | 100 |   0 | 
```

I also see a separate haxe process being spawned.

If I open a server with `haxe --wait 6000` and compile with `haxe --connect 6000 --times build.hxml` then the rebuild doesn't invoke the macro,

Is there a way to just build what the server has in its cache (basically just run without `--no-output`)?

**Comment by Simn** [comment]
We haven't finalized how we want to approach this, but what you can do for now is adding `"haxe.displayPort": 6000` in settings.json, then `--connect ` to it as you normally would.

**Comment by back2dos** [comment]
Cool, works great for me.

As a suggestion: given that there's already pretty decent handling to switch display configuration, a good start might be to fall back to it when building with empty/undefined `"args"` in `tasks.json`?

**Comment by Gama11** [comment]
@back2dos vshaxe isn't really involved in building, and I don't think extensions have any control over that right now. See https://github.com/Microsoft/vscode/issues/15179.

**Comment by nadako** [comment]
Yeah, let's wait for MS to implement something that can be extended by plugins and then think of how we can integrate into it.

**Comment by Gama11** [comment]
The upcoming 1.10.0 of Vshaxe automatically adds `--connect` to auto-generated tasks due to the following default settings:

```
"haxe.displayPort": "auto"
"haxe.enableCompilationServer": true
```
