### ISSUE TITLE
Override haxe.configuration.json

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#84]
This is more a question than an actual issue, but is there a way to override the settings of vshaxe/haxe.configuration.json (without having to fork vshaxe) ?

**Comment by Gama11** [comment]
Oh, it looks like the issue in #83 comes from that file.

**Comment by Gama11** [comment]
Regarding the original question, I'm not sure if that's possible. What's your use case?

**Comment by jeremyfa** [comment]
I have a preference to use ´/** comment */´ instead of ´/** comment **/´. So I would like to configure how ´/*´ is auto closed.

**Comment by Gama11** [comment]
I think https://github.com/wiggin77/codedox can help you there. It's quite customizable too!

**Comment by jeremyfa** [comment]
Ah cool, thanks for the link!

Initial question remains valid though :)

**Comment by Gama11** [comment]
It looks like you can achieve this by creating your own extension with an altered language configuration file and _making sure it's loaded after vshaxe_. Extension loading order seems to be alphabetical depending on the folder names in `.vscode/extensions`, so something like `vshaxe2` works. The language config file needs to be included in `package.json` like vshaxe does:

```haxe
"contributes": {
    "languages": [
        {
            "id": "haxe",
            "aliases": [
                "Haxe",
                "haxe"
            ],
            "extensions": [
                ".hx"
            ],
            "configuration": "./haxe.configuration.json"
        }
    ]
}
```

Extension loading order is apparently not something the user should have control over (https://github.com/Microsoft/vscode/issues/13292), so this is a bit hacky.

**Comment by jeremyfa** [comment]
Wow, thanks for the detailed answer!
