### ISSUE TITLE
Add an option to restart haxe server at a fixed interval

### ISSUE THREAD

**Issue by jeremyfa** [vshaxe/vshaxe#86]
Right now, I have to restart the haxe server manually from time to time.

Ideally it would best if there were never any problem on the haxe server so that we don't need to restart the server, but in practice, there are problems that can be "server taking 100% of CPU forever" or "server using too many subprocesses" having side effects like failing to create new processes (like when running CTRL+SHIFT+B, for instance).

I experienced the same issue when working on the atom plugin (haxe-rewrite branch: https://github.com/snowkit/atom-haxe/tree/haxe-rewrite), and the pragmatic solution I found was to restart the haxe server automatically every minute without any manual action (ensuring any haxe server-related problem would not last more than one minute). Of course every minute is a bit agressive.

That said, it would be useful to have an option in vscode to automatically restart the haxe server periodically at a specified interval of time, without having to do so manually. That's not ideal, but still better than having to run manually the _haxe.restartServer_ several times in the day, or wondering why completion suddenly stopped working (especially for newcomers).

**Comment by Gama11** [comment]
Hm... I actually have issues like that pretty rarely.

**Comment by jeremyfa** [comment]
I guess it depends on the project, but it definitely happens to me several times a day. The project is having a lot of classes, I guess that may influence the number of times the issue occurs. Anyway, that's why I am suggesting to provide an option to control that, and not force it to every user.

**Comment by Gama11** [comment]
Curious about @nadako's and @Simn's thoughts on this.

**Comment by jeremyfa** [comment]
Ah, it happened again just now on my project when running build (CTRL+SHIFT+B):

```
Called from CommandLineTools.hx line 389
Called from /usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx line 88
Called from a C function
Called from /usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx line 99
Uncaught exception - Process creation failure : haxelib
```

(the issue would happen whatever the build command is btw, it just seems that the haxe server is having more and more "subprocesses" over time until the host electron/vscode starts to complain, I had the exact same issue on Atom)

Restarting the haxe server manually "fixed" it instantly.

**Comment by Gama11** [comment]
Is the relevant project public? What OS?

**Comment by jeremyfa** [comment]
Unfortunately not public. It's on macOS (now on Sierra, but it did occur on Yosemite as well).

The project is using flixel, nape (a lot of classes), spine... I don't think there is anything special on it though.

**Comment by Simn** [comment]
We should look into the actual issue instead of randomly restarting the server like a bad sysadmin...

**Comment by Gama11** [comment]
@jeremyfa How up-to-date is your Flixel version? There is a build macro that used to create haxelib and git processes during display which ended up causing some people issues: https://github.com/HaxeFlixel/flixel/commit/f5dca1dc44d80256ee7ff3a07768852a385f9139

**Comment by jeremyfa** [comment]
I am on flixel 4.1.0. This issue might be related indeed (that said, why running a process in a macro at completion would actually LEAK the process?).

@Simn I definitely agree on looking at the roots of the issues. But I also think it's useful to have "tools" that can help when a _not solved yet_ bug is occuring and is actually affecting daily work. (here, I just suggested an option that doesn't have to be enabled by default).

**Comment by Simn** [comment]
It looks like that Process instance is indeed never closed properly.

**Comment by jeremyfa** [comment]
At the moment I'd rather stick with the current flixel version I have because I am close to release an update of the related game and don't want anything to break now, but I will try to update later.

Meanwhile, suggested option would still be useful. And useful everytime something that cannot be identified right away goes wrong "from time to time" in the haxe server, (like mentioned above, _server taking 100% of CPU_, for instance. This did happen less often than the process leak issue, so it might be less critical, but also harder to fix as it happens more rarely). Anyway, there could be _after updating dependency A, B or C, or even haxe_ a bug that may take time to be fixed... that's when the _bad sysadmin_ method can still help, as pragmatic and unelegant it sounds.

**Comment by jeremyfa** [comment]
Edit: the flixel fix seems to work! Still curious about whether a PR for this option would be accepted or not. Thanks!

**Comment by jeremyfa** [comment]
Given that there is still issue https://github.com/vshaxe/vshaxe/issues/52 that would get even worse with such option, and that so far current root issue has been identified, I'll just close this for now. Let's see if problem occurs again in the long run or not.

@Gama11 regarding the flixel issue, I believe the leaking process should be closed prolerly, not only disabled when using `#display`, because if we **build** using the haxe server (in order to speed things up), the process would still be leaking at the moment (not in "display" case, and process not killed because parent (haxe server) keeps running, I suppose).

**Comment by Gama11** [comment]
@jeremyfa There was another commit after the one I linked to that should have fixed that: https://github.com/HaxeFlixel/flixel/commit/ae7d23583c1e558ca68e4857073470bc1b94e7a7

It's also part of the 4.2.0 release.

**Comment by jeremyfa** [comment]
Ah ok great!
