### ISSUE TITLE
Add support for openfl project files

### ISSUE THREAD

**Issue by zaynyatyi** [vshaxe/vshaxe#88]
Since hxml files (or haxe build parameters) can be easily generated from project.xml it would not be a big thing to add support for them. 
The only thing - i'm not sure where to put target platform selection. Any suggestions on that?

**Comment by Gama11** [comment]
See #18 which should cover this.

Target plaftorm selection could just use the hxml chooser:

![](http://i.imgur.com/YcpkWIL.png)

**Comment by zaynyatyi** [comment]
Cool, thanks
