### ISSUE TITLE
Goto getter/setter

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#89]
```haxe
public var value(get,set):Int
```

Cmd click / ctrl click on the keyword `get/set` should go to the getter/setter function.

**Comment by Gama11** [comment]
Works fine for me (Haxe 3.4.0):

![](http://i.imgur.com/QGjVcam.gif)

Are there any errors in the Haxe output console after the `@position` request?

**Comment by kevinresol** [comment]
Oh...
I cannot reproduce it right now. Will get back when I do.
