### ISSUE TITLE
Use the same server for completion and compilation?

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#9]
`--wait studio` is used to start haxe for completion. If I would like to use the same server for compilation, what would the command line be? `--connect stdio`?

**Comment by nadako** [comment]
No, that won't work because if you start with `--wait stdio`, you have to connect to the started process's stdin/stderr. I don't think that's easily possible right now and I am not sure if it's worth it to hack this into vshaxe...
