### ISSUE TITLE
Type not found : ApplicationMain

### ISSUE THREAD

**Issue by rb1147x** [vshaxe/vshaxe#91]
Hi,

I'm able to successfully create a new openFL project and generate a hxml for use with vscode/vshaxe. However, after initializing vshaxe there's an immediate error, shown in the output console, of 

`Type not found : ApplicationMain`

Oddly enough, autocompletion still works as well as haxe errors/warnings, but only shown in the output console. Errors and warnings are not shown within the editor itself (e.g. no problem reporting in the bottom left, no red squiggly lines in the code, etc).

Has anyone run into this problem? I find it odd that vshaxe is showing an error, asking to fix and restart the language server and yet it still sort of works :)

For reference I'm using all the latest versions:
Haxe: 3.4.0
openfl: 4.8.0
lime: 3.7.3
vshaxe: 1.3.2

Thanks!

**Comment by Gama11** [comment]
When starting up, vshaxe builds a completion cache to speed up subsequent completion requests, from what you describe it sounds like that might have been unsuccessful.

Can you post the full error message?

**Comment by rb1147x** [comment]
This?

```
Haxe language server started
Initializing completion cache...
Could not retrieve haxelib repo path for diagnostics filtering
Processing Arguments [build.hxml,--no-output]
Defines cpp=1,dce=std,desktop=1,display=1,haxe3=1,haxe_ver=3.4,hxcpp_api_level=331,lime-cffi=1,lime-native=1,lime-vorbis=1,lime=3.7.3,lime_cffi=1,lime_native=1,lime_vorbis=1,native=1,no-compilation=1,no_compilation=1,openfl-native=1,openfl=4.8.0,openfl_native=1,source-header=Generated by Haxe 3.4.0,sys=1,tools=3.7.3,true=1,windows=1
Using signature 52eb94a0cde4fff4230d4886eac4e00f
Display position: ?: -1--1
> Type not found : ApplicationMain
Stats = 111 files, 108 classes, 940 methods, 3 macros
Time spent : 0.123s
Failed - try fixing the error(s) and restarting the language server:

Type not found : ApplicationMain
```

**Comment by Gama11** [comment]
Ok, I was able to reproduce it. :)

So, basically, it looks like the hxml from `lime display` is good enough for display requests, but not actual compilation. However, that's what we do when building the completion cache: compiling the project.

Instead of using `lime display` , you can actually just use the hxml Lime generates on each build anyway. This has the added advantage of being updated whenever you build for that target.

This is the same approach Flixel takes (and is also the reason why I never really noticed this until now): https://github.com/HaxeFlixel/flixel-templates/blob/2.2.1/ide-data/visual-studio-code/.vscode/settings.json#L2-L23

Unfortunately, this compilates things a bit for #18...

**Comment by rb1147x** [comment]
Thanks!

The editor still doesn't report errors/warnings for me (only showing in the output console). 

Does that work for you?

**Comment by Gama11** [comment]
When you compile? Yes, that should work if you have a problem matcher. https://github.com/vshaxe/vshaxe#build-task

It should even show you some errors from diagnostics without compiling:

![](http://i.imgur.com/lNu7yX0.png)

**Comment by rb1147x** [comment]
Yeah, I haven't touched the default tasks.json.... but now it just isn't working on any of my Haxe projects, openfl or not.

![capture](https://cloud.githubusercontent.com/assets/17628197/23001236/d9af6d1a-f3a9-11e6-8a97-4459762b6204.PNG)

**Comment by Gama11** [comment]
To be sure, you're actually running a build task to compile the project?

The errors from the output panel won't be highlighted or show in the problems view, they're just debug info from display requests for the most part.

**Comment by rb1147x** [comment]
Ahh oops, I hadn't but just did and it works fine with non openFL projects.

However, it doesn't seem to be working with openFL projects. I've changed the display config, which seemed like it worked at first, but I guess not. I have no indication of errors/warnings beyond the console.

**Comment by Gama11** [comment]
How does the tasks.json for your OpenFL project look like?

**Comment by rb1147x** [comment]
```
{
    "version": "0.1.0",
    "command": "haxe",
    "args": ["build.hxml"],
    "problemMatcher": {
        "owner": "haxe",
        "pattern": {
            "regexp": "^(.+):(\\d+): (?:lines \\d+-(\\d+)|character(?:s (\\d+)-| )(\\d+)) : (?:(Warning) : )?(.*)$",
            "file": 1,
            "line": 2,
            "endLine": 3,
            "column": 4,
            "endColumn": 5,
            "severity": 6,
            "message": 7
        }
    }
}
```

**Comment by Gama11** [comment]
You need to build through `lime` (or `haxelib run lime` if you haven't set up the alias) as you normally would with OpenFL projects, not `haxe`. A simple example:

```json
{
    "version": "0.1.0",
    "command": "haxelib",
    "args": ["run", "lime", "test", "flash"],
    "problemMatcher": {
        "owner": "haxe",
        "pattern": {
            "regexp": "^(.+):(\\d+): (?:lines \\d+-(\\d+)|character(?:s (\\d+)-| )(\\d+)) : (?:(Warning) : )?(.*)$",
            "file": 1,
            "line": 2,
            "endLine": 3,
            "column": 4,
            "endColumn": 5,
            "severity": 6,
            "message": 7
        }
    }
}
```

Check out Flixel's tasks.json for something more comlex that supports multiple targets:

https://github.com/HaxeFlixel/flixel-templates/blob/2.2.1/ide-data/visual-studio-code/.vscode/tasks.json

**Comment by rb1147x** [comment]
Wow, okay. Thanks!

Everything appears to be working now. I could have sworn a lot of the error/warning indications were happening automatically as I wrote code. I really haven't been running the build task just to 'refresh' the editor.

Thanks again for troubleshooting this with me.
