### ISSUE TITLE
Completion for "override function"

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#92]
Shows a list of overridable functions at `override |` or `override function |`

**Comment by Gama11** [comment]
I very much want to have something like that as well.

One issue with only allowing it on override is that you can't implement interface methods that way. Doesn't mean it shouldn't be supported though. :)

**Comment by Gama11** [comment]
Need some kind of support from Haxe for this as well.

**Comment by ncannasse** [comment]
Up ? :)

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/pull/7005

**Comment by Gama11** [comment]
![](https://i.imgur.com/M1lq6qZ.gif)

**Comment by Gama11** [comment]
This is supported now:

![](https://i.imgur.com/zez5QiJ.gif)

(still a few known issues to work out, but most cases work fine)

**Comment by ncannasse** [comment]
Can we remove the "public" that is added ? By default, override should not increase the visibility of the method (in case we change it to private later)

**Comment by Simn** [comment]
It only adds that if the overridden field is public too.

**Comment by ncannasse** [comment]
It's still unnecessary, and in case the "public" is removed from the
original method declaration, it sill allows public access to all overridden
methods.

**Comment by Simn** [comment]
Uhm okay, I thought it would be a compiler error if we don't have the `public` there. That's how it behaves for interfaces, but not for overrides. Isn't that inconsistent?

**Comment by kevinresol** [comment]
I am used to that behaviour, to me it just mean "inherit the access"

**Comment by Gama11** [comment]
I don't really like that Haxe feature to begin with... Visibility in classes defaulting to `private` _except for overrides of public methods_ hurts readability / is confusing, in my opinion.

If there's really a demand for it (which I doubt at the moment), we could add a code style setting for this, but I'd still like public access to be explicit by default. Note that FlashDevelop, which this feature is copied from, adds `public` as well.

**Comment by ncannasse** [comment]
override is override : it redefines the method without changing its
visibility.
regarding interface : implements is implicit since you don't need to tell
"implements" on each method, so the visibility needs to match.
Please remove the public, that's not because FlashDevelop is doing it wrong
that we should follow :D
