### ISSUE TITLE
init project includes all `.hxml` found in local `.haxelib`

### ISSUE THREAD

**Issue by fponticelli** [vshaxe/vshaxe#93]
If you `init` a project that contains a `.haxelib` folder (local haxelib) the dropdown proposes all the `*.hxml` files contained there (they can be hundreds). I see 2 possible solutions:

  - [ ] filtering `.haxelib` (or make it configurable)
  - [ ] sort files in the dropdown so that root files appear first and `.` folders last

**Comment by Gama11** [comment]
I think the correct behavior is to just ignore `.haxelib`. The reason that's not done atm is probably because that `newrepo` feature is used so little. :D
