### ISSUE TITLE
Invalid positions reported by diagnostics when file is not ascii-only

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#98]
Original issue: https://github.com/vshaxe/haxe-languageserver/issues/17

>This is due to vshaxe/haxe-languageserver@3468d0286da05fb77970ca625e138229bcd656a0. and until https://github.com/HaxeFoundation/haxe/issues/5163 is implemented, we're gonna need to open each file and do these conversions.

**Comment by Gama11** [comment]
@nadako can we close this now?

**Comment by nadako** [comment]
I guess..
